In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 207", "Table 208", "Table 209", "Table 210"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

,LGA,POULTRY,LIVESTOCK,CROPS,FISHERY,TRADING,THRIFT/CREDIT,REAL ESTATE,OTHER SMEs,TOTAL
0,AGUATA,0.0,30000000.0,0.0,0.0,10793182.0,0.0,0.0,0.0,40793182.0
1,ANAMBRA EAST,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ANAMBRA WEST,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ANAOCHA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AWKA NORTH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
columns = ['lga_id', 'smes', 'year', 'loan_amount']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"]) == 0):
            print(row["LGA"])
        # print(row)
        else:
            for col in df.columns[1:-1]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'smes': col,
                    'year': year,
                    'loan_amount': row[col],
                },]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_9900\996318725.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id           smes  year  loan_amount
0      13        POULTRY  2019          0.0
1      13      LIVESTOCK  2019    5865909.0
2      13          CROPS  2019          0.0
3      13        FISHERY  2019          0.0
4      13        TRADING  2019   10793182.0
5      13  THRIFT/CREDIT  2019          0.0
6      13    REAL ESTATE  2019          0.0
7      13     OTHER SMEs  2019          0.0
8      18        POULTRY  2019          0.0
9      18      LIVESTOCK  2019          0.0
10     18          CROPS  2019          0.0
11     18        FISHERY  2019          0.0
12     18        TRADING  2019          0.0
13     18  THRIFT/CREDIT  2019          0.0
14     18    REAL ESTATE  2019          0.0
15     18     OTHER SMEs  2019          0.0
16      2        POULTRY  2019          0.0
17      2      LIVESTOCK  2019          0.0
18      2          CROPS  2019          0.0
19      2        FISHERY  2019          0.0
20      2        TRADING  2019          0.0
21      2  THRIFT/CREDIT  2019          0.0

In [5]:
new_df['loan_amount']=new_df['loan_amount'].astype(int)
new_df.head()

  lga_id       smes  year  loan_amount
0     13    POULTRY  2019            0
1     13  LIVESTOCK  2019      5865909
2     13      CROPS  2019            0
3     13    FISHERY  2019            0
4     13    TRADING  2019     10793182

In [6]:
new_df.to_excel("loans_to_smes.xlsx", index=False)
print("Done!")

Done!