In [1]:
import pandas as pd

In [3]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 203", "Table 204", "Table 205", "Table 206"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [4]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

,LGA,POULTRY,LIVESTOCK,CROPS,FISHERY,TRADING,THRIFT/CREDIT,REAL ESTATE,OTHER SMEs,TOTAL
0,AGUATA,0.0,0.0,1522000.0,0.0,4777905.0,0.0,0.0,2185000,8484905
1,ANAMBRA EAST,0.0,0.0,7142650.0,0.0,2936405.0,0.0,0.0,1004000,11083055
2,ANAMBRA WEST,0.0,0.0,1679650.0,280000.0,2527905.0,0.0,0.0,2955000,7442555
3,ANAOCHA,300000.0,0.0,6635686.0,0.0,6029009.0,0.0,0.0,1386400,14351096
4,AWKA NORTH,0.0,0.0,1774500.0,0.0,2727905.0,0.0,0.0,925000,5427405

In [6]:
columns = ['lga_id', 'cooperative', 'year', 'loan_amount']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"]) == 0):
            print(row["LGA"])
        # print(row)
        else:
            for col in df.columns[1:-1]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'cooperative': col,
                    'year': year,
                    'loan_amount': row[col],
                },]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    cooperative  year loan_amount
0      13        POULTRY  2019     2000000
1      13      LIVESTOCK  2019     2000000
2      13          CROPS  2019     3082800
3      13        FISHERY  2019     2500000
4      13        TRADING  2019     3088642
5      13  THRIFT/CREDIT  2019           0
6      13    REAL ESTATE  2019           0
7      13     OTHER SMEs  2019     1345000
8      18        POULTRY  2019     2000000
9      18      LIVESTOCK  2019     1000000
10     18          CROPS  2019     6833000
11     18        FISHERY  2019     2700000
12     18        TRADING  2019     1412500
13     18  THRIFT/CREDIT  2019           0
14     18    REAL ESTATE  2019           0
15     18     OTHER SMEs  2019     2000000
16      2        POULTRY  2019     2500000
17      2      LIVESTOCK  2019     1500000
18      2          CROPS  2019     3590000
19      2        FISHERY  2019     2280000
20      2        TRADING  2019     2955000
21      2  THRIFT/CREDIT  2019           0

In [8]:
new_df['loan_amount']=new_df['loan_amount'].astype(int)
new_df.head()

  lga_id cooperative  year  loan_amount
0     13     POULTRY  2019      2000000
1     13   LIVESTOCK  2019      2000000
2     13       CROPS  2019      3082800
3     13     FISHERY  2019      2500000
4     13     TRADING  2019      3088642

In [9]:
new_df.to_excel("loans_to_cooperatives.xlsx", index=False)
print("Done!")

Done!