In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 103", "Table 104", "Table 105", "Table 106"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)
    dfs[index].replace('s', 5, inplace=True)


dfs[1].head()

,S/N,LGA,JAN,FEB,MAR,APRIL,MAY,JUNE,JULY,AUG,SEPT,OCT,NOV,DEC,TOTAL
0,1,IDEMILI SOUTH,18.0,15,20,0.0,12,24,21,26,14,20,30.0,25.0,225
1,2,ONITSHA NORTH,16.0,28,16,0.0,34,26,32,18,36,12,21.0,18.0,257
2,3,OGBARU,6.0,8,6,0.0,13,8,10,4,3,4,5.0,4.0,71
3,4,EKWUSIGO,6.0,6,3,0.0,3,13,10,14,10,5,6.0,9.0,85
4,5,ANAOCHA,10.0,12,13,0.0,9,7,8,9,13,6,11.0,9.0,107

In [4]:
lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [18]:
columns = ['lga_id', 'timestamp', 'building_plans']
months = {"JAN":"01", "FEB":"02","MAR":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUG":"08","SEPT":"09","OCT":"10","NOV":"11","DEC":"12"}


new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for i, row in df.iterrows():
        lgas = row["LGA"].split('/')
        print(lgas)
        for lga in lgas:
            for column in df.columns[2:-1]:
                
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df["lga_name"]==(lga if lga != 'WEST' else 'ANAMBRA WEST'), 'lga_id'].values[0],
                    'timestamp': str(months[column])+"-01-"+str(year),
                    'building_plans': row[column],
                }]
                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

['IDEMILI SOUTH']
['ONITSHA NORTH']
['OGBARU']
['EKWUSIGO']
['ANAOCHA']
['NJIKOKA']
['NNEWI NORTH']
['ONITSHA SOUTH']
['ORUMBA NORTH']
['AWKA SOUTH']
['AGUATA']
['NNEWI SOUTH']
['DUNUKOFIA', 'AYAMELUM']
['ORUMBA SOUTH']
['IHIALA']
['OYI']
['IDEMILI NORTH']
['ANAMBRA EAST', 'WEST']
['AWKA NORTH']
['IDEMILI SOUTH']
['ONITSHA NORTH']
['OGBARU']
['EKWUSIGO']
['ANAOCHA']
['NJIKOKA']
['NNEWI NORTH']
['ONITSHA SOUTH']
['ORUMBA NORTH']
['AWKA SOUTH']
['AGUATA']
['NNEWI SOUTH']
['DUNUKOFIA', 'AYAMELUM']
['ORUMBA SOUTH']
['IHIALA']
['OYI']
['IDEMILI NORTH']
['ANAMBRA EAST', 'WEST']
['AWKA NORTH']
['IDEMILI SOUTH']
['ONITSHA NORTH']
['OGBARU']
['EKWUSIGO']
['ANAOCHA']
['NJIKOKA']
['NNEWI NORTH']
['ONITSHA SOUTH']
['ORUMBA NORTH']
['AWKA SOUTH']
['AGUATA']
['NNEWI SOUTH']
['DUNUKOFIA', 'AYAMELUM']
['ORUMBA SOUTH']
['IHIALA']
['OYI']
['IDEMILI NORTH']
['ANAMBRA EAST', 'WEST']
['AWKA NORTH']
['IDEMILI SOUTH']
['ONITSHA NORTH']
['OGBARU']
['EKWUSIGO']
['ANAOCHA']
['NJIKOKA']
['NNEWI NORTH']
['ONITSHA SOUTH']
['ORUMBA NORTH']
['AWKA SOUTH']
['AGUATA']
['NNEWI SOUTH']
['DUNUKOFIA', 'AYAMELUM']
['ORUMBA SOUTH']
['IHIALA']
['OYI']
['IDEMILI NORTH']
['ANAMBRA EAST', 'WEST']
['AWKA NORTH']

   lga_id   timestamp building_plans
0       3  01-01-2019             18
1       3  02-01-2019             15
2       3  03-01-2019             20
3       3  04-01-2019             21
4       3  05-01-2019             26
5       3  06-01-2019             24
6       3  07-01-2019             30
7       3  08-01-2019             15
8       3  09-01-2019             15
9       3  10-01-2019           15.0
10      3  11-01-2019             12
11      3  12-01-2019             10
12     14  01-01-2019             16
13     14  02-01-2019             28
14     14  03-01-2019             16
15     14  04-01-2019             32
16     14  05-01-2019             18
17     14  06-01-2019             26
18     14  07-01-2019             19
19     14  08-01-2019             17
20     14  09-01-2019             20
21     14  10-01-2019           15.0

In [20]:
new_df["building_plans"] = new_df["building_plans"].astype(int)
new_df.head()

  lga_id   timestamp  building_plans
0      3  01-01-2019              18
1      3  02-01-2019              15
2      3  03-01-2019              20
3      3  04-01-2019              21
4      3  05-01-2019              26

In [21]:
new_df.to_excel("building_plan.xlsx", index=False)
print("Done!")

Done!