In [1]:
import pandas as pd

In [16]:
df = pd.read_excel("no_of_public_building.xlsx")

In [17]:
df = df.fillna(0)
df.replace(['NA', 'NIL'], 0, inplace=True)
df.replace('s', 5, inplace=True)

In [18]:
lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [20]:
columns = ['lga_id', 'timestamp_year', 'num_of_buildings']

new_df = pd.DataFrame(columns=columns)

for i, row in df.iterrows():   
    lga_id =  lga_df.loc[lga_df["lga_name"]==row["LGA"].strip().upper(), 'lga_id'].values[0]
    
    for column in df.columns[1:]:
        
        transformed_data = [{
            'lga_id': lga_id,
            'timestamp_year': "01-01-"+str(column),
            'num_of_buildings': row[column],
        }]
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id timestamp_year num_of_buildings
0      13     01-01-2019                2
1      13     01-01-2020                3
2      13     01-01-2021                0
3      13     01-01-2022                1
4      13     01-01-2023                5
5      13     01-01-2024                2
6      18     01-01-2019                8
7      18     01-01-2020                0
8      18     01-01-2021                7
9      18     01-01-2022                0
10     18     01-01-2023                2
11     18     01-01-2024                1
12      2     01-01-2019                1
13      2     01-01-2020                0
14      2     01-01-2021                0
15      2     01-01-2022                0
16      2     01-01-2023                2
17      2     01-01-2024                0
18      9     01-01-2019                0
19      9     01-01-2020                0
20      9     01-01-2021                0
21      9     01-01-2022                0

In [21]:
new_df["num_of_buildings"] = new_df["num_of_buildings"].astype(int)
new_df.head()

  lga_id timestamp_year  num_of_buildings
0     13     01-01-2019                 2
1     13     01-01-2020                 3
2     13     01-01-2021                 0
3     13     01-01-2022                 1
4     13     01-01-2023                 5

In [22]:
new_df.to_excel("transposedb/no_of_public_buildings.xlsx", index=False)
print("Done!")

Done!