In [40]:
import pandas as pd

In [ ]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 14", "Table 15", "Table 16", "Table 17"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,zone,196,20,48
1,2,ANAMBRA WEST,zone,613,15,21
2,3,IDEMILI SOUTH,zone,145,20,25
3,4,NNEWI SOUTH,zone,176,34,38
4,5,OYI,zone,331,10,40

In [42]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

            LGA  CATTLE  SHEEP  GOAT   PIG
0        AGUATA    5992      0  1630  1036
1  ANAMBRA EAST       0      0     0     0
2  ANAMBRA WEST       0      0     0     0
3       ANAOCHA    1806      0     0     0
4    AWKA NORTH    7880      0     0     0

In [43]:
columns = ['lga_id', 'livestock_slaughtered', 'year', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'livestock_slaughtered': "CATTLE",
                'year': year,
                'population': row["CATTLE"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'livestock_slaughtered': "SHEEP",
                'year': year,
                'population': row["SHEEP"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'livestock_slaughtered': "GOAT",
                'year': year,
                'population': row["GOAT"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'livestock_slaughtered': "PIG",
                'year': year,
                'population': row["PIG"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_8496\2566503958.py:34: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id livestock_slaughtered  year  population
0      13                CATTLE  2019      4420.0
1      13                 SHEEP  2019         0.0
2      13                  GOAT  2019       816.0
3      13                   PIG  2019       760.0
4      18                CATTLE  2019         0.0
5      18                 SHEEP  2019         0.0
6      18                  GOAT  2019         0.0
7      18                   PIG  2019         0.0
8       2                CATTLE  2019         0.0
9       2                 SHEEP  2019         0.0
10      2                  GOAT  2019         0.0
11      2                   PIG  2019         0.0
12      9                CATTLE  2019      2882.0
13      9                 SHEEP  2019         0.0
14      9                  GOAT  2019         0.0
15      9                   PIG  2019         0.0
16     15                CATTLE  2019      9267.0
17     15                 SHEEP  2019         0.0
18     15                  GOAT  2019         0.0
19     15                   PIG  2019         0.0
20     20                CATTLE  2019      2550.0
21     20                 SHEEP  2019         0.0

In [44]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id livestock_slaughtered  year  population
0     13                CATTLE  2019        4420
1     13                 SHEEP  2019           0
2     13                  GOAT  2019         816
3     13                   PIG  2019         760
4     18                CATTLE  2019           0

In [45]:
new_df.to_excel("slaughtered_livestock.xlsx", index=False)
print("Done!")

Done!