In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 107", "Table 108", "Table 109", "Table 110"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

,LGA,COMMUNITIES AFFECTED BY EROSION,AREA OF LAND AFFECTED BY EROSION (HECTARES),NUMBER OF HOUSES AFFECTED,AREA OF LAND RECLAIMED/STABILIZED,PERCENTAGE COMPLETION OF WORKS
0,AGUATA,0,0.0,0.0,0.0,0.0
1,ANAMBRA EAST,0,0.0,0.0,0.0,0.0
2,ANAMBRA WEST,0,0.0,0.0,0.0,0.0
3,ANAOCHA,0,0.0,0.0,0.0,0.0
4,AWKA NORTH,0,0.0,0.0,0.0,0.0

In [7]:
columns = ['lga_id', 'year', 'community', 'area_of_land_affected(hectares)', 'no_of_houses_affected', 'area_of_land_reclaimed', 'percentage_completion_of_works']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if row["COMMUNITIES AFFECTED BY EROSION"] in (0, '0'): continue
        if(row["LGA"] not in (0, '0')): lga=row["LGA"]
        
        if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"]) == 0):
            print(row["LGA"])
        # print(row)
        transformed_data = [{
            'lga_id': lga_df.loc[lga_df['lga_name'] == lga, "lga_id"].values[0],
            'year': year,
            'community': row["COMMUNITIES AFFECTED BY EROSION"],
            'area_of_land_affected(hectares)': row["AREA OF LAND AFFECTED BY EROSION (HECTARES)"],
            'no_of_houses_affected': row["NUMBER OF HOUSES AFFECTED"],
            'area_of_land_reclaimed': row["AREA OF LAND RECLAIMED/STABILIZED"],
            'percentage_completion_of_works': row["PERCENTAGE COMPLETION OF WORKS"]*100
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_7664\2612320939.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

,lga_id,year,community,area_of_land_affected(hectares),no_of_houses_affected,area_of_land_reclaimed,percentage_completion_of_works
0,20,2019,"Amachalla, Awka",47.5,752.0,46.3,97.50
1,20,2019,"Federal High Court/Ekwueme Square,\nAwka (Pall...",26.6,53.0,26.6,100.00
2,20,2019,"Neroz Plaza/ St Thomas Aquinas\nCommunity, Awka",16.8,151.0,16.8,100.00
3,8,2019,"Ugamuma Village, Obosi",221.0,2161.0,41.3,17.71
4,8,2019,"Ire Village, Obosi",156.0,3495.0,80.9,49.00
5,8,2019,Flyover-Flyover,137.0,1080.0,66.4,46.40
6,8,2019,"Abidi Village, Umuoji",704.0,6580.0,482.8,68.00
7,8,2019,"Ndiagu, Ikenga, Ogidi",158.0,1112.0,88.5,53.00
8,3,2019,Ojoto,925.5,2488.0,355.7,38.00
9,11,2019,Abagana,443.0,2764.0,171.8,38.00
10,11,2019,Enugwu-Ukwu,99.0,680.0,15.1,14.00
11,10,2019,"Nnewichi, Nnewi",1117.0,8669.0,433.6,38.00
12,14,2019,"New Heritage/Omagba, Onitsha",78.0,836.0,74.7,94.00
13,20,2020,"Amachalla, Awka",47.5,760.0,47.5,100.00
14,20,2020,"Federal High Court/Ekwueme Square, Awka (Palli...",26.6,53.0,26.6,100.00
15,20,2020,"Neroz Plaza/ St Thomas Aquinas Community, Awka",16.8,151.0,16.8,100.00
16,8,2020,"Ugamuma Village, Obosi",225.0,2361.0,90.6,38.90
17,8,2020,"Ire Village, Obosi",159.0,3595.0,110.6,67.00
18,8,2020,Flyover-Flyover,139.0,1170.0,74.4,52.02
19,8,2020,"Abidi Village, Umuoji",706.0,6730.0,625.2,88.05
20,8,2020,"Ndiagu, Ikenga, Ogidi",161.0,1212.0,89.3,53.50
21,3,2020,Ojoto,929.0,2568.0,749.0,80.00

In [8]:
new_df.to_excel("communities_affected_by_erosion.xlsx", index=False)
print("Done!")

Done!