In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 107", "Table 108", "Table 109", "Table 110"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

,LGA,COMMUNITIES AFFECTED BY EROSION,AREA OF LAND AFFECTED BY EROSION (HECTARES),NUMBER OF HOUSES AFFECTED,AREA OF LAND RECLAIMED/STABILIZED,PERCENTAGE COMPLETION OF WORKS
0,AGUATA,0,0.0,0.0,0.0,0.0
1,ANAMBRA EAST,0,0.0,0.0,0.0,0.0
2,ANAMBRA WEST,0,0.0,0.0,0.0,0.0
3,ANAOCHA,0,0.0,0.0,0.0,0.0
4,AWKA NORTH,0,0.0,0.0,0.0,0.0

In [10]:
columns = ['lga_id', 'year', 'community', 'area_of_land_affected(hectares)', 'no_of_houses_affected', 'area_of_land_reclaimed', 'percentage_completion_of_works']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if row["COMMUNITIES AFFECTED BY EROSION"] in (0, '0'): continue
        if(row["LGA"] not in (0, '0')): lga=row["LGA"]
        
        if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"]) == 0):
            print(row["LGA"])
        # print(row)
        transformed_data = [{
            'lga_id': lga_df.loc[lga_df['lga_name'] == lga, "lga_id"].values[0],
            'year': year,
            'community': row["COMMUNITIES AFFECTED BY EROSION"].replace("\n", " ").strip(),
            'area_of_land_affected(hectares)': row["AREA OF LAND AFFECTED BY EROSION (HECTARES)"],
            'no_of_houses_affected': row["NUMBER OF HOUSES AFFECTED"],
            'area_of_land_reclaimed': row["AREA OF LAND RECLAIMED/STABILIZED"],
            'percentage_completion_of_works': row["PERCENTAGE COMPLETION OF WORKS"]
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.tail(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_12040\2370511419.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

,lga_id,year,community,area_of_land_affected(hectares),no_of_houses_affected,area_of_land_reclaimed,percentage_completion_of_works
30,8,2021,"Ire Village, Obosi",162.0,3695.0,110.6,0.6700
31,8,2021,Flyover-Flyover,141.0,1260.0,74.4,0.5202
32,8,2021,"Abidi Village, Umuoji",710.0,6880.0,710.0,1.0000
33,8,2021,"Ndiagu, Ikenga, Ogidi",164.0,1312.0,100.0,0.6000
34,3,2021,Ojoto,936.0,2648.0,936.0,1.0000
35,11,2021,Abagana,449.0,2964.0,312.0,0.6900
36,11,2021,Enugwu-Ukwu,106.8,880.0,106.0,0.9900
37,10,2021,"Nnewichi, Nnewi",1133.0,9469.0,1067.0,0.9350
38,14,2021,"New Heritage/Omagba, Onitsha",79.0,856.0,79.0,0.9940
39,20,2022,"Amachalla, Awka",47.5,760.0,47.5,1.0000
40,20,2022,"Federal High Court/Ekwueme Square, Awka (Palli...",26.6,53.0,26.6,1.0000
41,20,2022,"Neroz Plaza/ St Thomas Aquinas Community, Awka",16.8,151.0,16.8,1.0000
42,8,2022,"Ugamuma Village, Obosi",233.0,3961.0,128.2,0.5500
43,8,2022,"Ire Village, Obosi",165.0,3795.0,157.0,0.8000
44,8,2022,Flyover-Flyover,143.0,1350.0,82.9,0.5800
45,8,2022,"Abidi Village, Umuoji",710.0,7180.0,710.0,1.0000
46,8,2022,"Ndiagu, Ikenga, Ogidi",167.0,1512.0,116.9,0.7000
47,3,2022,Ojoto,936.0,2808.0,936.0,1.0000
48,11,2022,Abagana,452.0,3164.0,321.0,0.7100
49,11,2022,Enugwu-Ukwu,108.0,1080.0,108.0,1.0000
50,10,2022,"Nnewichi, Nnewi",1141.0,10269.0,1141.0,1.0000
51,14,2022,"New Heritage/Omagba, Onitsha",79.5,876.0,79.5,1.0000

In [8]:
new_df["no_of_houses_affected"] = new_df["no_of_houses_affected"].astype(int)
new_df.head()

,lga_id,year,community,area_of_land_affected(hectares),no_of_houses_affected,area_of_land_reclaimed,percentage_completion_of_works
0,20,2019,"Amachalla, Awka",47.5,752,46.3,0.9750
1,20,2019,"Federal High Court/Ekwueme Square, Awka (Palli...",26.6,53,26.6,1.0000
2,20,2019,"Neroz Plaza/ St Thomas Aquinas Community, Awka",16.8,151,16.8,1.0000
3,8,2019,"Ugamuma Village, Obosi",221.0,2161,41.3,0.1771
4,8,2019,"Ire Village, Obosi",156.0,3495,80.9,0.4900

In [9]:
new_df.to_excel("communities_affected_by_erosion.xlsx", index=False)
print("Done!")

Done!