In [1]:
import pandas as pd

In [24]:
erosion_sites = pd.read_excel("erosion_sites_in_anambra.xlsx")
erosion_sites.head()

                          SITE          TOWN            LGA
0            Ndiokpalaeze Road  Ndiokpalaeze   Orumba North
1    Agu Mgbala Ivollo Village       Mbaukwu     Awka South
2           Golden Tulip Hotel         Agulu        Anaocha
3           Ugwuagbada Village        Umunze   Orumba South
4  Along Onitsha – Owerri Road           Oba  Idemili South

In [25]:
lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [26]:
mapping = lga_df.set_index('lga_name')['lga_id'].to_dict()
erosion_sites['LGA'] = erosion_sites['LGA'].str.upper().str.strip()
erosion_sites['site'] = erosion_sites['SITE'].str.strip()
erosion_sites['town'] = erosion_sites['TOWN'].str.strip()

erosion_sites["lga_id"] = erosion_sites["LGA"].map(mapping)
erosion_sites = erosion_sites.drop(columns=['LGA', 'SITE', 'TOWN'])

erosion_sites.head(50)

                                              site          town  lga_id
0                                Ndiokpalaeze Road  Ndiokpalaeze       7
1                        Agu Mgbala Ivollo Village       Mbaukwu      20
2                               Golden Tulip Hotel         Agulu       9
3                               Ugwuagbada Village        Umunze      21
4                      Along Onitsha – Owerri Road           Oba       3
5                             Enugwu/Abari Village        Nsugbe      18
6                                Nwakpadolu Estate          Awka      20
7                    Anambra/Imo Transport Company       Onitsha      14
8                                             Abba          Abba      11
9                          Along Arthur Eze Avenue          Awka      20
10                        Catholic Pastoral Centre        Okpuno      20
11                               Ifite-Ani Village         Agulu       9
12                                  Odida Nnewichi         Nnewi      10
13                 Opposite Uru Industries, Umudim         Nnewi      10
14                       St. Jude, Amaeze Quarters       Aguleri      18
15                                  Enuagu Village   Enugwu-Ukwu      11
16                               Umuonicha Village       Ebenebe      15
17                        Iyiagu Flood Restoration          Awka      20
18                 Cosmetics and Provisions Market      Ogbunike       5
19                               Along Ukpo Bypass          Ukpo      12
20                               Amaezike Quarters       Mgbakwu      15
21                   St. Raphael’s Catholic Parish        Okpoko      19
22                       Utuh/Osumenyi Communities          Utuh       4
23                        Oye-Abba Ezimezi Village       Amawbia      20
24                                  Aguachi Layout        Okpuno      20
25                    Our Lady of Lourdes Hospital        Ihiala      16
26  Nwannu Land, Abuja Estate, Behind Zontal Fobis          Awka      20
27                                  Ibollo Village      Oraifite      17
28                          Uke Street/Access Road      Ogbunike       5
29                        Igbakw/Ifite-Ogwari Road  Ifite-Ogwari       6
30                                    Nkwoedo Area      Oraifite      17
31         Along Obodo Obinagu Road, Oranto Orofia          Ukpo      12
32                                       Umuchiana     Ekwulobia      13
33                                          Ezioko           Oko       7
34                    Along Umunze/Ogbunka Highway        Umunze      21
35                                          Ukwulu        Ukwulu      12
36                                     Obe Village         Agulu       9
37                 Isiorji Quarters, Ifite village          Awka      20
38                             Grand Riveria Hotel          Awka      20
39                                  Ndiagu Village       Mbaukwu      20
40                       Muogbo Street, Mkputamkpu         Obosi       8
41                                Umuezeagu Uruagu         Nnewi      10
42                                Customs Barracks       Onitsha      14
43                                        Osumenyi      Osumenyi       4
44                                           Ezira         Ezira      21
45          St. Paul’s Theological College, Umudim         Nnewi      10
46     St. Paul’s Anglican Primary School, Ebenesi         Nnobi       3
47                         St. Pius Primary school          Nimo      11
48                SS John and Paul Church, Umubele          Awka      20
49                                 Amatutu Village         Agulu       9

In [27]:
erosion_sites.to_excel("transposedb/erosion_sites_in_anambra_transposed.xlsx", index=False)
print("Done!")

Done!