In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 125", "Table 126", "Table 127", "Table 128"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,MONTH,NUMBER OF FIRE INCIDENTS,FALSE CALL,NUMBER OF DEATH,NUMBER OF INJURED PERSONS,ESTIMATED VALUE OF PROPERTIES LOST,ESTIMATED VALUE OF PROPERTIES SAVED
0,JANUARY,21,0,0,0,542300000,2275000000
1,FEBRUARY,14,1,3,0,171950000,2853000000
2,MARCH,10,0,4,2,41300000,4808100000
3,APRIL,6,0,0,0,8950000,1247000000
4,MAY,1,0,0,0,2000000,20000000

In [4]:
columns = ["timestamp", "no_of_fire_incidents", "false_call", "no_of_death", "no_of_persons_injured", "est_value_of_property_lost", "est_value_of_property_saved"]
new_df = pd.DataFrame(columns=columns)
months = {"JANUARY":"01", "FEBRUARY":"02","MARCH":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUGUST":"08","SEPTEMBER":"09","OCTOBER":"10","NOVEMBER":"11","DECEMBER":"12"}

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'timestamp': months[row["MONTH"]] + "-01-" + str(year),
            'no_of_fire_incidents': row['NUMBER OF FIRE INCIDENTS'],
            'false_call': row["FALSE CALL"],
            'no_of_death' : row["NUMBER OF DEATH"],
            'no_of_persons_injured': row['NUMBER OF INJURED PERSONS'],
            'est_value_of_property_lost': row['ESTIMATED VALUE OF PROPERTIES LOST'],
            'est_value_of_property_saved': row['ESTIMATED VALUE OF PROPERTIES SAVED'],
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,timestamp,no_of_fire_incidents,false_call,no_of_death,no_of_persons_injured,est_value_of_property_lost,est_value_of_property_saved
0,01-01-2019,21,0,0,0,542300000,2275000000
1,02-01-2019,14,1,3,0,171950000,2853000000
2,03-01-2019,10,0,4,2,41300000,4808100000
3,04-01-2019,6,0,0,0,8950000,1247000000
4,05-01-2019,1,0,0,0,2000000,20000000
5,06-01-2019,4,0,0,0,31200000,111500000
6,07-01-2019,8,0,0,0,28231500,230000000
7,08-01-2019,10,0,0,0,135000000,2407000000
8,09-01-2019,2,0,0,0,4500000,120000000
9,10-01-2019,4,0,6,0,10106000000,102200000000
10,11-01-2019,11,0,2,0,34610000,2534000000
11,12-01-2019,32,0,0,1,274795000,6980200000
12,01-01-2020,42,0,2,0,500138900000,3688000000
13,02-01-2020,40,0,0,0,1201370000,74215500000
14,03-01-2020,12,0,0,0,10775000,975700000
15,04-01-2020,8,0,0,0,9355000,301000000
16,05-01-2020,10,0,0,1,70500000,441500000
17,06-01-2020,5,0,0,0,11200000,241000000
18,07-01-2020,12,0,0,0,323521000,1078800000
19,08-01-2020,6,0,0,0,360650000,720000000
20,09-01-2020,1,0,0,0,70000,10000000
21,10-01-2020,3,0,0,0,1600000,240000000

In [5]:
new_df.to_excel("fire_incidents_by_month.xlsx", index=False)
print("Done!")

Done!