In [1]:
import pandas as pd

In [5]:
years = [2022]
sheets = ["Table 130"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [6]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,DESCRIPTION OF PREMISES,NUMBER OF FIRE INCIDENTS,NUMBER OF LIVES LOST,NUMBER OF PERSONS UNHURT,NUMBER OF PERSONS INJURED,ESTIMATED VALUE OF PROPERTY LOST,ESTIMATED VALUE OF PROPERTY SAVED
0,PUBLIC BUILDING,13,0,0,0,3151050000,24560000000
1,PRIVATE DWELLING,36,0,0,0,371800000,3924000000
2,EDUCATIONAL ESTABLISHMENT,6,0,0,0,6600000,1680000000
3,SHOP,14,0,0,0,45430000,610000000
4,"CLUBS, HOTELS, RESTAURANTS",1,0,0,0,30000000,700000000

In [7]:
columns = ["year", "premises", "no_of_fire_incidents", "no_of_lives_lost", "no_of_unhurt_persons", "no_of_persons_injured", "est_value_of_property_lost", "est_value_of_property_saved"]
new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'year': year,
            'premises': row['DESCRIPTION OF PREMISES'],
            'no_of_fire_incidents': row['NUMBER OF FIRE INCIDENTS'],
            'no_of_lives_lost': row['NUMBER OF LIVES LOST'],
            'no_of_unhurt_persons': row['NUMBER OF PERSONS UNHURT'],
            'no_of_persons_injured': row['NUMBER OF PERSONS INJURED'],
            'est_value_of_property_lost': row['ESTIMATED VALUE OF PROPERTY LOST'],
            'est_value_of_property_saved': row['ESTIMATED VALUE OF PROPERTY SAVED'],
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,year,premises,no_of_fire_incidents,no_of_lives_lost,no_of_unhurt_persons,no_of_persons_injured,est_value_of_property_lost,est_value_of_property_saved
0,2022,PUBLIC BUILDING,13,0,0,0,3151050000,24560000000
1,2022,PRIVATE DWELLING,36,0,0,0,371800000,3924000000
2,2022,EDUCATIONAL ESTABLISHMENT,6,0,0,0,6600000,1680000000
3,2022,SHOP,14,0,0,0,45430000,610000000
4,2022,"CLUBS, HOTELS, RESTAURANTS",1,0,0,0,30000000,700000000
5,2022,FACTORIES,3,0,0,0,130000000,900000000
6,2022,RESCUE OPERATION,0,0,0,0,0,0
7,2022,OIL AND GAS INSTALLATIONS,2,0,0,0,19000000,900000000
8,2022,BUSH/REFUSE DUMP,12,0,0,0,5070000,1135000000
9,2022,ROADS,33,11,0,5,553700000,7405500000
10,2022,MARKET,15,6,0,6,589000000,57170000000
11,2022,TRANSFORMER,0,0,0,0,0,0
12,2022,TIMBER SHEDS,1,0,0,0,5000000,85000000

In [8]:
new_df.to_excel("fire_incidents_by_type_of_premises.xlsx", index=False)
print("Done!")

Done!