In [1]:
import pandas as pd

In [2]:
years = [2022]
sheets = ["Table 129"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,CAUSE OF FIRE INCIDENCE,NUMBER OF FIRE INCIDENTS,ESTIMATED VALUE OF PROPERTY LOST,ESTIMATED VALUE OF PROPERTY SAVED
0,ELECTRICAL EQUIPMENT,1,5000000,20000000
1,CANDLE,1,1500000,20000000
2,HIGH VOLTAGE FROM EEDC,1,6000000,20000000
3,CIGARETTE STUBS,1,0,10000000
4,ILLEGAL STORAGE OF PETROLEUM,0,0,0

In [4]:
columns = ["year", "causes", "no_of_fire_incidents", "est_value_of_property_lost", "est_value_of_property_saved"]
new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'year': year,
            'causes': row['CAUSE OF FIRE INCIDENCE'],
            'no_of_fire_incidents': row['NUMBER OF FIRE INCIDENTS'],
            'est_value_of_property_lost': row['ESTIMATED VALUE OF PROPERTY LOST'],
            'est_value_of_property_saved': row['ESTIMATED VALUE OF PROPERTY SAVED'],
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,year,causes,no_of_fire_incidents,est_value_of_property_lost,est_value_of_property_saved
0,2022,ELECTRICAL EQUIPMENT,1,5000000,20000000
1,2022,CANDLE,1,1500000,20000000
2,2022,HIGH VOLTAGE FROM EEDC,1,6000000,20000000
3,2022,CIGARETTE STUBS,1,0,10000000
4,2022,ILLEGAL STORAGE OF PETROLEUM,0,0,0
5,2022,ELECTRICAL SPARK,31,470920000,6393000000
6,2022,LEAKAGE FROM TANK,4,4500000,470000000
7,2022,MECHANICAL FAULT ACCIDENT,22,408300000,5710500000
8,2022,UNDER INVESTIGATION,0,0,0
9,2022,EXPLOSION,2,100200000,2500000000
10,2022,UNKNOWN,37,1082500000,57631000000
11,2022,BUSH BURNING,21,217400000,3595000000
12,2022,GAS,4,4000000,665000000
13,2022,ARSON,1,2500000000,20000000000
14,2022,CARELESSNESS,10,106330000,2035000000

In [5]:
new_df.to_excel("fire_incidents_by_causes.xlsx", index=False)
print("Done!")

Done!