In [1]:
import pandas as pd

In [13]:
years = [2019, 2020, 2022]
sheets = ["Table 115", "Table 116", "Table 117"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [14]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

# dfs[1].head()

In [15]:

# # communities affected_by_erosion
# columns = ['id', 'lga_id', 'community']
# community_df = pd.DataFrame(columns=columns)
# for i , df in enumerate(dfs):
#     for index, row in df.iterrows():
#         if row["COMMUNITIES AFFECTED BY FLOOD"] in (0, '0'): continue

#         if(row["LGA"] not in (0, '0')): lga=row["LGA"]

#         if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"]) == 0):
#             print(row["LGA"])
#         lga_id = lga_df.loc[lga_df["lga_name"] == lga, "lga_id"].values[0]
#         communities = row["COMMUNITIES AFFECTED BY FLOOD"].split(',')
#         # print(communities)
#         for community in communities:
#             transformed_data = [{
#                 "lga_id": lga_id,
#                 'community': community.replace("\n", " ").strip()
#             },]   

#             community_df = pd.concat([community_df, pd.DataFrame(transformed_data)], ignore_index=True)

# community_df = community_df.drop_duplicates()
# community_df['id'] = community_df.index
# community_df.head()

In [16]:
# community_df.to_excel("communities.xlsx", index=False)
# print("Done!")

In [17]:
columns = ['id', 'lga_id', 'year', 'no_of_household_affected_by_flood', 'no_of_household_supported']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if row["COMMUNITIES AFFECTED BY FLOOD"] in (0, '0'): continue

        if(row["LGA"] not in (0, '0')): lga=row["LGA"]
        
        if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"]) == 0):
            print(row["LGA"])
        lga_id = lga_df.loc[lga_df["lga_name"] == lga, "lga_id"].values[0]

        transformed_data = [{
            'lga_id': lga_id,
            'year': year,
            'no_of_household_affected_by_flood': row["NUMBER OF HOUSEHOLD AFFECTED BY FLOOD"],
            'no_of_household_supported': row["NUMBER OF HOUSEHOLD SUPPORTED"],
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df['id']=new_df.index
new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_8680\3006083654.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

,id,lga_id,year,no_of_household_affected_by_flood,no_of_household_supported
0,0,18,2019,178.0,178.0
1,1,2,2019,479.0,479.0
2,2,15,2019,70.0,70.0
3,3,6,2019,44.0,44.0
4,4,8,2019,152.0,152.0
5,5,16,2019,19.0,19.0
6,6,19,2019,499.0,499.0
7,7,14,2019,2.0,2.0
8,8,18,2020,11867.0,11867.0
9,9,2,2020,16796.0,16796.0
10,10,15,2020,511.0,511.0
11,11,6,2020,8851.0,8851.0
12,12,17,2020,217.0,217.0
13,13,3,2020,187.0,187.0
14,14,16,2020,1683.0,1683.0
15,15,19,2020,21863.0,21863.0
16,16,14,2020,383.0,383.0
17,17,1,2020,168.0,168.0
18,18,18,2022,23460.0,18476.0
19,19,2,2022,65996.0,52797.0
20,20,15,2022,7076.0,6368.0
21,21,6,2022,2989.0,2690.0

In [18]:
new_df["no_of_household_affected_by_flood"] = new_df["no_of_household_affected_by_flood"].astype(int)
new_df["no_of_household_supported"] = new_df["no_of_household_supported"].astype(int)
new_df.head()

,id,lga_id,year,no_of_household_affected_by_flood,no_of_household_supported
0,0,18,2019,178,178
1,1,2,2019,479,479
2,2,15,2019,70,70
3,3,6,2019,44,44
4,4,8,2019,152,152

In [19]:
new_df.to_excel("household_affected_by_flood.xlsx", index=False)
print("Done!")

Done!

In [29]:
# household_affected_by_flood_id is the id of the household_affected_by_flood table
# communities affected_by_erosion
columns = ['household_affected_by_flood_id', 'community']
community_df = pd.DataFrame(columns=columns)
for i , df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if row["COMMUNITIES AFFECTED BY FLOOD"] in (0, '0'): continue

        if(row["LGA"] not in (0, '0')): lga=row["LGA"]

        if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"]) == 0):
            print(row["LGA"])
        lga_id = lga_df.loc[lga_df["lga_name"] == lga, "lga_id"].values[0]
        communities = row["COMMUNITIES AFFECTED BY FLOOD"].split(',')
        # len_comm = len(new_df.loc[(new_df["lga_id"]==lga_id) & (new_df["year"]==year), "id"].values)
        # if(len_comm>1):
        #     print("hasfklhjsbd")
        # elif(len_comm==0):
        #     print("hagjlaajgkallk")
        # else:
        #     print("working!")

        # print(communities)
        new_df_id = new_df.loc[(new_df["lga_id"]==lga_id) & (new_df["year"]==year), "id"].values[0]
        for community in communities:
            transformed_data = [{
                "household_affected_by_flood_id": new_df_id,
                'community': community.replace("\n", " ").strip()
            },]   

            community_df = pd.concat([community_df, pd.DataFrame(transformed_data)], ignore_index=True)

community_df = community_df.drop_duplicates()
# community_df['id'] = community_df.index
community_df.head(50)
# print(len(community_df))

   household_affected_by_flood_id      community
0                               0        Otuocha
1                               0         Umuoba
2                               0      Enugu Otu
3                               0      Mkpunando
4                               0   Eziagulu-Otu
5                               0     Ikem-Ivite
6                               0    Aguleri uno
7                               0          Nando
8                               0       Igbariam
9                               1       Ezi Anam
10                              1     Ifite Anam
11                              1     Umuenwelum
12                              1    Oroma Etiti
13                              1    Umueze-Anam
14                              1    Umuoba-Anam
15                              1         Iyiora
16                              1     Olumbanasa
17                              1           Nzam
18                              1          Inoma
19                              1         Owelle
20                              1         Ukwala
21                              2        Achalla
22                              2         Ugbene
23                              2         Ugbenu
24                              2   Awba-Ofemili
25                              3   Ifite-Ogwari
26                              3        Igbakwu
27                              3         Umueje
28                              3          Omasi
29                              3           Omor
30                              3     Umuenwerum
31                              3          Anaku
32                              3         Umumbo
33                              4          Obosi
34                              5     Ubahuekwem
35                              5           Akwa
36                              5         Ihudum
37                              5        Umudara
38                              5    Umuezeawala
39                              5          Okija
40                              5            Uli
41                              5          Umuzu
42                              6    Akili Ogidi
43                              6   Akili Ozizor
44                              6    Amiyi Atani
45                              6  Mputu Obeagwe
46                              6         Odekpe
47                              6       Ogbakuba
48                              6   Ogwu-Aniocha
49                              6     Ogwuikpele

In [30]:
community_df.to_excel("communities.xlsx", index=False)
print("Done!")

Done!