In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 121", "Table 122", "Table 123", "Table 124"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,LGA,NUMBER OF FIRE OUTBREAK,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS SAVED,NUMBER OF DEATH,ESTIMATED VALUE OF PROPERTIES LOST,ESTIMATED VALUE OF PROPERTIES SAVED
0,AGUATA,0,0,0,0,0,0
1,ANAMBRA EAST,0,0,0,0,0,0
2,ANAMBRA WEST,0,0,0,0,0,0
3,ANAOCHA,1,0,0,0,35000,15000000
4,AWKA NORTH,1,0,0,0,1000000,15000000

In [5]:
columns = ["lga_id", "year", "no_of_fire_outbreak", "no_of_persons_saved", "no_of_persons_injured", "no_of_death", "est_value_of_property_lost", "est_value_of_property_saved"]
new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'lga_id': lga_df.loc[lga_df["lga_name"]== row["LGA"], 'lga_id'].values[0],
            'year': year,
            'no_of_fire_outbreak': row['NUMBER OF FIRE OUTBREAK'],
            'no_of_persons_injured': row['NUMBER OF PERSONS INJURED'],
            'no_of_persons_saved': row['NUMBER OF PERSONS SAVED'],
            'no_of_death' : row["NUMBER OF DEATH"],
            'est_value_of_property_lost': row['ESTIMATED VALUE OF PROPERTIES LOST'],
            'est_value_of_property_saved': row['ESTIMATED VALUE OF PROPERTIES SAVED'],
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,lga_id,year,no_of_fire_outbreak,no_of_persons_saved,no_of_persons_injured,no_of_death,est_value_of_property_lost,est_value_of_property_saved
0,13,2019,0,0,0,0,0,0
1,18,2019,0,0,0,0,0,0
2,2,2019,0,0,0,0,0,0
3,9,2019,1,0,0,0,35000,15000000
4,15,2019,1,0,0,0,1000000,15000000
5,20,2019,43,0,3,4,65290000,4989200000
6,6,2019,0,0,0,0,0,0
7,12,2019,0,0,0,0,0,0
8,17,2019,0,0,0,0,0,0
9,8,2019,19,0,0,0,155400000,6644000000
10,3,2019,0,0,0,0,0,0
11,16,2019,1,0,0,3,30000000,70000000
12,11,2019,15,0,0,0,275420000,2685500000
13,10,2019,12,0,0,1,26800000,4100100000
14,4,2019,0,0,0,0,0,0
15,19,2019,3,0,0,0,510900000,980000000
16,14,2019,16,0,0,7,173591500,4342000000
17,1,2019,7,0,0,0,10118400000,101130000000
18,7,2019,0,0,0,0,0,0
19,21,2019,0,0,0,0,0,0
20,5,2019,5,0,0,0,24000000,815000000
21,13,2020,0,0,0,0,0,0

In [6]:
new_df.to_excel("fire_outbreaks_and_casualties.xlsx", index=False)
print("Done!")

Done!