In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2022]
sheets = ["Table 118", "Table 119", "Table 120"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,LGA,TYPE OF DISASTER,NUMBER OF PERSONS DISPLACED BY NATURAL DISASTER,NUMBER OF PERSONS SUPPORTED,PERCENTAGE OF THE POPULATION SUPPORTED AFTER DISASTER,NUMBER OF OPERATIONAL/ EMERGENCY SUPPORT CENTRE,NO. OF IDPS CAMPS,NO. OF PERSONS IN IDP CAMPS
0,AGUATA,0,0.0,0.0,0.0,0.0,0.0,0.0
1,ANAMBRA EAST,FLOOD,1070.0,1070.0,1.0,1.0,5.0,1059.0
2,ANAMBRA WEST,FLOOD,2875.0,2875.0,1.0,1.0,0.0,0.0
3,ANAOCHA,0,0.0,0.0,0.0,0.0,0.0,0.0
4,AWKA NORTH,FLOOD,422.0,422.0,0.0,1.0,3.0,422.0

In [4]:
columns = ["lga_id", "year", "type_of_disaster", "no_of_persons_supported",
        "no_of_persons_displaced", "percentage_population_supported",
         "no_of_emergency_centres", "no_of_idp_camps", "no_of_persons_in_idp_camps"]
new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["TYPE OF DISASTER"] in (0,'0')): continue
        transformed_data = [{
            'lga_id': lga_df.loc[lga_df["lga_name"]== row["LGA"], 'lga_id'].values[0],
            'year': year,
            'type_of_disaster': row['TYPE OF DISASTER'],
            'no_of_persons_displaced': row['NUMBER OF PERSONS DISPLACED  BY NATURAL DISASTER'],
            'no_of_persons_supported': row['NUMBER OF PERSONS SUPPORTED'],
            'percentage_population_supported' : row["PERCENTAGE OF THE POPULATION SUPPORTED AFTER DISASTER"],
            'no_of_emergency_centres': row['NUMBER OF OPERATIONAL/ EMERGENCY SUPPORT CENTRE'],
            'no_of_idp_camps': row['NO. OF IDPS CAMPS'],
            'no_of_persons_in_idp_camps': row['NO. OF PERSONS IN IDP CAMPS'],
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_13932\2377766613.py:22: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

,lga_id,year,type_of_disaster,no_of_persons_supported,no_of_persons_displaced,percentage_population_supported,no_of_emergency_centres,no_of_idp_camps,no_of_persons_in_idp_camps
0,18,2019,FLOOD,1070.0,1070.0,1.0,1.0,5.0,1059.0
1,2,2019,FLOOD,2875.0,2875.0,1.0,1.0,0.0,0.0
2,15,2019,FLOOD,422.0,422.0,0.0,1.0,3.0,422.0
3,6,2019,FLOOD,264.0,264.0,0.0,1.0,6.0,265.0
4,8,2019,FLOOD,912.0,912.0,0.0,1.0,0.0,0.0
5,16,2019,FLOOD,112.0,112.0,0.0,1.0,2.0,100.0
6,19,2019,FLOOD,2995.0,2995.0,1.0,1.0,3.0,1764.0
7,14,2019,FLOOD,11.0,11.0,0.0,1.0,4.0,0.0
8,18,2020,FLOOD,71200.0,71200.0,41.0,0.0,4.0,2365.0
9,2,2020,FLOOD,100775.0,100775.0,52.0,0.0,0.0,0.0
10,15,2020,FLOOD,3065.0,3065.0,2.0,0.0,3.0,0.0
11,6,2020,FLOOD,53105.0,53105.0,0.0,0.0,6.0,8692.0
12,3,2020,FLOOD,1120.0,1120.0,0.0,0.0,0.0,0.0
13,16,2020,FLOOD,10100.0,10100.0,3.0,0.0,2.0,0.0
14,19,2020,FLOOD,131175.0,131175.0,51.0,0.0,3.0,3403.0
15,14,2020,FLOOD,2300.0,2300.0,2.0,0.0,4.0,835.0
16,1,2020,FLOOD,1005.0,1005.0,1.0,0.0,0.0,0.0
17,18,2022,FLOOD,95028.0,104719.0,91.0,1.0,5.0,21725.0
18,2,2022,FLOOD,195782.0,279689.0,78.0,1.0,0.0,0.0
19,15,2022,FLOOD,21494.0,28600.0,75.0,1.0,3.0,1474.0
20,6,2022,FLOOD,8801.0,9203.0,96.0,1.0,6.0,4200.0
21,17,2022,FLOOD,3181.0,4242.0,75.0,0.0,2.0,1060.0

In [5]:
new_df['no_of_persons_supported'] = new_df['no_of_persons_supported'].astype(int)
new_df['no_of_persons_displaced'] = new_df['no_of_persons_displaced'].astype(int)
new_df['percentage_population_supported'] = new_df['percentage_population_supported'].astype(int)
new_df['no_of_emergency_centres'] = new_df['no_of_emergency_centres'].astype(int)
new_df['no_of_idp_camps'] = new_df['no_of_idp_camps'].astype(int)
new_df['no_of_persons_in_idp_camps'] = new_df['no_of_persons_in_idp_camps'].astype(int)
new_df.head()

,lga_id,year,type_of_disaster,no_of_persons_supported,no_of_persons_displaced,percentage_population_supported,no_of_emergency_centres,no_of_idp_camps,no_of_persons_in_idp_camps
0,18,2019,FLOOD,1070,1070,1,1,5,1059
1,2,2019,FLOOD,2875,2875,1,1,0,0
2,15,2019,FLOOD,422,422,0,1,3,422
3,6,2019,FLOOD,264,264,0,1,6,265
4,8,2019,FLOOD,912,912,0,1,0,0

In [6]:
new_df.to_excel("victims_of_natural_disaster.xlsx", index=False)
print("Done!")

Done!