In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("july.xlsx", sheet_name="STATE OF ORIGIN")
lga_df = pd.read_excel("Anambra_LGAs.xlsx", sheet_name="Sheet1")
df.head()

,S/N,LGA,SCHOOL,ABIA,ADAMAWA,AKWA IBOM,BAUCHI,BAYELSA,BENUE,BORNO,...,SOKOTO,TARABA,YOBE,ZAMFARA,FCT,FOREIGN,COUNTRY,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,1,AGUATA,URBAN GIRLS'.SEC.SCH. EKWULOBIA,9.0,0.0,4.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,BENIN,179,NaN,NaN
1,2,AGUATA,GIRLS' .SEC. SCH. IGBOUKWU,24.0,NaN,3.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,237,NaN,NaN
2,3,AGUATA,COMM.SEC. SCH. ISUOFIA,19.0,3.0,3.0,NaN,NaN,12.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,391,391,NaN,NaN
3,4,AGUATA,AGUATA HIGH SCH.AGUATA,3.0,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38,38,NaN,NaN
4,5,AGUATA,GIRLS' HIGH SCHOOL UGA,8.0,NaN,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,124,124,NaN,NaN

In [4]:
new_df = pd.DataFrame(columns=['lga_id', 'school_id', 'school_name', 'school_type', 'lat', 'long'])
count = 0
for index, row in df.iterrows():
    count += 1
    transformed_data = []
    data = {
    'lga_id': lga_df.loc[lga_df['lga_name'] == row['LGA'], 'lga_id'].values[0],
    'school_id': count,
    'school_name': row['SCHOOL'].strip(),
    'school_type': 'Secondary',
    'lat': '',
    'long': '',
    }
    transformed_data.append(data)
    # Append the transformed data to the new DataFrame
    new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

new_df.head()

  lga_id school_id                      school_name school_type lat long
0     13         1  URBAN GIRLS'.SEC.SCH. EKWULOBIA   Secondary
1     13         2       GIRLS' .SEC. SCH. IGBOUKWU   Secondary
2     13         3           COMM.SEC. SCH. ISUOFIA   Secondary
3     13         4           AGUATA HIGH SCH.AGUATA   Secondary
4     13         5           GIRLS' HIGH SCHOOL UGA   Secondary

In [36]:
new_df.to_csv("Schools.csv", index=False)
print("Done!")

Done!