In [2]:
import pandas as pd

In [3]:
timestamp="01-07-2023"
df= pd.read_excel("primary_school.xlsx")
df.head()

,S/N,LGA,SCHOOL_TYPE,SCHOOL,ECCDE1_M,ECCDE1_F,ECCDE2_M,ECCDE2_F,ECCDE3_M,ECCDE3_F,...,PRY5_F,PRY6_M,PRY6_F,PRY_M,PRY_F,PRY_T,TOTAL,TEACHER_M,TEACHER_F,TEACHER_T
0,1,AGUATA,CATHOLIC,CENTRAL SCHOOL ACHINA,10.0,12.0,11.0,12.0,12.0,12.0,...,8,17,17,95,80,175,244,0,6,6
1,2,AGUATA,CATHOLIC,PRIMARY SCHOOL EKE ACHINA,23.0,24.0,11.0,9.0,11.0,10.0,...,10,17,9,93,51,144,232,0,9,9
2,3,AGUATA,CATHOLIC,OBINIKPA SCHOOL ACHINA,3.0,3.0,3.0,2.0,5.0,4.0,...,6,6,5,34,30,64,84,0,2,2
3,4,AGUATA,ANGLICAN,PROGRESSIVE SCHOOL ACHINA,4.0,4.0,5.0,6.0,5.0,2.0,...,4,5,6,44,28,72,98,1,3,4
4,5,AGUATA,CATHOLIC,CENTRAL SCHOOL AGULUEZECHUKWU,34.0,30.0,15.0,18.0,13.0,12.0,...,21,13,10,96,96,192,314,0,7,7

In [4]:
df = df.fillna(0)

In [5]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [6]:
print(df['SCHOOL_TYPE'].unique().tolist())

['CATHOLIC', 'ANGLICAN', 'PUBLIC', 0, 'COMMUNITY', 'CATHOLIC ', ' ', 'ANGLICAN.', 'CATHOLIC.', 'PUBLIC.', ' PUBLIC', 'PUBLICENT.']

In [9]:
new_df = pd.DataFrame(columns=['lga_id', 'school_id', 'school_name', 'school_type', 'category', 'lat', 'long'])

count = 2000
for index, row in df.iterrows():
    count += 1
    transformed_data = []
    data = {
    'lga_id': lga_df.loc[lga_df['lga_name'] == row['LGA'], 'lga_id'].values[0],
    'school_id': count,
    'school_name': row['SCHOOL'].strip(),
    'school_type': 'PUBLIC' if row['SCHOOL_TYPE'] == 0 else 'PUBLIC MISSION' if any(x in row['SCHOOL_TYPE'] for x in ('CATHOLIC', 'ANGLICAN')) else 'PUBLIC' if any(x in row['SCHOOL_TYPE'] for x in ('PUBLIC')) else 'PUBLIC',
    'category': 'Primary',
    'lat': '',
    'long': '',
    }
    transformed_data.append(data)
    # Append the transformed data to the new DataFrame
    new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

In [10]:
new_df.head(30)

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,2001,CENTRAL SCHOOL ACHINA,PUBLIC MISSION,Primary,,
1,13,2002,PRIMARY SCHOOL EKE ACHINA,PUBLIC MISSION,Primary,,
2,13,2003,OBINIKPA SCHOOL ACHINA,PUBLIC MISSION,Primary,,
3,13,2004,PROGRESSIVE SCHOOL ACHINA,PUBLIC MISSION,Primary,,
4,13,2005,CENTRAL SCHOOL AGULUEZECHUKWU,PUBLIC MISSION,Primary,,
5,13,2006,COMMUNITY SCHOOL AGULUEZECHUKWU,PUBLIC MISSION,Primary,,
6,13,2007,PRIMARY SCHOOL AGULUEZECHUKWU,PUBLIC,Primary,,
7,13,2008,OBIOFIA PRIMARY SCHOOL AGULUEZECHUKWU,PUBLIC,Primary,,
8,13,2009,CENTRAL SCHOOL AKPO,PUBLIC MISSION,Primary,,
9,13,2010,EGBUIKE PRIMARY SCHOOL AKPO,PUBLIC,Primary,,
10,13,2011,COMBINED PRIMARY SCHOOL AKPO/ACHINA,PUBLIC MISSION,Primary,,
11,13,2012,UDOKA PRIMARY SCHOOL AKPO/ACHINA,PUBLIC,Primary,,
12,13,2013,CENTRAL SCHOOL AMESI,PUBLIC MISSION,Primary,,
13,13,2014,COMMUNITY SCHOOL AMESI,PUBLIC,Primary,,
14,13,2015,PRIMARY SCHOOL AGBA EKWULOBIA,PUBLIC MISSION,Primary,,
15,13,2016,CENTRAL SCHOOL EKWULOBIA,PUBLIC MISSION,Primary,,
16,13,2017,COMMUNITY SCHOOL EKWULOBIA,PUBLIC MISSION,Primary,,
17,13,2018,EFOSIE PRIMARY SCHOOL EKWULOBIA,PUBLIC MISSION,Primary,,
18,13,2019,PRIMARY SCHOOL EZIAGULU EKWULOBIA,PUBLIC MISSION,Primary,,
19,13,2020,NWANNEBO PRIMARY SCHOOL ULA EKWULOBIA,PUBLIC MISSION,Primary,,
20,13,2021,UMUEZENNAFOR PRIMARY SCHOOL EKWULOBIA,PUBLIC MISSION,Primary,,
21,13,2022,AKPUNOJI PRIMARY SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
22,13,2023,ANULI COMMUNITY PRIMARY SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
23,13,2024,CENTRAL SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
24,13,2025,IGWEBUIKE PRIMARY SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
25,13,2026,NWAHIA PRIMARY SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
26,13,2027,OGBUGBOGU COMMUNITY PRIMARY SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
27,13,2028,TOWN SCHOOL EZINIFITE,PUBLIC MISSION,Primary,,
28,13,2029,AMAKPU PRIMARY SCHOOL NGO IGBOUKWU,PUBLIC,Primary,,
29,13,2030,CENTRAL SCHOOL IGBOUKWU,PUBLIC MISSION,Primary,,

In [11]:
new_df.to_csv("Primary_Schools.csv", index=False)
print("Done Printing!")

Done Printing!