In [1]:
import pandas as pd

In [2]:
timestamp="01-01-2023"
df= pd.read_excel("primary_school.xlsx")
df.head()

,S/N,LGA,SCHOOL_TYPE,SCHOOL,ECCDE1_M,ECCDE1_F,ECCDE2_M,ECCDE2_F,ECCDE3_M,ECCDE3_F,...,PRY5_F,PRY6_M,PRY6_F,PRY_M,PRY_F,PRY_T,TOTAL,TEACHER_M,TEACHER_F,TEACHER_T
0,1,AGUATA,CATHOLIC,CENTRAL SCHOOL ACHINA,10.0,12.0,11.0,12.0,12.0,12.0,...,8,17,17,95,80,175,244,0,6,6
1,2,AGUATA,CATHOLIC,PRIMARY SCHOOL EKE ACHINA,23.0,24.0,11.0,9.0,11.0,10.0,...,10,17,9,93,51,144,232,0,9,9
2,3,AGUATA,CATHOLIC,OBINIKPA SCHOOL ACHINA,3.0,3.0,3.0,2.0,5.0,4.0,...,6,6,5,34,30,64,84,0,2,2
3,4,AGUATA,ANGLICAN,PROGRESSIVE SCHOOL ACHINA,4.0,4.0,5.0,6.0,5.0,2.0,...,4,5,6,44,28,72,98,1,3,4
4,5,AGUATA,CATHOLIC,CENTRAL SCHOOL AGULUEZECHUKWU,34.0,30.0,15.0,18.0,13.0,12.0,...,21,13,10,96,96,192,314,0,7,7

In [ ]:
df = df.fillna(0)

In [40]:
school_df = pd.read_csv("combine_schools.csv")
school_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [8]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx", sheet_name="Sheet1")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [ ]:
# Create a new DataFrame
new_df = pd.DataFrame(columns=['school_id', 'class', 'timestamp', 'gender', 'population'])
for index, row in df.iterrows():
    # fetch the lga
    lga_id = lga_df.loc[lga_df['lga_name'] == row['LGA'], 'lga_id'].values[0]
    school_ids = school_df.loc[(school_df['school_name'] == row['SCHOOL'].strip()) & (lga_id == school_df['lga_id']) & (school_df['category'] == 'Primary'), 'school_id'].values
    if(len(school_ids) == 0):
        print(row['SCHOOL'].strip(), "is not in the school_df")
    elif(len(school_ids) > 1):
        print(index, school_df.loc[index, 'school_name'], school_ids)
        
    else: 
        transformed_data = [{
            'school_id': school_ids[0],
            'class': 'ECCDE1',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['ECCDE1_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'ECCDE1',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['ECCDE1_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'ECCDE2',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['ECCDE2_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'ECCDE2',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['ECCDE2_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'ECCDE3',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['ECCDE3_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'ECCDE3',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['ECCDE3_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY1',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['PRY1_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY1',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['PRY1_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY2',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['PRY2_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY2',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['PRY2_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY3',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['PRY3_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY3',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['PRY3_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY4',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['PRY4_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY4',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['PRY4_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY5',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['PRY5_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY5',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['PRY5_F'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY6',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['PRY6_M'],
        },
        {
            'school_id': school_ids[0],
            'class': 'PRY6',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['PRY6_F'],
        }]
        # Append the transformed data to the new DataFrame
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_10220\259930453.py:138: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

    is not in the school_df

In [13]:
new_df.head(50)

   school_id   class   timestamp  gender  population
0       2001  ECCDE1  01-01-2023    Male        10.0
1       2001  ECCDE1  01-01-2023  Female        12.0
2       2001  ECCDE2  01-01-2023    Male        11.0
3       2001  ECCDE2  01-01-2023  Female        12.0
4       2001  ECCDE3  01-01-2023    Male        12.0
5       2001  ECCDE3  01-01-2023  Female        12.0
6       2001    PRY1  01-01-2023    Male        12.0
7       2001    PRY1  01-01-2023  Female        14.0
8       2001    PRY2  01-01-2023    Male         9.0
9       2001    PRY2  01-01-2023  Female        18.0
10      2001    PRY3  01-01-2023    Male        15.0
11      2001    PRY3  01-01-2023  Female        12.0
12      2001    PRY4  01-01-2023    Male        21.0
13      2001    PRY4  01-01-2023  Female        11.0
14      2001    PRY5  01-01-2023    Male        21.0
15      2001    PRY5  01-01-2023  Female         8.0
16      2001    PRY6  01-01-2023    Male        17.0
17      2001    PRY6  01-01-2023  Female        17.0
18      2002  ECCDE1  01-01-2023    Male        23.0
19      2002  ECCDE1  01-01-2023  Female        24.0
20      2002  ECCDE2  01-01-2023    Male        11.0
21      2002  ECCDE2  01-01-2023  Female         9.0
22      2002  ECCDE3  01-01-2023    Male        11.0
23      2002  ECCDE3  01-01-2023  Female        10.0
24      2002    PRY1  01-01-2023    Male        16.0
25      2002    PRY1  01-01-2023  Female        10.0
26      2002    PRY2  01-01-2023    Male        19.0
27      2002    PRY2  01-01-2023  Female         6.0
28      2002    PRY3  01-01-2023    Male        17.0
29      2002    PRY3  01-01-2023  Female         8.0
30      2002    PRY4  01-01-2023    Male        14.0
31      2002    PRY4  01-01-2023  Female         8.0
32      2002    PRY5  01-01-2023    Male        10.0
33      2002    PRY5  01-01-2023  Female        10.0
34      2002    PRY6  01-01-2023    Male        17.0
35      2002    PRY6  01-01-2023  Female         9.0
36      2003  ECCDE1  01-01-2023    Male         3.0
37      2003  ECCDE1  01-01-2023  Female         3.0
38      2003  ECCDE2  01-01-2023    Male         3.0
39      2003  ECCDE2  01-01-2023  Female         2.0
40      2003  ECCDE3  01-01-2023    Male         5.0
41      2003  ECCDE3  01-01-2023  Female         4.0
42      2003    PRY1  01-01-2023    Male         4.0
43      2003    PRY1  01-01-2023  Female         4.0
44      2003    PRY2  01-01-2023    Male         5.0
45      2003    PRY2  01-01-2023  Female         4.0
46      2003    PRY3  01-01-2023    Male         5.0
47      2003    PRY3  01-01-2023  Female         5.0
48      2003    PRY4  01-01-2023    Male         7.0
49      2003    PRY4  01-01-2023  Female         6.0

In [14]:
print(new_df['population'].unique().tolist())
# for x in new_df['population']:
#     print(x, end=' ')
#     if not isinstance(x, (int, float)): 
#         print(x, "working!")

print(new_df.loc[new_df['population'].isna(), "school_id"].tolist())

[10.0, 12.0, 11.0, 14.0, 9.0, 18.0, 15.0, 21.0, 8.0, 17.0, 23.0, 24.0, 16.0, 19.0, 6.0, 3.0, 2.0, 5.0, 4.0, 7.0, 13.0, 34.0, 30.0, 20.0, 22.0, 1.0, 0.0, 27.0, 29.0, 26.0, 48.0, 36.0, 28.0, 50.0, 40.0, 33.0, 60.0, 42.0, 25.0, 37.0, 32.0, 31.0, 44.0, 43.0, 38.0, 41.0, 68.0, 69.0, 46.0, 39.0, 35.0, 56.0, 72.0, 52.0, 59.0, 71.0, 63.0, 57.0, 64.0, 45.0, 49.0, 54.0, 81.0, 74.0, 91.0, 78.0, 66.0, 86.0, 61.0, 58.0, 53.0, 47.0, 51.0, 55.0, 92.0, 108.0, 76.0, 75.0, 67.0, 62.0, 79.0, 90.0, 85.0, 132.0, 106.0, 73.0, 110.0, 107.0, 95.0, 116.0, 65.0, 83.0, 70.0, 80.0, 88.0, 77.0, 89.0, 93.0, 112.0, 103.0, 101.0, 99.0, 137.0, 82.0, 213.0, 195.0, 210.0, 185.0, 225.0, 204.0, 182.0, 109.0, 104.0, 87.0, 118.0]
[]

In [15]:
new_df.replace(['-', '_', 'NIL', 'O', 'o'], 0, inplace=True)
new_df['population'] = new_df['population'].astype(int)
new_df.head()

   school_id   class   timestamp  gender  population
0       2001  ECCDE1  01-01-2023    Male          10
1       2001  ECCDE1  01-01-2023  Female          12
2       2001  ECCDE2  01-01-2023    Male          11
3       2001  ECCDE2  01-01-2023  Female          12
4       2001  ECCDE3  01-01-2023    Male          12

In [16]:
new_df.to_csv("Primary_Schools_Summaries.csv", index=False)
print("Done!")

Done!