In [79]:
import pandas as pd

In [80]:
month = "July"
timestamp = "07-01-2024"
df = pd.read_excel("july.xlsx", sheet_name="SCHOOLS SUMMARIES")
school_df = pd.read_csv("combine_schools.csv")
school_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [81]:
# Reset index for easier manipulation
# df.reset_index(drop=True, inplace=True)
df = df.fillna(0)
df.head(100)

,S/N,LGA,SCHOOL,JSS1_M,JSS1_F,JSS1_ST,JSS2_M,JSS2_F,JSS2_ST,JSS3_M,...,SSS2_F,SSS2_ST,SSS3_M,SSS3_F,SSS3_ST,TOTAL_M,TOTAL_F,TOTAL_ST,TEACHER_M,TEACHER_F
0,1.0,AGUATA,URBAN GIRLS'.SEC.SCH. EKWULOBIA,0.0,195.0,3.0,0.0,146.0,3.0,0.0,...,89.0,3.0,0.0,87.0,3.0,0,766,18,3.0,38.0
1,2.0,AGUATA,GIRLS' .SEC. SCH. IGBOUKWU,0.0,106.0,3.0,0.0,99.0,3.0,0.0,...,133.0,3.0,0.0,122.0,3.0,0,724,19,8.0,26.0
2,3.0,AGUATA,COMM.SEC. SCH. ISUOFIA,182.0,135.0,6.0,146.0,123.0,5.0,140.0,...,113.0,4.0,100.0,84.0,4.0,807,665,29,5.0,20.0
3,4.0,AGUATA,AGUATA HIGH SCH.AGUATA,37.0,0.0,1.0,30.0,0.0,1.0,41.0,...,0.0,1.0,42.0,0.0,1.0,204,0,6,4.0,20.0
4,5.0,AGUATA,GIRLS' HIGH SCHOOL UGA,0.0,77.0,2.0,0.0,58.0,0.0,0.0,...,63.0,0.0,0.0,45.0,2.0,0,362,8,4.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,18.0,AWKA SOUTH,COMM. SEC. SCH. ISIAGU,13.0,10.0,1.0,2.0,2.0,1.0,0.0,...,2.0,1.0,0.0,0.0,1.0,23,23,6,0.0,13.0
96,19.0,AWKA SOUTH,"STATE MODEL JUNIOR SEC. SCH., IYIAGU II AWKA",44.0,97.0,4.0,53.0,69.0,3.0,54.0,...,79.0,3.0,36.0,45.0,3.0,275,483,20,3.0,28.0
97,1.0,DUNUKOFIA,ST. MARY'S HIGH SCH. IFITEDUNU,230.0,0.0,6.0,232.0,0.0,5.0,220.0,...,0.0,4.0,109.0,0.0,4.0,1080,0,27,4.0,29.0
98,2.0,DUNUKOFIA,WALTER EZE MEMO SEC. SCH. UKPO,54.0,47.0,2.0,59.0,48.0,2.0,61.0,...,60.0,2.0,46.0,57.0,2.0,314,337,12,2.0,20.0
99,3.0,DUNUKOFIA,COMM SEC. SCH. UMUNNACHI,67.0,73.0,4.0,70.0,87.0,4.0,77.0,...,64.0,3.0,54.0,61.0,3.0,356,444,21,4.0,24.0

In [82]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx", sheet_name="Sheet1")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [ ]:

# Create a new DataFrame
new_df = pd.DataFrame(columns=['school_id', 'class', 'timestamp', 'gender', 'population'])
for index, row in df.iterrows():
    lga_id = lga_df.loc[lga_df['lga_name'] == row['LGA'].strip(), 'lga_id'].values[0]
    school_ids = school_df.loc[(school_df['school_name'] == row['SCHOOL'].strip()) & (lga_id == school_df['lga_id']) & (school_df['category'] == 'Secondary'), 'school_id'].values
    if(len(school_ids) == 0):
        print(row['SCHOOL'].strip(), "is not in the school_df")
    elif(len(school_ids) > 1):
        print(index, school_df.loc[index, 'school_name'], school_ids)
        # duplicates = df['SCHOOL'][df['SCHOOL'].duplicated(keep=False)].tolist()
        # print(duplicates)
    else: 
        transformed_data = [{
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'JSS1',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['JSS1_M'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'JSS2',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['JSS2_M'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'JSS3',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['JSS3_M'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'SSS1',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['SSS1_M'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'SSS2',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['SSS2_M'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'SSS3',
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['SSS3_M'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'JSS1',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['JSS1_F'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'JSS2',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['JSS2_F'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'JSS3',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['JSS3_F'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'SSS1',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['SSS1_F'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'SSS2',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['SSS2_F'],
        },
        {
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'class': 'SSS3',
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['SSS3_F'],
        }]
        # Append the transformed data to the new DataFrame
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

fg = new_df.loc[500:550]
fg.head(20)

C:\Users\USER\AppData\Local\Temp\ipykernel_4560\3813224709.py:98: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

    school_id class   timestamp  gender  population
500       949  JSS3  07-01-2024  Female        57.0
501       949  SSS1  07-01-2024  Female        51.0
502       949  SSS2  07-01-2024  Female        51.0
503       949  SSS3  07-01-2024  Female        52.0
504       956  JSS1  07-01-2024    Male        12.0
505       956  JSS2  07-01-2024    Male        17.0
506       956  JSS3  07-01-2024    Male        13.0
507       956  SSS1  07-01-2024    Male        18.0
508       956  SSS2  07-01-2024    Male        14.0
509       956  SSS3  07-01-2024    Male        31.0
510       956  JSS1  07-01-2024  Female        20.0
511       956  JSS2  07-01-2024  Female        14.0
512       956  JSS3  07-01-2024  Female        17.0
513       956  SSS1  07-01-2024  Female        18.0
514       956  SSS2  07-01-2024  Female        19.0
515       956  SSS3  07-01-2024  Female        30.0
516       960  JSS1  07-01-2024    Male        20.0
517       960  JSS2  07-01-2024    Male        18.0
518       960  JSS3  07-01-2024    Male        24.0
519       960  SSS1  07-01-2024    Male        14.0

In [84]:
new_df.replace(['-', '_', 'NIL', 'O'], 0, inplace=True)
new_df['population'] = new_df['population'].astype(int)
new_df.head()

   school_id class   timestamp gender  population
0         21  JSS1  07-01-2024   Male           0
1         21  JSS2  07-01-2024   Male           0
2         21  JSS3  07-01-2024   Male           0
3         21  SSS1  07-01-2024   Male           0
4         21  SSS2  07-01-2024   Male           0

In [85]:
new_df.to_csv(f"{month}_school_summary.csv", index=False)
print("Done!")

Done!