In [11]:
import pandas as pd

In [12]:
df= pd.read_excel("secondary_schools.xlsx", sheet_name="STATE SECONDARY SHOOLS-Grid vie")
df.tail()

,S/N,NAME OF SCHOOL,ADDRESS/LOCATION,ZONE,LGA,PROPRIETOR,PHONE NUMBER,DATE OF APPROVAL,REMARKS,JSS MALE,...,JSS TOTAL,SSS MALE,SSS FEMALE,SSS TOTAL,MALE TOTAL,FEMALE TOTAL,TOTAL STUDENTS,NUMBER OF TEACHERS,SUPPORT STAFF,TEACHER/ STUDENT RATIO
1031,1031.0,STAR LIGHT SECONDARY SCHOOL,OGBUNIKE,OGIDI ZONE,OYI,NaN,8.037105e+09,NaN,PRIVATE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032,1032.0,TORIA SECONDARY SCHOOL,NTEJE,OGIDI ZONE,OYI,NaN,NaN,NaN,PRIVATE,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1033,1033.0,"COMMUNITY SECONADRY SCHOOL, EZIAGU",EZIAGU,AGUATA ZONE,ORUMBA SOUTH,NaN,NaN,NaN,GOVERNMENT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034,1034.0,"COMMUNITY HIGH SCHOOL, UGBENU",UGBENU,AWKA ZONE,AWKA NORTH,NaN,NaN,NaN,GOVERNMENT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1035,1035.0,"UNITY COLLEGE UMUJI, EBENEBE",EBENEBE,AWKA ZONE,AWKA NORTH,NaN,NaN,NaN,GOVERNMENT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [14]:
new_df = pd.DataFrame(columns=['lga_id', 'school_id', 'school_name', 'school_type', 'category', 'lat', 'long'])

count = 0
for index, row in df.iterrows():
    count += 1
    transformed_data = []
    data = {
    'lga_id': lga_df.loc[lga_df['lga_name'] == row['LGA'], 'lga_id'].values[0],
    'school_id': count,
    'school_name': row['NAME OF SCHOOL'].strip(),
    'school_type': 'PUBLIC' if 'GOVERNMENT' in row['REMARKS'] else 'PRIVATE' if 'PRIVATE' in row['REMARKS'] else 'UNKNOWN',
    'category': "Secondary",
    'lat': '',
    'long': '',
    }
    transformed_data.append(data)
    # Append the transformed data to the new DataFrame
    new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

new_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,,
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,,
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,,
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,,
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,,

In [15]:
print(new_df['school_type'].unique().tolist())

['PUBLIC', 'PRIVATE']

In [16]:
new_df.to_csv("Secondary_Schools.csv", index=False)
print("Done Printing!")

Done Printing!