In [25]:
import pandas as pd

In [26]:
timestamp="01-07-2023"
df= pd.read_excel("secondary_schools.xlsx", sheet_name="STATE SECONDARY SHOOLS-Grid vie")
df.head()

,S/N,NAME OF SCHOOL,ADDRESS/LOCATION,ZONE,LGA,PROPRIETOR,PHONE NUMBER,DATE OF APPROVAL,REMARKS,JSS MALE,...,JSS TOTAL,SSS MALE,SSS FEMALE,SSS TOTAL,MALE TOTAL,FEMALE TOTAL,TOTAL STUDENTS,NUMBER OF TEACHERS,SUPPORT STAFF,TEACHER/ STUDENT RATIO
0,1.0,AGUATA HIGH SCH.AGUATA,NaN,AGUATA ZONE,AGUATA,NaN,NaN,NaN,GOVERNMENT,87.0,...,87.0,66.0,0.0,66.0,153.0,0.0,153.0,16.0,0.0,9.562500
1,2.0,CHRIST THE REDEEMER COLLEGE AMESI,NaN,AGUATA ZONE,AGUATA,NaN,NaN,NaN,GOVERNMENT,130.0,...,270.0,50.0,76.0,126.0,180.0,216.0,396.0,16.0,0.0,24.750000
2,3.0,COMM SEC. SCH. (BSS) EZINIFITE,NaN,AGUATA ZONE,AGUATA,NaN,NaN,NaN,GOVERNMENT,27.0,...,63.0,20.0,21.0,41.0,47.0,57.0,104.0,9.0,0.0,11.555556
3,4.0,COMM SEC. SCH. (BSS) IGBOUKWU,NaN,AGUATA ZONE,AGUATA,NaN,NaN,NaN,GOVERNMENT,95.0,...,165.0,36.0,54.0,90.0,131.0,124.0,255.0,12.0,1.0,21.250000
4,5.0,COMM SEC. SCH. AGULUEZECHUKWU,NaN,AGUATA ZONE,AGUATA,NaN,NaN,NaN,GOVERNMENT,27.0,...,102.0,26.0,50.0,76.0,53.0,125.0,178.0,9.0,2.0,19.777778

In [27]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [28]:
june_df = pd.read_excel("june.xlsx", sheet_name="SCHOOLS SUMMARIES")
june_df.head()

,S/N,LGA,SCHOOL,JSS1_M,JSS1_F,JSS1_ST,JSS2_M,JSS2_F,JSS2_ST,JSS3_M,...,SSS2_F,SSS2_ST,SSS3_M,SSS3_F,SSS3_ST,TOTAL_M,TOTAL_F,TOTAL_ST,TEACHER_M,TEACHER_F
0,1.0,AGUATA,URBAN GIRLS'.SEC.SCH. EKWULOBIA,0.0,195.0,3.0,0.0,146.0,3.0,0.0,...,89.0,3.0,0.0,87.0,3.0,0,766,18,3.0,38.0
1,2.0,AGUATA,GIRLS' .SEC. SCH. IGBOUKWU,NaN,106.0,3.0,NaN,99.0,3.0,NaN,...,133.0,3.0,NaN,122.0,3.0,0,724,19,8.0,26.0
2,3.0,AGUATA,COMM.SEC. SCH. ISUOFIA,182.0,135.0,6.0,146.0,123.0,5.0,140.0,...,113.0,4.0,100.0,84.0,4.0,807,665,29,5.0,20.0
3,4.0,AGUATA,AGUATA HIGH SCH.AGUATA,37.0,0.0,1.0,30.0,0.0,1.0,41.0,...,0.0,1.0,42.0,0.0,1.0,204,0,6,4.0,20.0
4,5.0,AGUATA,GIRLS' HIGH SCHOOL UGA,0.0,77.0,2.0,0.0,58.0,NaN,0.0,...,63.0,NaN,0.0,45.0,2.0,0,362,8,4.0,14.0

In [29]:
schools = june_df["SCHOOL"]
__schools = df["NAME OF SCHOOL"]
s = []
for index, row in df.iterrows():
    if "GOVERNMENT" in row["REMARKS"]:
        if row["NAME OF SCHOOL"] not in june_df["SCHOOL"].tolist():
            print(row["NAME OF SCHOOL"])
            s.append(df.loc[df["NAME OF SCHOOL"] == row["NAME OF SCHOOL"], "S/N"].values[0])


print(len(s))
s

0

[]

In [30]:
k = [x for x in june_df['SCHOOL'].tolist() if x not in df['NAME OF SCHOOL'].tolist()]
k

[]

In [31]:
school_list = df['NAME OF SCHOOL'].tolist()

for index, row in june_df.iterrows():
    if row['SCHOOL'] not in school_list: print(index, row['LGA'], row['SCHOOL'])