In [85]:
import pandas as pd

In [86]:
month = "July"
timestamp = "07-01-2024"
df = pd.read_excel("july.xlsx", sheet_name="STATE OF ORIGIN")
school_df = pd.read_csv("combine_schools.csv")
df.head()

,S/N,LGA,SCHOOL,ABIA,ADAMAWA,AKWA IBOM,BAUCHI,BAYELSA,BENUE,BORNO,...,SOKOTO,TARABA,YOBE,ZAMFARA,FCT,FOREIGN,COUNTRY,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,1,AGUATA,URBAN GIRLS'.SEC.SCH. EKWULOBIA,9.0,0.0,4.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,BENIN,179,NaN,NaN
1,2,AGUATA,GIRLS' .SEC. SCH. IGBOUKWU,24.0,NaN,3.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,237,NaN,NaN
2,3,AGUATA,COMM.SEC. SCH. ISUOFIA,19.0,3.0,3.0,NaN,NaN,12.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,391,391,NaN,NaN
3,4,AGUATA,AGUATA HIGH SCH.AGUATA,3.0,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38,38,NaN,NaN
4,5,AGUATA,GIRLS' HIGH SCHOOL UGA,8.0,NaN,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,124,124,NaN,NaN

In [87]:
df = df.fillna(0)
df.head(100)

,S/N,LGA,SCHOOL,ABIA,ADAMAWA,AKWA IBOM,BAUCHI,BAYELSA,BENUE,BORNO,...,SOKOTO,TARABA,YOBE,ZAMFARA,FCT,FOREIGN,COUNTRY,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,1,AGUATA,URBAN GIRLS'.SEC.SCH. EKWULOBIA,9.0,0.0,4.0,0.0,1.0,4.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,BENIN,179,0,0.0
1,2,AGUATA,GIRLS' .SEC. SCH. IGBOUKWU,24.0,0.0,3.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,237,0,0.0
2,3,AGUATA,COMM.SEC. SCH. ISUOFIA,19.0,3.0,3.0,0.0,0.0,12.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,391,391,0,0.0
3,4,AGUATA,AGUATA HIGH SCH.AGUATA,3.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,38,38,0,0.0
4,5,AGUATA,GIRLS' HIGH SCHOOL UGA,8.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,124,124,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,18,AWKA SOUTH,COMM. SEC. SCH. ISIAGU,2.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,39,39,0,0.0
96,19,AWKA SOUTH,"STATE MODEL JUNIOR SEC. SCH., IYIAGU II AWKA",32.0,6.0,14.0,0.0,0.0,6.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,GHANA,401,0,0.0
97,1,DUNUKOFIA,ST. MARY'S HIGH SCH. IFITEDUNU,10.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,173,173,0,0.0
98,2,DUNUKOFIA,WALTER EZE MEMO SEC. SCH. UKPO,7.0,3.0,5.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,163,163,0,0.0
99,3,DUNUKOFIA,COMM SEC. SCH. UMUNNACHI,2.0,0.0,1.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,154,154,0,0.0

In [88]:
lga_df=pd.read_excel("Anambra_LGAs.xlsx")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [89]:

# Create a new DataFrame
new_df = pd.DataFrame(columns=['school_id', 'state', 'timestamp', 'population'])
for index, row in df.iterrows():
    lga_id = lga_df.loc[lga_df['lga_name'] == row['LGA'].strip(), 'lga_id'].values[0]
    school_ids = school_df.loc[(school_df['school_name'] == row['SCHOOL'].strip()) & (lga_id == school_df['lga_id']) & (school_df['category'] == 'Secondary'), 'school_id'].values
    if(len(school_ids) == 0):
        print(row['SCHOOL'].strip(), "is not in the school_df")
    elif(len(school_ids) > 1):
        print(index, school_df.loc[index, 'school_name'], school_ids)
    else:
        transformed_data = []
        for column in df.columns[3:-4]:
            data = {
            'school_id': school_ids[0],
            'state': column,
            'timestamp': timestamp,
            'population': row[column],
            }
            transformed_data.append(data)
        # Append the transformed data to the new DataFrame
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(200)

C:\Users\USER\AppData\Local\Temp\ipykernel_15456\4110770456.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

    school_id      state   timestamp  population
0          21       ABIA  07-01-2024         9.0
1          21    ADAMAWA  07-01-2024         0.0
2          21  AKWA IBOM  07-01-2024         4.0
3          21     BAUCHI  07-01-2024         0.0
4          21    BAYELSA  07-01-2024         1.0
..        ...        ...         ...         ...
195        19        EDO  07-01-2024         2.0
196        19      EKITI  07-01-2024         0.0
197        19      ENUGU  07-01-2024        17.0
198        19      GOMBE  07-01-2024         0.0
199        19        IMO  07-01-2024        20.0

[200 rows x 4 columns]

In [90]:
new_df.replace(['-', '_', 'NIL', 'O', 'Nil', ' '], 0, inplace=True)
new_df['population'] = new_df['population'].astype(int)

In [91]:
new_df.to_csv(f"{month}_state_of_origin.csv", index=False)
print("Done")

Done