In [63]:
import pandas as pd

In [64]:
month = "July"
timestamp = "07-01-2024"
df = pd.read_excel("july.xlsx", sheet_name="SCHOOLS SUMMARIES")
school_df = pd.read_csv("combine_schools.csv")
df.head()

,S/N,LGA,SCHOOL,JSS1_M,JSS1_F,JSS1_ST,JSS2_M,JSS2_F,JSS2_ST,JSS3_M,...,SSS2_F,SSS2_ST,SSS3_M,SSS3_F,SSS3_ST,TOTAL_M,TOTAL_F,TOTAL_ST,TEACHER_M,TEACHER_F
0,1.0,AGUATA,URBAN GIRLS'.SEC.SCH. EKWULOBIA,0.0,195.0,3.0,0.0,146.0,3.0,0.0,...,89.0,3.0,0.0,87.0,3.0,0,766,18,3.0,38.0
1,2.0,AGUATA,GIRLS' .SEC. SCH. IGBOUKWU,NaN,106.0,3.0,NaN,99.0,3.0,NaN,...,133.0,3.0,NaN,122.0,3.0,0,724,19,8.0,26.0
2,3.0,AGUATA,COMM.SEC. SCH. ISUOFIA,182.0,135.0,6.0,146.0,123.0,5.0,140.0,...,113.0,4.0,100.0,84.0,4.0,807,665,29,5.0,20.0
3,4.0,AGUATA,AGUATA HIGH SCH.AGUATA,37.0,0.0,1.0,30.0,0.0,1.0,41.0,...,0.0,1.0,42.0,0.0,1.0,204,0,6,4.0,20.0
4,5.0,AGUATA,GIRLS' HIGH SCHOOL UGA,0.0,77.0,2.0,0.0,58.0,NaN,0.0,...,63.0,NaN,0.0,45.0,2.0,0,362,8,4.0,14.0

In [65]:
lga_df = pd.read_excel("Anambra_LGAs.xlsx", sheet_name="Sheet1")
lga_df.head()

   lga_id       lga_name     zone
0       1  ONITSHA SOUTH  ONITSHA
1       2   ANAMBRA WEST  OTUOCHA
2       3  IDEMILI SOUTH    OGIDI
3       4    NNEWI SOUTH    NNEWI
4       5            OYI    OGIDI

In [ ]:
df = df.fillna(0)

# Create a new DataFrame
new_df = pd.DataFrame(columns=['school_id', 'timestamp', 'gender', 'population'])
for index, row in df.iterrows():
    lga_id = lga_df.loc[lga_df['lga_name'] == row['LGA'].strip(), 'lga_id'].values[0]
    school_ids = school_df.loc[(school_df['school_name'] == row['SCHOOL'].strip()) & (lga_id == school_df['lga_id']) & (school_df['category'] == 'Secondary'), 'school_id'].values
    if(len(school_ids) == 0):
        print(row['SCHOOL'].strip(), "is not in the school_df")
    elif(len(school_ids) > 1):
        print(index, school_df.loc[index, 'school_name'], school_ids)
        # duplicates = df['SCHOOL'][df['SCHOOL'].duplicated(keep=False)].tolist()
        # print(duplicates)
    else: 
        transformed_data = [{
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'timestamp': timestamp,
            'gender': 'Male',
            'population': row['TEACHER_M'],
        },{
            'school_id': school_df.loc[school_df['school_name'] == row['SCHOOL'].strip(), 'school_id'].values[0],
            'timestamp': timestamp,
            'gender': 'Female',
            'population': row['TEACHER_F'],
        }]
        # Append the transformed data to the new DataFrame
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(200)

C:\Users\USER\AppData\Local\Temp\ipykernel_5696\166106838.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

    school_id   timestamp  gender  population
0          21  07-01-2024    Male         3.0
1          21  07-01-2024  Female        38.0
2          14  07-01-2024    Male         8.0
3          14  07-01-2024  Female        26.0
4          12  07-01-2024    Male         5.0
..        ...         ...     ...         ...
195       276  07-01-2024  Female        29.0
196       277  07-01-2024    Male         2.0
197       277  07-01-2024  Female        20.0
198       270  07-01-2024    Male         4.0
199       270  07-01-2024  Female        24.0

[200 rows x 4 columns]

In [67]:
new_df.replace(['-', '_', 'NIL', 'O', 'Nil'], 0, inplace=True)
new_df['population'] = new_df['population'].astype(int)
new_df.head()

   school_id   timestamp  gender  population
0         21  07-01-2024    Male           3
1         21  07-01-2024  Female          38
2         14  07-01-2024    Male           8
3         14  07-01-2024  Female          26
4         12  07-01-2024    Male           5

In [68]:
new_df.to_csv(f"{month}_teacher_summary.csv", index=False)
print("Use LeetCode Design!")

Use LeetCode Design!