In [1]:
import pandas as pd

In [7]:
years = [2025]
dfs = []
for index, sheet in enumerate(years):
    dfs.append(pd.read_excel("anthrax_vaccination.xlsx"))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head(20)

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40
5,6,AYAMELUM,OTUOCHA,196,40,35
6,7,ORUMBA NORTH,AGUATA,44,15,47
7,8,IDEMILI NORTH,OGIDI,66,34,38
8,9,ANAOCHA,AWKA,109,36,50
9,10,NNEWI NORTH,NNEWI,128,34,42
10,11,NJIKOKA,AWKA,81,18,42
11,12,DUNUKOFIA,AWKA,72,28,40
12,13,AGUATA,AGUATA,534,0,18
13,14,ONITSHA NORTH,ONITSHA,305,11,39
14,15,AWKA NORTH,AWKA,356,20,48
15,16,IHIALA,NNEWI,310,22,40
16,17,EKWUSIGO,NNEWI,104,25,44
17,18,ANAMBRA EAST,OTUOCHA,418,0,12
18,19,OGBARU,ONITSHA,504,5,30
19,20,AWKA SOUTH,AWKA,175,0,61

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

   S/N            LGA  Cattle  Sheep  Goat
0    1  Idemili South     502    990  1103
1    2      Dunukofia     581    627  1057
2    3         Aguata     686   1099  1889
3    4         Ihiala     107    554  1145
4    5       Ekwusigo     118    576  1059

In [9]:
columns = ['lga_id', 'year', 'livestock', 'num_of_vaccination']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"].upper().strip(), "lga_id"].values) == 0):
            print(row["LGA"].upper())
        # print(row)
        else:
            lga_id = lga_df.loc[lga_df['lga_name'] == row["LGA"].upper().strip(), "lga_id"].values[0]
            for col in df.columns[2:]:
                transformed_data = [
                    {
                        'lga_id': lga_id,
                        'year': year,
                        'livestock': col,
                        'num_of_vaccination': row[col]
                    }
                ]
                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year livestock num_of_vaccination
0       3  2025    Cattle                502
1       3  2025     Sheep                990
2       3  2025      Goat               1103
3      12  2025    Cattle                581
4      12  2025     Sheep                627
5      12  2025      Goat               1057
6      13  2025    Cattle                686
7      13  2025     Sheep               1099
8      13  2025      Goat               1889
9      16  2025    Cattle                107
10     16  2025     Sheep                554
11     16  2025      Goat               1145
12     17  2025    Cattle                118
13     17  2025     Sheep                576
14     17  2025      Goat               1059
15     18  2025    Cattle                553
16     18  2025     Sheep                257
17     18  2025      Goat                793
18      7  2025    Cattle                457
19      7  2025     Sheep                681
20      7  2025      Goat               1052
21     19  2025    Cattle               2260

In [10]:
new_df['num_of_vaccination']=new_df['num_of_vaccination'].astype(int)
new_df.head()

  lga_id  year livestock  num_of_vaccination
0      3  2025    Cattle                 502
1      3  2025     Sheep                 990
2      3  2025      Goat                1103
3     12  2025    Cattle                 581
4     12  2025     Sheep                 627

In [11]:
new_df.to_excel("transposedb/anthrax_vaccination_transposed.xlsx", index=False)
print("Done!")

Done!