In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021]
sheets = ["Table 223", "Table 224", "Table 225"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,NUMBER OF TRANSFORMERS DISTRIBUTED,NUMBER OF GENERATORS DISTRIBUTED,NUMBER OF STREET LIGHT INSTALLED,NUMBER OF SOLAR PANELS INSTALLED,LENGTH OF HIGH TENSION LINES (KM),LENGTH OF LOW TENSION LINES (KM),DISTANCE COVERED BY STREET LIGHTS (KM)
0,AGUATA,1,0.0,3,0.0,0.0,0.0,0.0
1,ANAMBRA EAST,1,0.0,2,0.0,0.0,0.0,0.0
2,ANAMBRA WEST,0,0.0,0,0.0,0.0,0.0,0.0
3,ANAOCHA,5,0.0,1,0.0,0.0,0.0,0.0
4,AWKA NORTH,3,0.0,0,0.0,0.0,0.0,0.0

In [4]:
columns = ['lga_id', 'electricity_project', 'year', 'count']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        for col in df.columns[1:]:

            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'electricity_project': col,
                'year': year,
                'count': row[col],
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id                     electricity_project  year count
0      13      NUMBER OF TRANSFORMERS DISTRIBUTED  2019     1
1      13        NUMBER OF GENERATORS DISTRIBUTED  2019   0.0
2      13        NUMBER OF STREET LIGHT INSTALLED  2019     0
3      13        NUMBER OF SOLAR PANELS INSTALLED  2019     0
4      13       LENGTH OF HIGH TENSION LINES (KM)  2019   0.0
5      13        LENGTH OF LOW TENSION LINES (KM)  2019   0.0
6      13  DISTANCE COVERED BY STREET LIGHTS (KM)  2019   0.0
7      18      NUMBER OF TRANSFORMERS DISTRIBUTED  2019     2
8      18        NUMBER OF GENERATORS DISTRIBUTED  2019   0.0
9      18        NUMBER OF STREET LIGHT INSTALLED  2019     3
10     18        NUMBER OF SOLAR PANELS INSTALLED  2019     0
11     18       LENGTH OF HIGH TENSION LINES (KM)  2019   0.0
12     18        LENGTH OF LOW TENSION LINES (KM)  2019   0.0
13     18  DISTANCE COVERED BY STREET LIGHTS (KM)  2019   0.0
14      2      NUMBER OF TRANSFORMERS DISTRIBUTED  2019     0
15      2        NUMBER OF GENERATORS DISTRIBUTED  2019   0.0
16      2        NUMBER OF STREET LIGHT INSTALLED  2019     0
17      2        NUMBER OF SOLAR PANELS INSTALLED  2019     0
18      2       LENGTH OF HIGH TENSION LINES (KM)  2019   0.0
19      2        LENGTH OF LOW TENSION LINES (KM)  2019   0.0
20      2  DISTANCE COVERED BY STREET LIGHTS (KM)  2019   0.0
21      9      NUMBER OF TRANSFORMERS DISTRIBUTED  2019     2

In [5]:
new_df['count']=new_df['count'].astype(int)
new_df.head()

  lga_id                 electricity_project  year  count
0     13  NUMBER OF TRANSFORMERS DISTRIBUTED  2019      1
1     13    NUMBER OF GENERATORS DISTRIBUTED  2019      0
2     13    NUMBER OF STREET LIGHT INSTALLED  2019      0
3     13    NUMBER OF SOLAR PANELS INSTALLED  2019      0
4     13   LENGTH OF HIGH TENSION LINES (KM)  2019      0

In [6]:
new_df.to_excel("electricity_projects.xlsx", index=False)
print("Done!")

Done!