In [5]:
import pandas as pd
pd.options.display.float_format = '{:.0f}'.format

In [6]:
sheets = ["Sheet1"]
file_names = ["./data/budget_2022.xlsx", "./data/budget_2023.xlsx", "./data/budget_2024.xlsx", "./data/budget_2025.xlsx"]
years = [2022, 2023, 2024, 2025]
dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

In [7]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,Ministry,Personnel Cost,Overhead Cost,Recurrent Expenditure,Capital Expenditure,Total Expenditure
0,Office of the Executive Governor,643829526,28607825825,36643366813,9000000000,45643366813
1,Office of the Secretary to the State Government,462472582,621054701,1062501318,2546000000,3658501318
2,Ministry of Finance,318861189,22812946,341674136,6025500000,6365174136
3,Ministry of Works,185899318,32427355,228326673,263320000000,266713266673
4,Ministry of Environment,269336207,77971382,261088352,0,261088352

In [8]:
# columns = ['Ministry', 'Personnel Cost', 'Overhead Cost', 'response']

new_df = pd.DataFrame(columns=["year", *dfs[0].columns])

for i, df in enumerate(dfs):
    year = years[i]
    df["year"] = year
    
    new_df = pd.concat([new_df, df], ignore_index=True)


new_df.head(50)

C:\Users\USER\AppData\Local\Temp\ipykernel_9920\2758193881.py:9: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, df], ignore_index=True)

,year,Ministry,Personnel Cost,Overhead Cost,Recurrent Expenditure,Capital Expenditure,Total Expenditure
0,2022,Office of the Executive Governor,643829526,28607825825,36643366813,9000000000,45643366813
1,2022,Office of the Secretary to the State Government,462472582,621054701,1062501318,2546000000,3658501318
2,2022,Ministry of Finance,318861189,22812946,341674136,6025500000,6365174136
3,2022,Ministry of Works,185899318,32427355,228326673,263320000000,266713266673
4,2022,Ministry of Environment,269336207,77971382,261088352,0,261088352
5,2022,Ministry of Justice,573367392,18339716,611057108,3065000000,3688707108
6,2022,"Ministry of Culture, Entertainment & Tourism",110066560,11384104,113450663,10111000000,10224450663
7,2022,Ministry of Petroleum and Mineral Resources,101311864,12984967,107296831,379000000,486296831
8,2022,"Ministry of Local Government, Chieftaincy & Co...",677308193,0,677308193,0,677308193
9,2022,Ministry of Power & Water Resources,488275684,16705379,413892105,13846833333,18285743337
10,2022,Ministry of Special Duties,20572200,17227600,39799800,915000000,936799800
11,2022,Anambra State House of Assembly,1519128693,3045100261,4604228954,5858000000,10462228954
12,2022,Anambra State Independent Electoral Commission,67113488,16910053,88023540,165000000,253523540
13,2022,Judicial Service Commission,5683750263,71849238,5862263617,7785600000,13657863617
14,2022,Anambra State Internal Revenue Service,525015287,89712372,634727659,679000000,1313727659
15,2022,Ministry of Information,273066530,17211374,292277904,5243118000,5515395904
16,2022,Office of the Head of Service,1026410186,275920722,1302330908,846000000,2148330908
17,2022,Anambra State Investment Promotion & Protectio...,201583990,0,201583990,0,201583990
18,2022,Christian Pilgrims Welfare Board,6976500,0,6976500,0,6976500
19,2022,Muslim Pilgrims Welfare Board,6910350,0,6910350,0,6910350
20,2022,Ministry of Homeland Affairs,131779993,13107400,140887393,2601500000,2752387393
21,2022,"Ministry of Social Welfare, Children & Women A...",110446653,9351322,120197975,2570600000,2902226775
22,2022,Ministry of Housing,134600177,11860000,148460177,9995000000,10199650177
23,2022,Ministry of Industry,270883463,19656250,292539713,527000000,819093413
24,2022,Ministry of Budget & Economic Planning,178035998,57476821,239512819,3411000000,580612819
25,2022,Ministry of Transport,241024782,11860000,254884782,3279700000,3554814782
26,2022,Ministry of Agriculture,608826114,66476821,626970954,2676000000,894570954
27,2022,Ministry of Education,312935929,797764026,1130699955,36374500000,47781499955
28,2022,Ministry of Youths,147732064,15822177,161554241,3204000000,471954241
29,2022,Ministry of Health,518449488,0,518449488,0,518449488
30,2022,Ministry of Lands,258238168,18182554,278420722,1669000000,445320722
31,2023,Office of the Executive Governor,659829526,29607825825,36643366813,9200000000,45843366813
32,2023,Office of the Secretary to the State Government,479472582,641054701,1062501318,2646000000,3708501318
33,2023,Ministry of Finance,329861189,23812946,353674136,6125500000,6475174136
34,2023,Ministry of Works,195899318,33427355,239326673,265320000000,268713266673
35,2023,Ministry of Environment,275336207,87971382,273088352,0,273088352
36,2023,Ministry of Justice,593367392,19339716,621057108,3095000000,3708707108
37,2023,"Ministry of Culture, Entertainment & Tourism",115066560,12384104,123450663,10211000000,10334450663
38,2023,Ministry of Petroleum and Mineral Resources,105311864,13984967,117296831,389000000,506296831
39,2023,"Ministry of Local Government, Chieftaincy & Co...",687308193,0,687308193,0,687308193
40,2023,Ministry of Power & Water Resources,498275684,17705379,423892105,14046833333,18485743337
41,2023,Ministry of Special Duties,21572200,18227600,40799800,925000000,953799800
42,2023,Anambra State House of Assembly,1539128693,3145100261,4704228954,5958000000,10662228954
43,2023,Anambra State Independent Electoral Commission,68113488,17910053,89023540,175000000,264523540
44,2023,Judicial Service Commission,5783750263,81849238,5962263617,7885600000,13857863617
45,2023,Anambra State Internal Revenue Service,545015287,99712372,654727659,689000000,1343727659
46,2023,Ministry of Information,283066530,18211374,302277904,5343118000,5625395904
47,2023,Office of the Head of Service,1046410186,285920722,1332330908,856000000,2188330908
48,2023,Anambra State Investment Promotion & Protectio...,211583990,0,211583990,0,211583990
49,2023,Christian Pilgrims Welfare Board,7076500,0,7076500,0,7076500

In [9]:
print(len(new_df))

124

In [10]:
new_df.to_excel("transposed/budget.xlsx", index=False)
print("Finished!")

Finished!