In [1]:
import pandas as pd
pd.options.display.float_format = '{:.2f}'.format

In [2]:
sheets = ["Sheet1"]
file_names = ["./data/budget_2022.xlsx", "./data/budget_2023.xlsx", "./data/budget_2024.xlsx", "./data/budget_2025.xlsx"]
years = [2022, 2023, 2024, 2025]
dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,Ministry,Personnel Cost,Overhead Cost,Recurrent Expenditure,Capital Expenditure,Total Expenditure
0,Office of the Executive Governor,4080308483,16804756186,20885064669,6955169151,27840233820
1,Office of the Secretary to the State Government,322535647,553817246,876352893,1654000000,2530352893
2,Ministry of Finance,12966620741,6469110079,19435730820,6025500000,22402587909
3,Ministry of Works,0,0,0,0,0
4,Ministry of Environment,86493115,188000000,274493115,3862183355,4136676470

In [4]:
# columns = ['Ministry', 'Personnel Cost', 'Overhead Cost', 'response']

new_df = pd.DataFrame(columns=["year", *dfs[0].columns])

for i, df in enumerate(dfs):
    year = years[i]
    df["year"] = year
    
    new_df = pd.concat([new_df, df], ignore_index=True)


new_df.head(50)

,year,Ministry,Personnel Cost,Overhead Cost,Recurrent Expenditure,Capital Expenditure,Total Expenditure
0,2022,Office of the Executive Governor,4080308483,16804756186,20885064669,6955169151,27840233820
1,2022,Office of the Secretary to the State Government,322535647,553817246,876352893,1654000000,2530352893
2,2022,Ministry of Finance,12966620741,6469110079,19435730820,6025500000,22402587909
3,2022,Ministry of Works,0,0,0,0,0
4,2022,Ministry of Environment,86493115,188000000,274493115,3862183355,4136676470
5,2022,Ministry of Justice,181740040,18850000,200590040,739212185,939802225
6,2022,"Ministry of Culture, Entertainment & Tourism",65770965,6000000,71770965,270955789,342726754
7,2022,Ministry of Petroleum and Mineral Resources,0,0,0,0,0
8,2022,"Ministry of Local Government, Chieftaincy & Co...",24957623,6000000,30957623,1560619000,1591576623
9,2022,Ministry of Power & Water Resources,152965425,19499035,172464460,3872782174,4045246634
10,2022,Ministry of Special Duties,0,0,0,0,0
11,2022,Anambra State House of Assembly,741452420,1517900000,2259352420,3500000000,5759352420
12,2022,Anambra State Independent Electoral Commission,41475000,15671037,57146037,308669723,365815760
13,2022,Judicial Service Commission,1663271635,189200000,1852471635,2815000000,4667471635
14,2022,Ministry of Information,173974394,635306010,809280404,942618075,1751898479
15,2022,Office of the Head of Service,460000000,14400000,474400000,654104400,1128504400
16,2022,Ministry of Homeland Affairs,0,0,0,0,0
17,2022,"Ministry of Social Welfare, Children & Women A...",68623400,13300000,81923400,726000000,807923400
18,2022,Ministry of Housing,61656822,18000000,79656822,3702203846,3781860668
19,2022,Ministry of Industry,124776892,18500000,143276892,1785948639,1929225531
20,2022,Ministry of Budget & Economic Planning,128480231,17443841,145924072,2496000000,2641924072
21,2022,Ministry of Transport,25606744,161500000,187106744,1165550000,1352656744
22,2022,Ministry of Agriculture,371267762,48285600,419553362,2278707129,2698260491
23,2022,Ministry of Education,5685260024,362934954,6048194978,3238402223,9286597201
24,2022,Ministry of Youths,95870753,39326100,135196853,2008750000,2143946853
25,2022,Ministry of Health,2557449656,1198709563,3756159219,5885260000,9641419219
26,2022,Ministry of Lands,175352525,225000000,400352525,1508480666,1908833191
27,2022,Office of the Auditor General (State),177003112,10500000,187503112,95200000,282703112
28,2022,Civil Service Commission,64716174,13000000,77716174,58053025,135769199
29,2022,Local Government Civil Service Commission,25480255,0,25480255,0,25480255
30,2022,Awka Capital Teritory Development Authority - ...,0,60200000,60200000,0,60200000
31,2023,Office of the Executive Governor,4401856028.57,17713149739.40,22115005767.97,3268487325.80,25383493093.76
32,2023,Office of the Secretary to the State Government,350074643.95,685823357.25,1035898001.20,1712205500.00,2748103501.20
33,2023,Ministry of Finance,15591770840.45,31320111690.25,46911882530.70,3457500000.00,50369382530.70
34,2023,Ministry of Works,170040879.00,13492500.00,183533379.00,80351500000.00,80535033379
35,2023,Ministry of Environment,94957181.56,197400000.00,292357181.56,2752199954.00,3044557135.56
36,2023,Ministry of Justice,203730265.00,19792500.00,223522765.00,1595000000.00,1818522765
37,2023,"Ministry of Culture, Entertainment & Tourism",73679058.25,6300000.00,79979058.25,7711000000.00,7790979058.25
38,2023,Ministry of Petroleum and Mineral Resources,18734364.00,6300000.00,25034364.00,395000000.00,420034364
39,2023,"Ministry of Local Government, Chieftaincy & Co...",27918612.03,6300000.00,34218612.03,3484000000.00,3518218612.03
40,2023,Ministry of Power & Water Resources,171394996.25,20473986.75,191868983.00,7123000000.00,7314868983
41,2023,Ministry of Special Duties,14700000.00,6300000.00,21000000.00,445000000.00,466000000
42,2023,Anambra State House of Assembly,787432944.00,2302205000.00,3089637944.00,3384070000.00,6473707944
43,2023,Anambra State Independent Electoral Commission,43548750.00,16454588.85,60003338.85,89120000.00,149123338.85
44,2023,Judicial Service Commission,1899355117.74,198660000.00,2098015117.74,2373780000.00,"₦ ₦ 4,471,795,117.74"
45,2023,Ministry of Information,195052501.70,667071311.00,862123812.70,647900000.00,1510023812.70
46,2023,Office of the Head of Service,521301065.00,65120000.00,586421065.00,530942000.00,1117363065
47,2023,Ministry of Homeland Affairs,90701175.00,6300000.00,97001175.00,1262180000.00,1359181175
48,2023,"Ministry of Social Welfare, Children & Women A...",76437273.00,13965000.00,90402273.00,2583000000.00,2673402273
49,2023,Ministry of Housing,68825119.10,18900000.00,87725119.10,6945000000.00,7032725119.10

In [5]:
print(len(new_df))

124

In [6]:
new_df.to_excel("transposed/budget.xlsx", index=False)
print("Finished!")

Finished!