In [1]:
import pandas as pd

In [5]:
sheets = ["Sheet1"]
file_names = ["women_affairs.xlsx"]
years = [2024]
dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [6]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,S/N,PHYSICAL ABUSE/BATTERY,PSYCHOLOGICAL/EMOTIONAL ABUSE,SEXUAL ASSAULT,RAPE/DEFILEMENT,FEMALE GENITAL MUTILATION,FORCED MARRIAGE,CHILD ABUSE AND NEGLECT,TRAFFICKING IN PERSONS,FORCEFUL EJECTION FROM FAMILY,...,EDUCATION LEVEL,ALLEGED PERPETRATOR SEX,ACCESS TO JUSTICE,CASE CLOSED,CASE CLOSED BY,DATE CASE CLOSED,FINAL OUTCOME,DATE JUSTICE DELIVERED,Unnamed: 29,STATE
0,1,0,0,0,0,0,0,0,0.0,0,...,COMPLETED SEC SCHOOL,M,YES,NO,0,0,0,0,0,0
1,2,0,0,YES,0,0,0,0,0.0,0,...,SOME SEC SCHOOL,M,YES,NO,0,0,0,0,0,0
2,3,YES,0,0,0,0,0,0,0.0,0,...,GRADUATE,0,YES,NO,0,0,0,0,0,0
3,4,YES,0,0,0,0,0,0,0.0,0,...,COMPLETED SEC SCHOOL,"M,F",YES,NO,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,0.0,0,...,COMPLETED SEC SCHOOL,M,YES,NO,0,0,0,0,0,0

In [13]:
columns = ['sn', 'year', 'question', 'response']

new_df = pd.DataFrame(columns=columns)
year = 2024

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        for col in df.columns[1:]:
            if(row[col] in ('0', 0)): continue
            transformed_data = [{
                'sn': row["S/N"],
                'year': year,
                'question': col,
                'response': row[col],
            }]

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(50)

   sn  year                                   question              response
0   1  2024  VIOLATION OF PROPERTY & INHERITANCE RIGHT                   YES
1   1  2024                   FINANCIAL/ECONOMIC ABUSE                   YES
2   1  2024                                        LGA               ANAOCHA
3   1  2024                                       WARD           AGULUZOIGBO
4   1  2024                           DATE OF INCIDENT   2022-11-16 00:00:00
5   1  2024                              DATE REPORTED   2024-02-12 00:00:00
6   1  2024                                 VICTIM SEX                     F
7   1  2024                             MARITAL STATUS               MARRIED
8   1  2024                              EMPLOY STATUS          SELF EMPOYED
9   1  2024                            EDUCATION LEVEL  COMPLETED SEC SCHOOL
10  1  2024                    ALLEGED PERPETRATOR SEX                     M
11  1  2024                          ACCESS TO JUSTICE                   YES
12  1  2024                                CASE CLOSED                    NO
13  2  2024                             SEXUAL ASSAULT                   YES
14  2  2024                                        LGA                AGUATA
15  2  2024                                       WARD             UJUALIGWE
16  2  2024                           DATE OF INCIDENT   2024-01-01 00:00:00
17  2  2024                              DATE REPORTED   2024-03-13 00:00:00
18  2  2024                             MARITAL STATUS               MARRIED
19  2  2024                              EMPLOY STATUS          SELF EMPOYED
20  2  2024                            EDUCATION LEVEL       SOME SEC SCHOOL
21  2  2024                    ALLEGED PERPETRATOR SEX                     M
22  2  2024                          ACCESS TO JUSTICE                   YES
23  2  2024                                CASE CLOSED                    NO
24  3  2024                     PHYSICAL ABUSE/BATTERY                   YES
25  3  2024                                        LGA               IDEMILI
26  3  2024                                       WARD                AMAFOR
27  3  2024                           DATE OF INCIDENT   2024-03-12 00:00:00
28  3  2024                              DATE REPORTED   2024-03-14 00:00:00
29  3  2024                             MARITAL STATUS               MARRIED
30  3  2024                              EMPLOY STATUS               EMLOYED
31  3  2024                            EDUCATION LEVEL              GRADUATE
32  3  2024                          ACCESS TO JUSTICE                   YES
33  3  2024                                CASE CLOSED                    NO
34  4  2024                     PHYSICAL ABUSE/BATTERY                   YES
35  4  2024                   FINANCIAL/ECONOMIC ABUSE                   YES
36  4  2024                                        LGA                   OYI
37  4  2024                                       WARD                UMUNYA
38  4  2024                           DATE OF INCIDENT   2024-03-18 00:00:00
39  4  2024                              DATE REPORTED   2024-03-28 00:00:00
40  4  2024                                 VICTIM SEX                     F
41  4  2024                             MARITAL STATUS               MARRIED
42  4  2024                              EMPLOY STATUS            UNEMPLOYED
43  4  2024                            EDUCATION LEVEL  COMPLETED SEC SCHOOL
44  4  2024                    ALLEGED PERPETRATOR SEX                   M,F
45  4  2024                          ACCESS TO JUSTICE                   YES
46  4  2024                                CASE CLOSED                    NO
47  5  2024                                        LGA                   OYI
48  5  2024                                       WARD           UMUOBA ANAM
49  5  2024                           DATE OF INCIDENT   2024-04-07 00:00:00

In [11]:
print(len(new_df))

758

In [14]:
new_df.to_excel("Women_affairs_transposed.xlsx", index=False)
print("Done!")

Done!