In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 190", "Table 191", "Table 192", "Table 193"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

            LGA  MALE  FEMALE
0        AGUATA     3      10
1  ANAMBRA EAST     1       8
2  ANAMBRA WEST     4       9
3       ANAOCHA     4      10
4    AWKA NORTH     3       5

In [4]:
columns = ['lga', 'year', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        for col in df.columns[1:]:
            transformed_data = [{
                'lga': row["LGA"],
                'year': year,
                'gender': col.strip(),
                'population': int(row[col]),
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

              lga  year  gender population
0          AGUATA  2019    MALE          2
1          AGUATA  2019  FEMALE          9
2    ANAMBRA EAST  2019    MALE          2
3    ANAMBRA EAST  2019  FEMALE          7
4    ANAMBRA WEST  2019    MALE          3
5    ANAMBRA WEST  2019  FEMALE         10
6         ANAOCHA  2019    MALE          5
7         ANAOCHA  2019  FEMALE          6
8      AWKA NORTH  2019    MALE          1
9      AWKA NORTH  2019  FEMALE          4
10     AWKA SOUTH  2019    MALE          5
11     AWKA SOUTH  2019  FEMALE         18
12       AYAMELUM  2019    MALE          2
13       AYAMELUM  2019  FEMALE          6
14      DUNUKOFIA  2019    MALE          3
15      DUNUKOFIA  2019  FEMALE         10
16       EKWUSIGO  2019    MALE          2
17       EKWUSIGO  2019  FEMALE          8
18  IDEMILI NORTH  2019    MALE          4
19  IDEMILI NORTH  2019  FEMALE         20
20  IDEMILI SOUTH  2019    MALE          1
21  IDEMILI SOUTH  2019  FEMALE         13

In [5]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

            lga  year  gender  population
0        AGUATA  2019    MALE           2
1        AGUATA  2019  FEMALE           9
2  ANAMBRA EAST  2019    MALE           2
3  ANAMBRA EAST  2019  FEMALE           7
4  ANAMBRA WEST  2019    MALE           3

In [6]:
new_df.to_excel("civil_defence_corp_population.xlsx", index=False)
print("Done!")

Done!