In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021]
sheets = ["Table 194", "Table 195", "Table 196"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

            LGA  MALE  FEMALE
0        AGUATA     5       1
1  ANAMBRA EAST     5       0
2  ANAMBRA WEST     4       0
3       ANAOCHA     7       1
4    AWKA NORTH     3       4

In [4]:
columns = ['lga_id', 'year', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"]) == 0):
            print(row["LGA"])
            continue

        for col in df.columns[1:]:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'year': year,
                'gender': col.strip(),
                'population': int(row[col]),
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year  gender population
0      13  2019    MALE          3
1      13  2019  FEMALE          1
2      18  2019    MALE          4
3      18  2019  FEMALE          1
4       2  2019    MALE          4
5       2  2019  FEMALE          2
6       9  2019    MALE          4
7       9  2019  FEMALE          1
8      15  2019    MALE          5
9      15  2019  FEMALE          0
10     20  2019    MALE          3
11     20  2019  FEMALE          6
12      6  2019    MALE          1
13      6  2019  FEMALE          2
14     12  2019    MALE          2
15     12  2019  FEMALE          5
16     17  2019    MALE          4
17     17  2019  FEMALE          1
18      8  2019    MALE          7
19      8  2019  FEMALE          2
20      3  2019    MALE          4
21      3  2019  FEMALE          3

In [5]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id  year  gender  population
0     13  2019    MALE           3
1     13  2019  FEMALE           1
2     18  2019    MALE           4
3     18  2019  FEMALE           1
4      2  2019    MALE           4

In [6]:
new_df.to_excel("immigration_personnel_population.xlsx", index=False)
print("Done!")

Done!