In [15]:
import pandas as pd

In [16]:
sheets = ["Sheet1"]
file_names = ["phase1.xlsx", "phase2.xlsx"]
batches = ["Phase 1", "Phase 2"]
dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [17]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,SN,LGA,No. OF MALE,No. OF FEMALE,No. OF PWDs,No. WITH HIGH LITERACY (FSLC and Above),No. WITH LOW LITERACY LEVEL (Below FSLC)
0,1.0,AWKA SOUTH,412,618,27,1030,0
1,2.0,AWKA NORTH,33,49,3,82,0
2,3.0,ANAOCHA,94,56,2,150,0
3,4.0,DUNUKOFIA,48,31,0,79,0
4,5.0,NJIKOKA,49,72,1,121,0

In [21]:
columns = ['lga', 'year', 'batch', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)
year = 2024

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(row["LGA"]==0): continue

        transformed_data = [{
            'lga': row["LGA"],
            'year': year,
            'batch': batches[i],
            'gender': "Male",
            'population': row["No. OF MALE"]
        },{
            'lga': row["LGA"],
            'year': year,
            'batch': batches[i],
            'gender': "Female",
            'population': row["No. OF FEMALE"]
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.tail(22)

              lga  year    batch  gender population
66  ONITSHA NORTH  2024  Phase 2    Male      636.0
67  ONITSHA NORTH  2024  Phase 2  Female      966.0
68  ONITSHA SOUTH  2024  Phase 2    Male      206.0
69  ONITSHA SOUTH  2024  Phase 2  Female      314.0
70            OYI  2024  Phase 2    Male      137.0
71            OYI  2024  Phase 2  Female      206.0
72         AGUATA  2024  Phase 2    Male      364.0
73         AGUATA  2024  Phase 2  Female      553.0
74       EKWUSIGO  2024  Phase 2    Male      134.0
75       EKWUSIGO  2024  Phase 2  Female      200.0
76         IHIALA  2024  Phase 2    Male      204.0
77         IHIALA  2024  Phase 2  Female      305.0
78    NNEWI NORTH  2024  Phase 2    Male      178.0
79    NNEWI NORTH  2024  Phase 2  Female      269.0
80    NNEWI SOUTH  2024  Phase 2    Male      128.0
81    NNEWI SOUTH  2024  Phase 2  Female      193.0
82   ORUMBA NORTH  2024  Phase 2    Male      228.0
83   ORUMBA NORTH  2024  Phase 2  Female      343.0
84   ORUMBA SOUTH  2024  Phase 2    Male      186.0
85   ORUMBA SOUTH  2024  Phase 2  Female      280.0
86         UMUBOI  2024  Phase 2    Male        0.0
87         UMUBOI  2024  Phase 2  Female        0.0

In [19]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

          lga  year    batch  gender  population
0  AWKA SOUTH  2024  Phase 1    Male         412
1  AWKA SOUTH  2024  Phase 1  Female         618
2  AWKA NORTH  2024  Phase 1    Male          33
3  AWKA NORTH  2024  Phase 1  Female          49
4     ANAOCHA  2024  Phase 1    Male          94

In [20]:
new_df.to_excel("youth_population.xlsx", index=False)
print("Done!")

Done!