In [1]:
import pandas as pd

In [2]:
sheets = ["Sheet1"]
file_names = ["phase1.xlsx", "phase2.xlsx"]
batches = ["Phase 1", "Phase 2"]
dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,SN,LGA,No. OF MALE,No. OF FEMALE,No. OF PWDs,No. WITH HIGH LITERACY (FSLC and Above),No. WITH LOW LITERACY LEVEL (Below FSLC)
0,1.0,AWKA SOUTH,412,618,27,1030,0
1,2.0,AWKA NORTH,33,49,3,82,0
2,3.0,ANAOCHA,94,56,2,150,0
3,4.0,DUNUKOFIA,48,31,0,79,0
4,5.0,NJIKOKA,49,72,1,121,0

In [9]:
columns = ['lga', 'year', 'batch', 'literacy_level', 'population']

new_df = pd.DataFrame(columns=columns)
year = 2024

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(row["LGA"]==0): continue
        transformed_data = [{
            'lga': row["LGA"],
            'year': year,
            'batch': batches[i],
            'literacy_level': "High",
            'population': row["No. WITH HIGH LITERACY (FSLC and Above)"]
        },{
            'lga': row["LGA"],
            'year': year,
            'batch': batches[i],
            'literacy_level': "Low",
            'population': row["No. WITH LOW LITERACY LEVEL (Below FSLC)"]
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.tail(22)

              lga  year    batch literacy_level population
66  ONITSHA NORTH  2024  Phase 2           High     1610.0
67  ONITSHA NORTH  2024  Phase 2            Low        0.0
68  ONITSHA SOUTH  2024  Phase 2           High      523.0
69  ONITSHA SOUTH  2024  Phase 2            Low        0.0
70            OYI  2024  Phase 2           High      344.0
71            OYI  2024  Phase 2            Low        0.0
72         AGUATA  2024  Phase 2           High      922.0
73         AGUATA  2024  Phase 2            Low        0.0
74       EKWUSIGO  2024  Phase 2           High      334.0
75       EKWUSIGO  2024  Phase 2            Low        0.0
76         IHIALA  2024  Phase 2           High      509.0
77         IHIALA  2024  Phase 2            Low        0.0
78    NNEWI NORTH  2024  Phase 2           High      449.0
79    NNEWI NORTH  2024  Phase 2            Low        0.0
80    NNEWI SOUTH  2024  Phase 2           High      322.0
81    NNEWI SOUTH  2024  Phase 2            Low        0.0
82   ORUMBA NORTH  2024  Phase 2           High      571.0
83   ORUMBA NORTH  2024  Phase 2            Low        0.0
84   ORUMBA SOUTH  2024  Phase 2           High      466.0
85   ORUMBA SOUTH  2024  Phase 2            Low        0.0
86         UMUBOI  2024  Phase 2           High        0.0
87         UMUBOI  2024  Phase 2            Low        0.0

In [10]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

          lga  year    batch literacy_level  population
0  AWKA SOUTH  2024  Phase 1           High        1030
1  AWKA SOUTH  2024  Phase 1            Low           0
2  AWKA NORTH  2024  Phase 1           High          82
3  AWKA NORTH  2024  Phase 1            Low           0
4     ANAOCHA  2024  Phase 1           High         150

In [13]:
new_df.to_excel("youth_population_by_literacy_level.xlsx", index=False)
print("Done!")

Done!