In [8]:
import pandas as pd

In [9]:
sheets = ["Sheet1"]
file_names = ["job_creation_statistics.xlsx", "phase2.xlsx"]
batches = ["Phase 1", "Phase 2"]
sessions = ["2022/2023", "2024/2025"]

dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [10]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,SN,LGA,No. OF MALE,No. OF FEMALE,No. OF PWDs,No. WITH HIGH LITERACY (FSLC and Above),No. WITH LOW LITERACY LEVEL (Below FSLC)
0,1.0,AWKA SOUTH,471,621,27,1092,0
1,2.0,AWKA NORTH,33,49,3,82,0
2,3.0,ANAOCHA,107,94,2,201,0
3,4.0,DUNUKOFIA,48,31,0,79,0
4,5.0,NJIKOKA,74,97,5,171,0

In [11]:
columns = ['lga', 'session', 'batch', 'pwd']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        if(row["LGA"]==0): continue

        transformed_data = [{
            'lga': row["LGA"],
            'session': sessions[i],
            'batch': batches[i],
            'pwd': row["No. OF PWDs"]
        }]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

              lga    session    batch pwd
0      AWKA SOUTH  2022/2023  Phase 1  27
1      AWKA NORTH  2022/2023  Phase 1   3
2         ANAOCHA  2022/2023  Phase 1   2
3       DUNUKOFIA  2022/2023  Phase 1   0
4         NJIKOKA  2022/2023  Phase 1   5
5   IDEMILI NORTH  2022/2023  Phase 1   2
6   IDEMILI SOUTH  2022/2023  Phase 1   0
7    ANAMBRA EAST  2022/2023  Phase 1   0
8    ANAMBRA WEST  2022/2023  Phase 1   0
9        AYAMELUM  2022/2023  Phase 1   0
10         OGBARU  2022/2023  Phase 1   7
11  ONITSHA NORTH  2022/2023  Phase 1   8
12  ONITSHA SOUTH  2022/2023  Phase 1   2
13            OYI  2022/2023  Phase 1   0
14         AGUATA  2022/2023  Phase 1   5
15       EKWUSIGO  2022/2023  Phase 1   1
16         IHIALA  2022/2023  Phase 1   0
17    NNEWI NORTH  2022/2023  Phase 1   2
18    NNEWI SOUTH  2022/2023  Phase 1   0
19   ORUMBA NORTH  2022/2023  Phase 1   0
20   ORUMBA SOUTH  2022/2023  Phase 1   0
21         UMUBOI  2022/2023  Phase 1   0

In [12]:
new_df['pwd']=new_df['pwd'].astype(int)
new_df.head()

          lga    session    batch  pwd
0  AWKA SOUTH  2022/2023  Phase 1   27
1  AWKA NORTH  2022/2023  Phase 1    3
2     ANAOCHA  2022/2023  Phase 1    2
3   DUNUKOFIA  2022/2023  Phase 1    0
4     NJIKOKA  2022/2023  Phase 1    5

In [13]:
new_df.to_excel("transposedb/youth_pwds.xlsx", index=False)
print("Done!")

Done!