In [5]:
import pandas as pd

In [8]:
years = [2022]
sheets = ["Table 186"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [9]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

,MONTH,AIRLINES,NUMBER OF FLIGHTS (ARRIVALS & DEPARTURE),NUMBER OF ARRIVING PASSENGERS,NUMBER OF DEPARTING PASSENGERS,TOTAL NUMBER OF PASSENGERS
0,JANUARY,AIR PEACE,80,1672,1658,3330
1,0,UNITED NIGERIA,102,1756,1897,3653
2,0,PRIVATE JET,52,148,197,345
3,TOTAL,0,234,3576,3752,7328
4,FEBRUARY,AIR PEACE,80,1852,1940,3792

In [12]:
columns = ['timestamp', 'airlines', 'flights', 'arriving_passengers', 'departing_passengers']
months = {"JANUARY":"01", "FEBRUARY":"02","MARCH":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUGUST":"08","SEPTEMBER":"09","OCTOBER":"10","NOVEMBER":"11","DECEMBER":"12"}


new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    df["MONTH"]=df["MONTH"].astype(str)
    for i, row in df.iterrows():
        if(row["MONTH"]=="TOTAL"): continue
        if(row["MONTH"]!="0"): month=row["MONTH"]
        
        transformed_data = [{
            'timestamp': str(months[month])+"-01-"+str(year),
            'airlines': row["AIRLINES"],
            'flights': row["NUMBER OF FLIGHTS (ARRIVALS & DEPARTURE)"],
            'arriving_passengers': row["NUMBER OF ARRIVING PASSENGERS"],
            'departing_passengers': row["NUMBER OF DEPARTING PASSENGERS"],
        }]
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(50)

,timestamp,airlines,flights,arriving_passengers,departing_passengers
0,01-01-2022,AIR PEACE,80,1672,1658
1,01-01-2022,UNITED NIGERIA,102,1756,1897
2,01-01-2022,PRIVATE JET,52,148,197
3,02-01-2022,AIR PEACE,80,1852,1940
4,02-01-2022,UNITED NIGERIA,108,1976,1914
5,02-01-2022,PRIVATE JET,30,55,47
6,03-01-2022,AIR PEACE,88,2811,2992
7,03-01-2022,UNITED NIGERIA,128,1845,1872
8,03-01-2022,PRIVATE JET,34,80,82
9,04-01-2022,AIR PEACE,112,5918,5026
10,04-01-2022,UNITED NIGERIA,124,2106,1773
11,04-01-2022,PRIVATE JET,30,95,68
12,05-01-2022,AIR PEACE,106,4403,4298
13,05-01-2022,UNITED NIGERIA,106,1454,1444
14,05-01-2022,PRIVATE JET,24,77,80
15,06-01-2022,AIR PEACE,104,4189,4108
16,06-01-2022,UNITED NIGERIA,102,1928,1387
17,06-01-2022,PRIVATE JET,16,38,72
18,07-01-2022,AIR PEACE,94,4288,3898
19,07-01-2022,UNITED NIGERIA,46,731,578
20,07-01-2022,PRIVATE JET,8,51,11
21,08-01-2022,AIR PEACE,106,4746,4489
22,08-01-2022,UNITED NIGERIA,18,282,302
23,08-01-2022,PRIVATE JET,0,0,0
24,09-01-2022,AIR PEACE,104,4244,4019
25,09-01-2022,UNITED NIGERIA,18,280,279
26,09-01-2022,PRIVATE JET,10,20,5
27,10-01-2022,AIR PEACE,104,3815,3783
28,10-01-2022,UNITED NIGERIA,14,390,182
29,10-01-2022,PRIVATE JET,18,83,55
30,11-01-2022,AIR PEACE,104,4312,3783
31,11-01-2022,UNITED NIGERIA,32,438,182
32,11-01-2022,PRIVATE JET,8,13,55
33,12-01-2022,AIR PEACE,148,7618,4375
34,12-01-2022,UNITED NIGERIA,44,966,547
35,12-01-2022,PRIVATE JET,36,223,179

In [14]:
new_df["flights"]=new_df["flights"].astype(int)
new_df["arriving_passengers"]=new_df["arriving_passengers"].astype(int)
new_df["departing_passengers"]=new_df["departing_passengers"].astype(int)

new_df.to_excel("airlines_traffic.xlsx", index=False)
print("Done!")

Done!