In [7]:
import pandas as pd

In [8]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 182", "Table 183", "Table 184", "Table 185"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [9]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

      MONTH  NUMBER OF IMPOUNDED VEHICLES
0   JANUARY                           848
1  FEBRUARY                           384
2     MARCH                          1261
3     APRIL                             3
4       MAY                           345

In [10]:
columns = ['timestamp', 'impounded_vehicles']
months = {"JANUARY":"01", "FEBRUARY":"02","MARCH":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUGUST":"08","SEPTEMBER":"09","OCTOBER":"10","NOVEMBER":"11","DECEMBER":"12"}

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'timestamp': str(months[row['MONTH']])+"-01-"+str(year),
            'impounded_vehicles': row['NUMBER OF IMPOUNDED VEHICLES']
        }]
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

     timestamp impounded_vehicles
0   01-01-2019                521
1   02-01-2019                921
2   03-01-2019               1318
3   04-01-2019               1485
4   05-01-2019               1301
5   06-01-2019               1257
6   07-01-2019               1745
7   08-01-2019               1562
8   09-01-2019               1515
9   10-01-2019               1734
10  11-01-2019               1470
11  12-01-2019                871
12  01-01-2020                848
13  02-01-2020                384
14  03-01-2020               1261
15  04-01-2020                  3
16  05-01-2020                345
17  06-01-2020               1959
18  07-01-2020               3197
19  08-01-2020               3049
20  09-01-2020               2417
21  10-01-2020               1510

In [11]:
new_df['impounded_vehicles']=new_df['impounded_vehicles'].astype(int)
new_df.head()

    timestamp  impounded_vehicles
0  01-01-2019                 521
1  02-01-2019                 921
2  03-01-2019                1318
3  04-01-2019                1485
4  05-01-2019                1301

In [13]:
new_df.to_excel("impounded_vehicles.xlsx", index=False)
print("Done!")

Done!