In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 182", "Table 183", "Table 184", "Table 185"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

      MONTH  NUMBER OF IMPOUNDED VEHICLES
0   JANUARY                           848
1  FEBRUARY                           384
2     MARCH                          1261
3     APRIL                             3
4       MAY                           345

In [4]:
columns = ['year', 'month', 'impounded_vehicles']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'year': year,
            'month': row['MONTH'],
            'impounded_vehicles': row['NUMBER OF IMPOUNDED VEHICLES']
        }]
        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

    year      month impounded_vehicles
0   2019    JANUARY                521
1   2019   FEBRUARY                921
2   2019      MARCH               1318
3   2019      APRIL               1485
4   2019        MAY               1301
5   2019       JUNE               1257
6   2019       JULY               1745
7   2019     AUGUST               1562
8   2019  SEPTEMBER               1515
9   2019    OCTOBER               1734
10  2019   NOVEMBER               1470
11  2019   DECEMBER                871
12  2020    JANUARY                848
13  2020   FEBRUARY                384
14  2020      MARCH               1261
15  2020      APRIL                  3
16  2020        MAY                345
17  2020       JUNE               1959
18  2020       JULY               3197
19  2020     AUGUST               3049
20  2020  SEPTEMBER               2417
21  2020    OCTOBER               1510

In [5]:
new_df['impounded_vehicles']=new_df['impounded_vehicles'].astype(int)
new_df.head()

   year     month  impounded_vehicles
0  2019   JANUARY                 521
1  2019  FEBRUARY                 921
2  2019     MARCH                1318
3  2019     APRIL                1485
4  2019       MAY                1301

In [6]:
new_df.to_excel("impounded_vehicles.xlsx", index=False)
print("Done!")

Done!