In [3]:
import pandas as pd

In [4]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 174", "Table 175", "Table 176", "Table 177"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [5]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,Unnamed: 0,OFFENCES,CARS,BUS/PICK UP SHUTTLE,MINI BUS,LUXURY BUS,TRAILER,LORRY,KEKE NAPEP,MOTORCYCLE
0,1,ROAD OBSTRUCTION,120,110,10,0,10,6,0,0
1,2,ROUTE VIOLATION,60,30,15,0,1,1,109,150
2,3,CAUTION SIGN VIOLATION,20,10,0,0,0,0,0,0
3,4,DANGEROUS DRIVING,0,0,0,0,0,0,0,0
4,5,DRUNK DRIVING,0,0,2,0,0,0,0,0

In [6]:
columns = ['year', 'offences', 'vehicle_category', 'count']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        for column in df.columns[2:]:
            transformed_data = [{
                'year': year,
                'offences': row['OFFENCES'],
                'vehicle_category': column,
                'count': row[column]
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

    year                offences     vehicle_category count
0   2019        ROAD OBSTRUCTION                 CARS    50
1   2019        ROAD OBSTRUCTION  BUS/PICK UP SHUTTLE   100
2   2019        ROAD OBSTRUCTION             MINI BUS    10
3   2019        ROAD OBSTRUCTION           LUXURY BUS     0
4   2019        ROAD OBSTRUCTION              TRAILER     7
5   2019        ROAD OBSTRUCTION                LORRY     0
6   2019        ROAD OBSTRUCTION           KEKE NAPEP    40
7   2019        ROAD OBSTRUCTION           MOTORCYCLE     0
8   2019         ROUTE VIOLATION                 CARS    50
9   2019         ROUTE VIOLATION  BUS/PICK UP SHUTTLE    40
10  2019         ROUTE VIOLATION             MINI BUS     4
11  2019         ROUTE VIOLATION           LUXURY BUS     0
12  2019         ROUTE VIOLATION              TRAILER     3
13  2019         ROUTE VIOLATION                LORRY     0
14  2019         ROUTE VIOLATION           KEKE NAPEP    50
15  2019         ROUTE VIOLATION           MOTORCYCLE    80
16  2019  CAUTION SIGN VIOLATION                 CARS    20
17  2019  CAUTION SIGN VIOLATION  BUS/PICK UP SHUTTLE    10
18  2019  CAUTION SIGN VIOLATION             MINI BUS     5
19  2019  CAUTION SIGN VIOLATION           LUXURY BUS     0
20  2019  CAUTION SIGN VIOLATION              TRAILER     3
21  2019  CAUTION SIGN VIOLATION                LORRY     0

In [7]:
new_df['count']=new_df['count'].astype(int)

len(new_df['offences'].unique())

13

In [8]:
new_df.to_excel("road_traffic_offences.xlsx", index=False)
print("Done!")

Done!