In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021]
sheets = ["Table 189"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,CONSTITUENCY,NAME,GENDER,POSITION,DATE OF BIRTH,POLITICAL PARTY,FIRST ELECTION YEAR INTO THE HOUSE,ACADEMIC QUALIFICATION,PHONE NUMBER,EMAIL
0,AGUATA I,Hon Umeonoduagu Nnmandi Dike,M,Member,1982-04-05,APGA,2019 1st\nTerm,Ph.D,7038810872,nnamdiumehh@yahoo.com
1,AGUATA II,Hon Okechukwu I. Okoye,M,Member,1978-09-29,APGA,2019 1st\nTerm,M.Sc,8025255381,zicomary@yahoo.com
2,ANAMBRA EAST,Hon Obinna Chris Emenaka,M,Member,1978-09-30,APGA,2012 3rd\nTerm,M.Sc,8037434955,staminai@yahoo.com
3,ANAMBRA WEST,Hon Udoba Patrick Obalum,M,Member,1968-10-10,APGA,2019 1st\nTerm,SSCE,8067796455,sirpatudoba22@gmail.com
4,ANAOCHA I,Hon Ejiofor Ebele Leonard,M,Deputy Minority\nLeader,1976-11-22,PDP,2011 2nd\nTerm,B.Sc,8035010322,ejioforleo@yahoo.com

In [14]:
columns = ['constituency', 'assembly', 'name', 'gender', 'position', 'date_of_birth', 'political_party', 'first_election_year_into_the_house', 'academic_qualification', 'phone_number', 'email']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        transformed_data = [{
            'constituency': row['CONSTITUENCY'].replace("\n", " "),
            'assembly': '7th',
            'name': row["NAME"].replace("\n", " "),
            'gender': "Male" if row["GENDER"] == 'M' else "Female",
            'position': row["POSITION"].replace("\n", " "),
            'date_of_birth': row["DATE OF BIRTH"].strftime("%m-%d-%Y"),
            'political_party': row["POLITICAL PARTY"].replace("\n", " "),
            'first_election_year_into_the_house': row["FIRST ELECTION YEAR INTO THE HOUSE"].replace("\n", " "),
            'academic_qualification': row["ACADEMIC QUALIFICATION"].replace("\n", " "),
            'phone_number': '0'+str(row["PHONE NUMBER"]),
            'email': row["EMAIL"].replace("\n", " "),
        }]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,constituency,assembly,name,gender,position,date_of_birth,political_party,first_election_year_into_the_house,academic_qualification,phone_number,email
0,AGUATA I,7th,Hon Umeonoduagu Nnmandi Dike,Male,Member,04-05-1982,APGA,2019 1st Term,Ph.D,07038810872,nnamdiumehh@yahoo.com
1,AGUATA II,7th,Hon Okechukwu I. Okoye,Male,Member,09-29-1978,APGA,2019 1st Term,M.Sc,08025255381,zicomary@yahoo.com
2,ANAMBRA EAST,7th,Hon Obinna Chris Emenaka,Male,Member,09-30-1978,APGA,2012 3rd Term,M.Sc,08037434955,staminai@yahoo.com
3,ANAMBRA WEST,7th,Hon Udoba Patrick Obalum,Male,Member,10-10-1968,APGA,2019 1st Term,SSCE,08067796455,sirpatudoba22@gmail.com
4,ANAOCHA I,7th,Hon Ejiofor Ebele Leonard,Male,Deputy Minority Leader,11-22-1976,PDP,2011 2nd Term,B.Sc,08035010322,ejioforleo@yahoo.com
5,ANAOCHA II,7th,Hon Okechukwu Ejike A.,Male,Member,06-21-1976,APGA,2019 1st Term,B.A.Ed,08062463334,ogbunuko@gmail.com
6,AWKA NORTH,7th,Hon Nwokoye John I.,Male,Member,07-19-1979,APGA,2019 1st Term,B.Sc,08036746910,nwokoyejohn@gmail.com
7,AWKA SOUTH I,7th,Hon Godwin Nnamdi Okafor,Male,Majority Leader,01-07-1964,APGA,2015 2nd Term,Ph.D,08060041127,majorityleaderanha@gmail.com
8,AWKA SOUTH II,7th,Hon Okoye Pius Chukwuma,Male,Member,09-22-1986,APGA,2019 1st Term,SSCE,08162570657,chukwumaokoye2013@yahoo.com
9,AYAMELUM,7th,Hon Uche Victor Okafor,Male,Speaker,04-03-1977,APGA,2015 2nd Term,M.Sc,09033244611,ucheokafor@legislator.com
10,DUNUKOFIA,7th,Hon Ezeudu Lawrence C.,Male,Member,08-16-1974,APGA,2015 2nd Term,LL.M,08168907328,lawrenceezeudu.c@gmail.com
11,EKWUSIGO,7th,Hon Offor Onyebuchi Augustine,Male,Minority Leader,11-02-1967,PDP,2015 2nd Term,B.Sc,08037121777,onyebuchi_offor@yahoo.com
12,IDEMILI NORTH,7th,Hon Chiekwu Arthur Ifeanyi,Male,Member,06-08-1978,APGA,2019 1st Term,B.Sc,08033132597,arthrichard1477@gmail.com
13,IDEMILI SOUTH,7th,Hon Ezenwunne Fabian Chuka,Male,Member,07-07-1966,APGA,2015 2nd Term,"B.L, LL.B",08037108058,ezenwunechuka@gmail.com
14,IHIALA I,7th,Hon Chidi Livinus Udemadu,Male,Member,10-28-1972,APGA,2015 2nd Term,"B.L, LL.B",08037055542,ezemsinachi032@gmail.com
15,IHIALA II,7th,Hon Agbodike Pascal,Male,Deputy Speaker,08-28-1980,APGA,2015 2nd Term,Ph.D,08037089269,pascalarinze@gmail.com
16,NNEWI NORTH,7th,Hon Okafor Nonso Peter,Male,Member,03-27-1981,APGA,2019 1st Term,HND,08030992443,npokafor@gmail.com
17,NNEWI SOUTH I,7th,Hon Sonny F. Oziobialu,Male,Member,01-08-1966,APGA,2019 1st Term,B.Sc,08033566945,ozobialusonny@gmail.com
18,NNEWI SOUTH II,7th,Hon Akaegbobi Johnbosco,Male,Member,08-29-1983,PDP,2019 1st Term,M.Sc,08164271389,johnbosco@mail.com
19,NJIKOKA I,7th,Hon Timothy Ifedioranma,Male,Member,05-07-1960,APGA,2015 2nd Term,Ph.D,08034336114,mercychurches@yahoo.com
20,NJIKOKA II,7th,Hon Sir Peter C.N Ibida,Male,Chief Whip,01-01-1959,APGA,2015 2nd Term,B.Sc,08033427193,pibida@yahoo.com
21,OGBARU I,7th,Hon Igwe Noble Chukwunonso,Male,Member,06-13-1978,PDP,2019 1st Term,B.Sc,08036738681,igwenoblenonso@gmail.com

In [15]:
new_df.to_excel("legislators_profile.xlsx", index=False)
print("Done!")

Done!