In [2]:
import pandas as pd

In [3]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 214", "Table 215", "Table 216", "Table 217"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [4]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,BOREHOLE FUNCTIONAL,BOREHOLE NON-FUNCTIONAL,HAND PUMB FUNCTIONAL,HAND PUMB NON-FUNCTIONAL,PIPE-BORNE WATER,STREAM,OPEN WELL (DUG),OTHERS
0,AGUATA,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ANAMBRA EAST,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ANAMBRA WEST,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ANAOCHA,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AWKA NORTH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
columns = ['lga_id', 'sources', 'year', 'count']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        for col in df.columns[1:-1]:

            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'sources': col,
                'year': year,
                'count': row[col],
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_7316\1647718983.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id                   sources  year  count
0      13       BOREHOLE FUNCTIONAL  2019    0.0
1      13   BOREHOLE NON-FUNCTIONAL  2019    0.0
2      13      HAND PUMB FUNCTIONAL  2019    0.0
3      13  HAND PUMB NON-FUNCTIONAL  2019    0.0
4      13          PIPE-BORNE WATER  2019    0.0
5      13                    STREAM  2019    0.0
6      13           OPEN WELL (DUG)  2019    0.0
7      18       BOREHOLE FUNCTIONAL  2019    0.0
8      18   BOREHOLE NON-FUNCTIONAL  2019    0.0
9      18      HAND PUMB FUNCTIONAL  2019    0.0
10     18  HAND PUMB NON-FUNCTIONAL  2019    0.0
11     18          PIPE-BORNE WATER  2019    0.0
12     18                    STREAM  2019    0.0
13     18           OPEN WELL (DUG)  2019    0.0
14      2       BOREHOLE FUNCTIONAL  2019    0.0
15      2   BOREHOLE NON-FUNCTIONAL  2019    0.0
16      2      HAND PUMB FUNCTIONAL  2019    0.0
17      2  HAND PUMB NON-FUNCTIONAL  2019    0.0
18      2          PIPE-BORNE WATER  2019    0.0
19      2                    STREAM  2019    0.0
20      2           OPEN WELL (DUG)  2019    0.0
21      9       BOREHOLE FUNCTIONAL  2019    0.0

In [6]:
new_df['count']=new_df['count'].astype(int)
new_df.head()

  lga_id                   sources  year  count
0     13       BOREHOLE FUNCTIONAL  2019      0
1     13   BOREHOLE NON-FUNCTIONAL  2019      0
2     13      HAND PUMB FUNCTIONAL  2019      0
3     13  HAND PUMB NON-FUNCTIONAL  2019      0
4     13          PIPE-BORNE WATER  2019      0

In [7]:
new_df.to_excel("sources_of_water_supply.xlsx", index=False)
print("Done!")

Done!

In [8]:
import numpy as np
print(np.sum(new_df["count"]))

39