In [1]:
import pandas as pd

In [13]:
sheets = ["Table 202"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [14]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna('')
    dfs[index].replace(['NA', 'NIL', '-'], '', inplace=True)

dfs[0].head()

   S/N           MEDIA HOUSES   TYPE CATEGORY LOCATION/ADDRESS
0    1  THE  NATION NEWSPAPER  PRINT  PRIVATE             AWKA
1    2     GUARDIAN NEWSPAPER  PRINT  PRIVATE             AWKA
2    3                  PUNCH  PRINT  PRIVATE             AWKA
3    4     THIS DAY NEWSPAPER  PRINT  PRIVATE             AWKA
4    5                THE SUN  PRINT  PRIVATE             AWKA

In [15]:
columns = ['media_houses', 'year', 'type', 'category', 'location']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        transformed_data = [{
            'media_houses': row['MEDIA HOUSES'],
            'year': 2021,
            'type': row['TYPE'],
            'category': row['CATEGORY'],
            'location': row['LOCATION/ADDRESS']
        },]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

new_df.head(22)

,media_houses,year,type,category,location
0,THE NATION NEWSPAPER,2021,PRINT,PRIVATE,AWKA
1,GUARDIAN NEWSPAPER,2021,PRINT,PRIVATE,AWKA
2,PUNCH,2021,PRINT,PRIVATE,AWKA
3,THIS DAY NEWSPAPER,2021,PRINT,PRIVATE,AWKA
4,THE SUN,2021,PRINT,PRIVATE,AWKA
5,VANGUARD NEWSPAPER,2021,PRINT,PRIVATE,AWKA
6,THE INDEPENDENT NEWSPAPER,2021,PRINT,PRIVATE,AWKA
7,TRINITAS (FAITH BASED),2021,PRINT,PRIVATE,"ARCHDIOCESE OF ONITSHA, BASILICA ONITSHA"
8,OUTLOOK NEWSPAPER (FAITH BASED),2021,PRINT,PRIVATE,NNEWI
9,THE DOVE (FAITH BASED),2021,PRINT,PRIVATE,AWKA
10,FIDES NEWSPAPER (FAITH BASED),2021,PRINT,PRIVATE,"NODU OKPUNO, AWKA SOUTH"
11,TOGETHER (FAITH BASED),2021,PRINT,PRIVATE,
12,DONAC PILOT NNEWI (FAITH BASED),2021,PRINT,PRIVATE,NNEWI
13,OUR NATION (FAITH BASED),2021,PRINT,PRIVATE,"BESIDE ALL HALLOWS SEMINARY, ONITSHA"
14,ADVOCATE NEWSPAPER,2021,PRINT,PRIVATE,
15,AUTHORITY PAPER,2021,PRINT,PRIVATE,AWKA
16,DAILY TIMES NEWSPAPER,2021,PRINT,PRIVATE,AWKA
17,DAILY TRUST,2021,PRINT,PRIVATE,AWKA
18,DATELINE NEWSPAPER,2021,PRINT,PRIVATE,AWKA
19,HALLMARK NEWSPAPER,2021,PRINT,PRIVATE,AWKA
20,NATIONAL LIGHT,2021,PRINT,PRIVATE,AWKA
21,NEW TELEGRAPH NEWSPAPER,2021,PRINT,PRIVATE,AWKA

In [16]:
new_df['year']=new_df['year'].astype(int)

new_df.head()

            media_houses  year   type category location
0  THE  NATION NEWSPAPER  2021  PRINT  PRIVATE     AWKA
1     GUARDIAN NEWSPAPER  2021  PRINT  PRIVATE     AWKA
2                  PUNCH  2021  PRINT  PRIVATE     AWKA
3     THIS DAY NEWSPAPER  2021  PRINT  PRIVATE     AWKA
4                THE SUN  2021  PRINT  PRIVATE     AWKA

In [17]:
new_df.to_excel("transposed/media_houses.xlsx", index=False)
print("Done!")

Done!