In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 197", "Table 198", "Table 199", "Table 200"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[1].head()

            LGA  NO OF REGISTERED POSTAL BOXES       IN    OUT
0        AGUATA                         4666.0  11202.0  402.0
1  ANAMBRA EAST                          200.0     10.0    0.0
2  ANAMBRA WEST                          200.0     21.0    0.0
3       ANAOCHA                         3494.0     87.0   12.0
4    AWKA NORTH                          352.0     17.0    5.0

In [4]:
columns = ['lga_id', 'year', 'no_of_register_postal_boxes', 'txn_vol_in', 'txn_vol_out']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"]) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'year': year,
                'no_of_register_postal_boxes': row["NO OF REGISTERED POSTAL BOXES"],
                'txn_vol_in': row["IN"],
                'txn_vol_out': row["OUT"]
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

TOTAL
Source: NIPOST
TOTAL
Source: NIPOST
TOTAL
Source: NIPOST
TOTAL
Source: NIPOST

C:\Users\USER\AppData\Local\Temp\ipykernel_4776\2015754982.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id  year  no_of_register_postal_boxes  txn_vol_in  txn_vol_out
0      13  2019                       4666.0     31202.0        907.0
1      18  2019                        200.0        18.0          0.0
2       2  2019                        200.0        21.0          0.0
3       9  2019                       3494.0       287.0         72.0
4      15  2019                        352.0       117.0          5.0
5      20  2019                       3916.0     48569.0       1207.0
6       6  2019                          0.0         0.0          0.0
7      12  2019                        998.0      1112.0         37.0
8      17  2019                        784.0       702.0         22.0
9       8  2019                       1098.0      1908.0         69.0
10      3  2019                        868.0       985.0         45.0
11     16  2019                       1020.0      2016.0         89.0
12     11  2019                       1525.0       308.0         75.0
13     10  2019                       3176.0      1989.0        108.0
14      4  2019                       1240.0       808.0         48.0
15     19  2019                        424.0        57.0          2.0
16     14  2019                      12500.0     51389.0       1205.0
17      1  2019                       9408.0      2137.0        132.0
18      7  2019                        680.0       307.0         15.0
19     21  2019                        898.0       589.0         36.0
20      5  2019                        890.0       795.0         36.0
21     13  2020                       4666.0     11202.0        402.0

In [5]:
new_df['no_of_register_postal_boxes']=new_df['no_of_register_postal_boxes'].astype(int)
new_df['txn_vol_in']=new_df['txn_vol_in'].astype(int)
new_df['txn_vol_out']=new_df['txn_vol_out'].astype(int)

new_df.head()

  lga_id  year  no_of_register_postal_boxes  txn_vol_in  txn_vol_out
0     13  2019                         4666       31202          907
1     18  2019                          200          18            0
2      2  2019                          200          21            0
3      9  2019                         3494         287           72
4     15  2019                          352         117            5

In [7]:
new_df.to_excel("transposed/registered_postal_boxes.xlsx", index=False)
print("Done!")

Done!