In [1]:
import pandas as pd

In [4]:
sheets = ["Table 201"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [5]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,REVENUE TYPE,2019,2020,2021,2022
0,SALES OF STAMP,3840850.00,2871200.00,3512550.00,458650.00
1,SHARE FROM PARCELS RECEIVED FROM OTHER COUNTRIES,0.00,0.00,0.00,87500.00
2,POSTAL CLEARANCE,58500.00,22250.00,70550.00,38250.00
3,DELIVERY FEES,17650.00,5600.00,32900.00,17500.00
4,OTHER REVENUE,28423171.43,16086768.34,32020481.66,63602221.25

In [6]:
columns = ['revenue_type', 'year', 'revenue']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    for index, row in df.iterrows():
        for col in df.columns[1:]:
            transformed_data = [{
                'revenue_type': row['REVENUE TYPE'],
                'year': col,
                'revenue': row[col]
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_3148\558932950.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

                                        revenue_type  year      revenue
0                                     SALES OF STAMP  2019   3840850.00
1                                     SALES OF STAMP  2020   2871200.00
2                                     SALES OF STAMP  2021   3512550.00
3                                     SALES OF STAMP  2022    458650.00
4   SHARE FROM PARCELS RECEIVED FROM OTHER COUNTRIES  2019         0.00
5   SHARE FROM PARCELS RECEIVED FROM OTHER COUNTRIES  2020         0.00
6   SHARE FROM PARCELS RECEIVED FROM OTHER COUNTRIES  2021         0.00
7   SHARE FROM PARCELS RECEIVED FROM OTHER COUNTRIES  2022     87500.00
8                                   POSTAL CLEARANCE  2019     58500.00
9                                   POSTAL CLEARANCE  2020     22250.00
10                                  POSTAL CLEARANCE  2021     70550.00
11                                  POSTAL CLEARANCE  2022     38250.00
12                                     DELIVERY FEES  2019     17650.00
13                                     DELIVERY FEES  2020      5600.00
14                                     DELIVERY FEES  2021     32900.00
15                                     DELIVERY FEES  2022     17500.00
16                                     OTHER REVENUE  2019  28423171.43
17                                     OTHER REVENUE  2020  16086768.34
18                                     OTHER REVENUE  2021  32020481.66
19                                     OTHER REVENUE  2022  63602221.25

In [7]:
new_df['year']=new_df['year'].astype(int)

new_df.head()

                                       revenue_type  year    revenue
0                                    SALES OF STAMP  2019  3840850.0
1                                    SALES OF STAMP  2020  2871200.0
2                                    SALES OF STAMP  2021  3512550.0
3                                    SALES OF STAMP  2022   458650.0
4  SHARE FROM PARCELS RECEIVED FROM OTHER COUNTRIES  2019        0.0

In [8]:
new_df.to_excel("transposed/revenue_from_postal_services_in_akwa.xlsx", index=False)
print("Done!")

Done!