In [1]:
import pandas as pd

In [2]:
file_name = ["data/cooperative_societies_by_type_and_lga.xlsx"]
sheets = ['Sheet1', 'Sheet2', 'Sheet3']
years=[2019, 2020, 2021]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel(file_name[0], sheet_name=sheet))

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

,LGA,POULTRY,LIVESTOCK,FISHERY,CROP,TRANSPORT,TRADING,MANUFACTURING,THRIFT/CREDIT,OIL/GAS,AGRO-PROCESSING,HOUSING
0,AGUATA,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,ANAMBRA EAST,1.0,0.0,0.0,19.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0
2,ANAMBRA WEST,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ANAOCHA,1.0,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,AWKA NORTH,2.0,0.0,0.0,30.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [4]:
lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [5]:
# In the ways of the old masters
# LordMokuTLE
columns = ['lga_id', 'year', 'type', 'num_of_cooperative_societies']
new_df = pd.DataFrame(columns=columns)
for i, df in enumerate(dfs):
    map_values = dict(zip(lga_df['lga_name'], lga_df['lga_id']))
    # print(map_values)
    df['year']=years[i]
    df.rename(columns={'LGA':'lga_id'}, inplace=True)
    df['lga_id'] = df['lga_id'].astype(str).map(lambda x: map_values.get(x.strip().upper())).astype(int)
    mdf = pd.melt(df, id_vars=['lga_id', 'year'], var_name='type', value_name='num_of_cooperative_societies')
    new_df = pd.concat([new_df, mdf], ignore_index=True)

new_df.head(50)

C:\Users\USER\AppData\Local\Temp\ipykernel_5544\711894419.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, mdf], ignore_index=True)

   lga_id  year       type  num_of_cooperative_societies
0      13  2019    POULTRY                           0.0
1      18  2019    POULTRY                           1.0
2       2  2019    POULTRY                           0.0
3       9  2019    POULTRY                           1.0
4      15  2019    POULTRY                           2.0
5      20  2019    POULTRY                           7.0
6       6  2019    POULTRY                           0.0
7      12  2019    POULTRY                           0.0
8      17  2019    POULTRY                           0.0
9       8  2019    POULTRY                           0.0
10      3  2019    POULTRY                           2.0
11     16  2019    POULTRY                           0.0
12     11  2019    POULTRY                           1.0
13     10  2019    POULTRY                           0.0
14      4  2019    POULTRY                           0.0
15     19  2019    POULTRY                           0.0
16     14  2019    POULTRY                           0.0
17      1  2019    POULTRY                           0.0
18     21  2019    POULTRY                           3.0
19      7  2019    POULTRY                           0.0
20      5  2019    POULTRY                           0.0
21     13  2019  LIVESTOCK                           0.0
22     18  2019  LIVESTOCK                           0.0
23      2  2019  LIVESTOCK                           0.0
24      9  2019  LIVESTOCK                           2.0
25     15  2019  LIVESTOCK                           0.0
26     20  2019  LIVESTOCK                           2.0
27      6  2019  LIVESTOCK                           0.0
28     12  2019  LIVESTOCK                           0.0
29     17  2019  LIVESTOCK                           0.0
30      8  2019  LIVESTOCK                           0.0
31      3  2019  LIVESTOCK                           2.0
32     16  2019  LIVESTOCK                           0.0
33     11  2019  LIVESTOCK                           2.0
34     10  2019  LIVESTOCK                           0.0
35      4  2019  LIVESTOCK                           1.0
36     19  2019  LIVESTOCK                           0.0
37     14  2019  LIVESTOCK                           0.0
38      1  2019  LIVESTOCK                           0.0
39     21  2019  LIVESTOCK                           3.0
40      7  2019  LIVESTOCK                           0.0
41      5  2019  LIVESTOCK                           0.0
42     13  2019    FISHERY                           0.0
43     18  2019    FISHERY                           0.0
44      2  2019    FISHERY                           0.0
45      9  2019    FISHERY                           0.0
46     15  2019    FISHERY                           0.0
47     20  2019    FISHERY                           2.0
48      6  2019    FISHERY                           0.0
49     12  2019    FISHERY                           0.0

In [7]:
new_df.head()

  lga_id  year     type  num_of_cooperative_societies
0     13  2019  POULTRY                             0
1     18  2019  POULTRY                             1
2      2  2019  POULTRY                             0
3      9  2019  POULTRY                             1
4     15  2019  POULTRY                             2

In [9]:
new_df['num_of_cooperative_societies'] = new_df['num_of_cooperative_societies'].astype(int)

new_df.to_excel("transposedb/cooperative_societies_by_type_and_lga.xlsx", index=False)
print("Done with transfromation!")

Done with transfromation!