In [71]:
import pandas as pd

In [72]:
file_names = ["data/markets_in_anambra.xlsx"]

dfs = []
for index, file_name in enumerate(file_names):
    dfs.append(pd.read_excel(file_name, sheet_name="Sheet1"))

In [73]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL', '-'], 0, inplace=True)

dfs[0].head()

   NO       NAME OF MARKET       TOWN           LGA OWNERSHIP
0   1      Etawa Ekwulobia  Ekwulobia        Aguata      Govt
1   2  Nkwo Itawa Igboukwu   Igboukwu        Aguata     Govt.
2   3      Nkwo Umunze Mkt     Umunze  Orumba south     Govt.
3   4          Oye Uga Mkt        Uga        Aguata     Govt.
4   5      Eke Oko Traders        Oko  Orumba north     Govt.

In [74]:
lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [75]:
columns = ['name', 'town', 'lga_id', 'ownership']
df = dfs[0]
df.drop('NO', axis=1, inplace=True)
df.columns = columns
map_values = dict(zip(lga_df['lga_name'], lga_df['lga_id']))
# print(map_values)

df['lga_id'] = df['lga_id'].astype(str).map(lambda x: map_values.get(x.strip().upper())).astype(int)

df.tail(50)

,name,town,lga_id,ownership
52,"Electrical Market, Nnewi",Nnewi,10,Private
53,Fairly Used Motor Parts Dealer,Nnewi,10,Govt.
54,Ogbaru Main Market,Ogbaru,19,Govt.
55,Ogboefere,Ogbaru,19,Private
56,"Electronics Market, Ogbaru",Ogbaru,19,Private
57,Ogbaru Plastics Market,Ogbaru,19,Private
58,Ahia Coke,Ogbaru,19,Private
59,"Old Motors Parts, Mgbuka Amazu",Okpoko,19,Private
60,"Iron Dealers Market, Atani Road",Ogbaru,19,Private
61,New Motor Cycle Spare Parts,Ogbaru,19,Private
62,Okolo Ichida Estate,Ogbaru,19,Private
63,Osha/Odekpe Plastics Market,Ogbaru,19,Private
64,Fruits and Vegetables Market,Ogbaru,19,Govt.
65,Nkwo Okija,Okija,16,Govt.
66,BOMSPD,Nnewi,10,Govt.
67,Abada International Market,Onitsha,1,Private
68,Onitsha Main Market,Onitsha,14,Govt.
69,Bridge Head Market,Onitsha,1,Govt.
70,Freedom Market,Onitsha,14,Govt.
71,GBO Market,Onitsha,14,Private
72,Independent Market,Onitsha,14,Govt.
73,Marine Modern Market,Onitsha,14,Private
74,Millennium Merchants and Importers Market,Onitsha,14,Private
75,Nwugo Beer Market,Onitsha,1,Private
76,Ochanja Central Market,Onitsha,1,Govt.
77,Ochanja & Environs,Onitsha,1,Private
78,Onitsha South Shop Owners,Onitsha,1,Private
79,Ose Okwodu Market,Onitsha,14,Govt.
80,Progress Market,Onitsha,14,Govt.
81,Artisan Onitsha,Onitsha,14,Private
82,Onitsha Aluminum Allied,Onitsha,14,Private
83,Stationeries & Computers Dealers,Onitsha,14,Private
84,"Bida Market, Onitsha",Onitsha,14,Private
85,Fishing Material Market,Onitsha,14,Private
86,Onitsha Printing Papers Dealers,Onitsha,14,Govt.
87,Madueke Article Market,Onitsha,1,Private
88,Onitsha Sokoto Road Traders,Onitsha,14,Private
89,Haruna Traders,Onitsha,14,Private
90,Ifejirika Market,Onitsha,14,Private
91,Ogbogwu Market,Onitsha,1,Govt.
92,Onitsha Photographic Dealers Association Onitsha,Onitsha,14,Private
93,"Plastic Market,Ogbunike",Ogbunike,5,Private
94,"Plywood Market, Ogbunike",Ogbunike,5,Private
95,"Cosmetics /Provisions Market, Ogbunike",Ogbunike,5,Private
96,Shoe Manufacturing Ogbunike,Ogbunike,5,Govt.
97,Building Materials Market Ogidi,Ogidi,8,Private
98,Nkwo Awkuzu Market,Awkuzu,5,Govt.
99,Otuocha Market,Otuocha,18,Govt.
100,Afor Igwe Market,Umudioka,12,Govt.
101,Aguleri Timber Market,Aguleri,18,Private

In [76]:
df.to_excel("transposedb/markets_in_anambra.xlsx", index=False)
print("Done with transfromation!")

Done with transfromation!