In [1]:
import pandas as pd

In [2]:
years = [2022]
sheets = ["Table 98"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [6]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

,LGA,ASTRAZENCA 1st Dose,ASTRAZENCA 2nd Dose,MODENA 1st Dose,MODENA 2nd Dose,PFIZER 1st Dose,PFIZER 2nd Dose,JOHNSON 1st Dose,JOHNSON Booster Dose
0,AGUATA,5690.0,1879.0,3233.0,1287.0,34973.0,9322.0,116852.0,7534.0
1,ANAMBRA EAST,472.0,485.0,1839.0,700.0,2300.0,1046.0,54728.0,5093.0
2,ANAMBRA WEST,401.0,230.0,1526.0,810.0,1781.0,335.0,14365.0,103.0
3,ANAOCHA,973.0,786.0,2925.0,1491.0,10038.0,3382.0,48722.0,6821.0
4,AWKA NORTH,631.0,1399.0,2628.0,1975.0,2887.0,1188.0,33411.0,56.0

In [11]:
columns = ['lga_id', 'year', 'manufacturer', 'dose', 'vaccine_count']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'manufacturer': ' '.join(col.split()[:1]),
                    'dose': ' '.join(col.split()[1:]),
                    'vaccine_count': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_13004\3124117702.py:22: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

TOTAL
Source: Source: Anambra State Ministry of Health

   lga_id  year manufacturer          dose  vaccine_count
0      13  2022   ASTRAZENCA      1st Dose         5690.0
1      13  2022   ASTRAZENCA      2nd Dose         1879.0
2      13  2022       MODENA      1st Dose         3233.0
3      13  2022       MODENA      2nd Dose         1287.0
4      13  2022       PFIZER      1st Dose        34973.0
5      13  2022       PFIZER      2nd Dose         9322.0
6      13  2022      JOHNSON      1st Dose       116852.0
7      13  2022      JOHNSON  Booster Dose         7534.0
8      18  2022   ASTRAZENCA      1st Dose          472.0
9      18  2022   ASTRAZENCA      2nd Dose          485.0
10     18  2022       MODENA      1st Dose         1839.0
11     18  2022       MODENA      2nd Dose          700.0
12     18  2022       PFIZER      1st Dose         2300.0
13     18  2022       PFIZER      2nd Dose         1046.0
14     18  2022      JOHNSON      1st Dose        54728.0
15     18  2022      JOHNSON  Booster Dose         5093.0
16      2  2022   ASTRAZENCA      1st Dose          401.0
17      2  2022   ASTRAZENCA      2nd Dose          230.0
18      2  2022       MODENA      1st Dose         1526.0
19      2  2022       MODENA      2nd Dose          810.0
20      2  2022       PFIZER      1st Dose         1781.0
21      2  2022       PFIZER      2nd Dose          335.0

In [12]:
print("len", len(new_df['dose'].unique()))
sorted(new_df['dose'].unique())

len 3

['1st Dose', '2nd Dose', 'Booster Dose']

In [13]:
new_df['vaccine_count']=new_df['vaccine_count'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year manufacturer      dose  vaccine_count
0     13  2022   ASTRAZENCA  1st Dose           5690
1     13  2022   ASTRAZENCA  2nd Dose           1879
2     13  2022       MODENA  1st Dose           3233
3     13  2022       MODENA  2nd Dose           1287
4     13  2022       PFIZER  1st Dose          34973

In [14]:
new_df.to_excel("transposed/covid19_vaccines.xlsx", index=False)
print("Finished!")

Finished!