In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 90", "Table 91", "Table 92", "Table 93"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,Adolescent Deliveries (10-19 years),Decision in Seeking Care < 24 hours,Deliveries,Deliveries - Caesarian Section,Deliveries - HIV positive women,Deliveries - HIV positive women (Booked),Deliveries - HIV positive women (Unbooked),Deliveries - Normal,Deliveries Assisted,Deliveries by Skilled Birth Attendants (SBA),Deliveries monitored using a partograph,Deliveries with complications - mother only,Live birth by HIV positive women
0,AGUATA,23,331.0,541,50.0,18.0,18.0,0.0,566,11.0,1007,507,21.0,18.0
1,ANAMBRA EAST,20,5.0,349,19.0,11.0,9.0,5.0,637,105.0,794,215,11.0,11.0
2,ANAMBRA WEST,6,2.0,32,11.0,0.0,1.0,0.0,105,58.0,117,53,9.0,1.0
3,ANAOCHA,9,19.0,435,36.0,17.0,15.0,3.0,661,2.0,1068,488,5.0,17.0
4,AWKA NORTH,2,10.0,137,15.0,6.0,4.0,1.0,441,36.0,485,191,15.0,5.0

In [4]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_2012\1883267797.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

TOTAL
TOTAL
TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health

   lga_id  year                                    data_point   value
0      13  2019                Deliveries - Caesarian Section   135.0
1      13  2019               Deliveries - HIV positive women    16.0
2      13  2019      Deliveries - HIV positive women (Booked)    11.0
3      13  2019    Deliveries - HIV positive women (Unbooked)     3.0
4      13  2019                           Deliveries - Normal  1113.0
5      13  2019                           Deliveries Assisted    27.0
6      13  2019  Deliveries by Skilled Birth Attendants (SBA)  1191.0
7      13  2019       Deliveries monitored using a partograph   536.0
8      13  2019   Deliveries with complications - mother only    17.0
9      13  2019              Live birth by HIV positive women    16.0
10     18  2019                Deliveries - Caesarian Section    83.0
11     18  2019               Deliveries - HIV positive women    25.0
12     18  2019      Deliveries - HIV positive women (Booked)    14.0
13     18  2019    Deliveries - HIV positive women (Unbooked)    10.0
14     18  2019                           Deliveries - Normal   898.0
15     18  2019                           Deliveries Assisted   843.0
16     18  2019  Deliveries by Skilled Birth Attendants (SBA)   886.0
17     18  2019       Deliveries monitored using a partograph   128.0
18     18  2019   Deliveries with complications - mother only     8.0
19     18  2019              Live birth by HIV positive women    22.0
20      2  2019                Deliveries - Caesarian Section    11.0
21      2  2019               Deliveries - HIV positive women     1.0

In [6]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 14

array(['Deliveries - Caesarian Section',
       'Deliveries - HIV positive women',
       'Deliveries - HIV positive women (Booked)',
       'Deliveries - HIV positive women (Unbooked)',
       'Deliveries - Normal', 'Deliveries Assisted',
       'Deliveries by Skilled Birth Attendants (SBA)',
       'Deliveries monitored using a partograph',
       'Deliveries with complications - mother only',
       'Live birth by HIV positive women',
       'Adolescent Deliveries (10-19 years)',
       'Decision in Seeking Care < 24 hours', 'Deliveries',
       'Deliveries by Skilled Birth Attendants'], dtype=object)

In [7]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                                  data_point  value
0     13  2019              Deliveries - Caesarian Section    135
1     13  2019             Deliveries - HIV positive women     16
2     13  2019    Deliveries - HIV positive women (Booked)     11
3     13  2019  Deliveries - HIV positive women (Unbooked)      3
4     13  2019                         Deliveries - Normal   1113

In [8]:
new_df.to_excel("transposed/deliveries_cases.xlsx", index=False)
print("Finished!")

Finished!