In [1]:
import pandas as pd

In [4]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 99", "Table 100", "Table 101", "Table 102"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [5]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

,LGA,FORMAL/PUBLIC SECTOR MALE,FORMAL/PUBLIC SECTOR FEMALE,FORMAL/PUBLIC SECTOR DEPENDENTS MALE,FORMAL/PUBLIC SECTOR DEPENDENTS FEMALE,INFORMAL/PRIVATE SECTOR MALE,INFORMAL/PRIVATE SECTOR FEMALE,INFORMAL/PRIVATE SECTOR TISHIP MALE,INFORMAL/PRIVATE SECTOR TISHIP FEMALE,INFORMAL/PRIVATE SECTOR ADOPTION MODEL MALE,INFORMAL/PRIVATE SECTOR ADOPTION MODEL FEMALE
0,AGUATA,167.0,1306.0,1587.0,850.0,103.0,228.0,43.0,106.0,0.0,0.0
1,ANAMBRA EAST,213.0,609.0,970.0,580.0,167.0,138.0,37.0,54.0,0.0,0.0
2,ANAMBRA WEST,175.0,226.0,526.0,315.0,61.0,176.0,15.0,28.0,0.0,0.0
3,ANAOCHA,194.0,1426.0,1925.0,1005.0,37.0,86.0,34.0,82.0,0.0,0.0
4,AWKA NORTH,70.0,394.0,584.0,308.0,25.0,66.0,10.0,27.0,0.0,0.0

In [ ]:
columns = ['lga_id', 'year', 'sector', 'model', 'gender', 'num_of_enrolees']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                a, b = col.split("SECTOR")
                # print(a, b)
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'sector': a.strip(),
                    'model': ' '.join(b.split()[:-1]),
                    'gender': b.split()[-1],
                    'num_of_enrolees': row[col],
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_12196\559008149.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

OTHER STATES
TOTAL
Source: Anambra State Health Insurance Agency
OTHER STATES
TOTAL
Source: Anambra State Health Insurance Agency
OTHER STATES
TOTAL
Source: Anambra State Health Insurance Agency
OTHER STATES
TOTAL
Source: Anambra State Health Insurance Agency

   lga_id  year            sector           model  gender  num_of_enrolees
0      13  2019     FORMAL/PUBLIC                    MALE            167.0
1      13  2019     FORMAL/PUBLIC                  FEMALE           1306.0
2      13  2019     FORMAL/PUBLIC      DEPENDENTS    MALE           1587.0
3      13  2019     FORMAL/PUBLIC      DEPENDENTS  FEMALE            850.0
4      13  2019  INFORMAL/PRIVATE                    MALE            103.0
5      13  2019  INFORMAL/PRIVATE                  FEMALE            228.0
6      13  2019  INFORMAL/PRIVATE          TISHIP    MALE             43.0
7      13  2019  INFORMAL/PRIVATE          TISHIP  FEMALE            106.0
8      13  2019  INFORMAL/PRIVATE  ADOPTION MODEL    MALE              0.0
9      13  2019  INFORMAL/PRIVATE  ADOPTION MODEL  FEMALE              0.0
10     18  2019     FORMAL/PUBLIC                    MALE            213.0
11     18  2019     FORMAL/PUBLIC                  FEMALE            609.0
12     18  2019     FORMAL/PUBLIC      DEPENDENTS    MALE            970.0
13     18  2019     FORMAL/PUBLIC      DEPENDENTS  FEMALE            580.0
14     18  2019  INFORMAL/PRIVATE                    MALE            167.0
15     18  2019  INFORMAL/PRIVATE                  FEMALE            138.0
16     18  2019  INFORMAL/PRIVATE          TISHIP    MALE             37.0
17     18  2019  INFORMAL/PRIVATE          TISHIP  FEMALE             54.0
18     18  2019  INFORMAL/PRIVATE  ADOPTION MODEL    MALE              0.0
19     18  2019  INFORMAL/PRIVATE  ADOPTION MODEL  FEMALE              0.0
20      2  2019     FORMAL/PUBLIC                    MALE            175.0
21      2  2019     FORMAL/PUBLIC                  FEMALE            226.0

In [ ]:
# print("len", len(new_df['dose'].unique()))
# sorted(new_df['dose'].unique())

len 3

['1st Dose', '2nd Dose', 'Booster Dose']

In [10]:
new_df['num_of_enrolees']=new_df['num_of_enrolees'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year            sector       model  gender  num_of_enrolees
0     13  2019     FORMAL/PUBLIC                MALE              167
1     13  2019     FORMAL/PUBLIC              FEMALE             1306
2     13  2019     FORMAL/PUBLIC  DEPENDENTS    MALE             1587
3     13  2019     FORMAL/PUBLIC  DEPENDENTS  FEMALE              850
4     13  2019  INFORMAL/PRIVATE                MALE              103

In [11]:
new_df.to_excel("transposed/enrolees_in_ashia.xlsx", index=False)
print("done!")

done!