In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 50", "Table 51", "Table 52", "Table 53"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,TEACHING HOSPITAL,GENERAL HOSPITALS,PRIMARY HEALTH CENTRE,PRIVATE PRIMARY FACILITY,PRIVATE SECONDARY FACILITY
0,AGUATA,0.0,4,40,6,102
1,ANAMBRA EAST,0.0,1,27,5,10
2,ANAMBRA WEST,0.0,1,21,0,2
3,ANAOCHA,0.0,4,30,10,35
4,AWKA NORTH,0.0,2,25,5,15

In [7]:
columns = ['lga_id', 'establishment', 'year', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'establishment': "TEACHING HOSPITAL",
                'year': year,
                'population': row["TEACHING HOSPITAL"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'establishment': "GENERAL HOSPITAL",
                'year': year,
                'population': row["GENERAL HOSPITALS"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'establishment': "PRIMARY HEALTH CENTRE",
                'year': year,
                'population': row["PRIMARY HEALTH CENTRE"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'establishment': "PRIVATE PRIMARY FACILITY",
                'year': year,
                'population': row["PRIVATE PRIMARY FACILITY"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'establishment': "PRIVATE SECONDARY FACILITY",
                'year': year,
                'population': row["PRIVATE SECONDARY FACILITY"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_17324\2074693105.py:40: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id               establishment  year  population
0      13           TEACHING HOSPITAL  2019         0.0
1      13            GENERAL HOSPITAL  2019         4.0
2      13       PRIMARY HEALTH CENTRE  2019        40.0
3      13    PRIVATE PRIMARY FACILITY  2019         6.0
4      13  PRIVATE SECONDARY FACILITY  2019       102.0
5      18           TEACHING HOSPITAL  2019         0.0
6      18            GENERAL HOSPITAL  2019         1.0
7      18       PRIMARY HEALTH CENTRE  2019        27.0
8      18    PRIVATE PRIMARY FACILITY  2019         5.0
9      18  PRIVATE SECONDARY FACILITY  2019        10.0
10      2           TEACHING HOSPITAL  2019         0.0
11      2            GENERAL HOSPITAL  2019         1.0
12      2       PRIMARY HEALTH CENTRE  2019        21.0
13      2    PRIVATE PRIMARY FACILITY  2019         0.0
14      2  PRIVATE SECONDARY FACILITY  2019         2.0
15      9           TEACHING HOSPITAL  2019         0.0
16      9            GENERAL HOSPITAL  2019         4.0
17      9       PRIMARY HEALTH CENTRE  2019        30.0
18      9    PRIVATE PRIMARY FACILITY  2019        10.0
19      9  PRIVATE SECONDARY FACILITY  2019        35.0
20     15           TEACHING HOSPITAL  2019         0.0
21     15            GENERAL HOSPITAL  2019         2.0

In [8]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id               establishment  year  population
0     13           TEACHING HOSPITAL  2019           0
1     13            GENERAL HOSPITAL  2019           4
2     13       PRIMARY HEALTH CENTRE  2019          40
3     13    PRIVATE PRIMARY FACILITY  2019           6
4     13  PRIVATE SECONDARY FACILITY  2019         102

In [9]:
new_df.to_excel("establishments_by_category.xlsx", index=False)
print("Done!")

Done!