In [1]:
import pandas as pd

In [6]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 86", "Table 87", "Table 88", "Table 89"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [7]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,Clients given oral pills,Clients that received Condoms,Condoms distributed (sachet) - male,Condoms distributed (sachet) - female,FP clients counselled,Family Planning Injections,Family Planning clients accessing HCT services,Female 15-49 years using modern contraceptives,Females using modern contraception,...,Individual referred for FP services from - PMTCT (HIV + Pregnant Women),Injectables given,New FP Acceptors,Oral pill cycle (packets),Oral pills cycle (sachets) dispensed,Persons given oral pills,Post- partum IUD inserted,Post- partum Implanon NXT inserted,Post-partum Jadelle inserted,Women counselled on Postpartum FP
0,AGUATA,337.0,3116.0,25982.0,10699.0,10778.0,1190.0,452.0,3969.0,2263.0,...,6.0,684.0,7463.0,2261.0,835.0,881.0,39.0,41.0,27.0,642.0
1,ANAMBRA EAST,452.0,1225.0,13047.0,5419.0,10776.0,1497.0,1851.0,3804.0,1897.0,...,1.0,909.0,5874.0,3014.0,1166.0,1215.0,0.0,61.0,3.0,484.0
2,ANAMBRA WEST,66.0,937.0,7474.0,3073.0,2324.0,263.0,420.0,504.0,214.0,...,0.0,277.0,1511.0,200.0,90.0,100.0,2.0,5.0,6.0,108.0
3,ANAOCHA,502.0,1285.0,18708.0,11775.0,10650.0,2620.0,943.0,4759.0,2820.0,...,0.0,1736.0,5290.0,2786.0,1098.0,1345.0,7.0,54.0,16.0,626.0
4,AWKA NORTH,169.0,766.0,9172.0,3648.0,4711.0,1051.0,60.0,1717.0,841.0,...,0.0,513.0,2564.0,963.0,263.0,570.0,0.0,2.0,0.0,67.0

In [8]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_15992\1883267797.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL

   lga_id  year                                         data_point    value
0      13  2019              Condoms distributed (sachet) - female   1855.0
1      13  2019                Condoms distributed (sachet) - male  36993.0
2      13  2019                              FP clients counselled   7920.0
3      13  2019                         Family Planning Injections   1322.0
4      13  2019     Family Planning clients accessing HCT services   1538.0
5      13  2019     Female 15-49 years using modern contraceptives   5221.0
6      13  2019                                      IUCD inserted    286.0
7      13  2019                                            Implant    640.0
8      13  2019  Individual referred for FP services from - ART...    204.0
9      13  2019  Individual referred for FP services from - PMT...      1.0
10     13  2019       Individual referred for FP services from HCT    318.0
11     13  2019                                   New FP Acceptors   4231.0
12     13  2019                          Oral pill cycle (packets)   1002.0
13     13  2019                           Persons given oral pills    542.0
14     18  2019              Condoms distributed (sachet) - female   5201.0
15     18  2019                Condoms distributed (sachet) - male  41173.0
16     18  2019                              FP clients counselled   8514.0
17     18  2019                         Family Planning Injections   1333.0
18     18  2019     Family Planning clients accessing HCT services   1324.0
19     18  2019     Female 15-49 years using modern contraceptives   3987.0
20     18  2019                                      IUCD inserted     18.0
21     18  2019                                            Implant    610.0

In [10]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 28

array(['Condoms distributed (sachet) - female',
       'Condoms distributed (sachet) - male', 'FP clients counselled',
       'Family Planning Injections',
       'Family Planning clients accessing HCT services',
       'Female 15-49 years using modern contraceptives', 'IUCD inserted',
       'Implant',
       'Individual referred for FP services from - ART (ART Refill)',
       'Individual referred for FP services from - PMTCT (HIV + Pregnant Women)',
       'Individual referred for FP services from HCT', 'New FP Acceptors',
       'Oral pill cycle (packets)', 'Persons given oral pills',
       'Clients given oral pills', 'Clients that received Condoms',
       'Females using modern contraception', 'IUD inserted',
       'Implants inserted', 'Injectables given',
       'Oral pills cycle (sachets) dispensed',
       'Post- partum IUD inserted', 'Post- partum Implanon NXT inserted',
       'Post-partum Jadelle inserted',
       'Women counselled on Postpartum FP', 'Condoms distributed',
       'Post-partum IUD inserted', 'Post-partum Implanon NXT inserted'],
      dtype=object)

In [11]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                                      data_point  value
0     13  2019           Condoms distributed (sachet) - female   1855
1     13  2019             Condoms distributed (sachet) - male  36993
2     13  2019                           FP clients counselled   7920
3     13  2019                      Family Planning Injections   1322
4     13  2019  Family Planning clients accessing HCT services   1538

In [12]:
new_df.to_excel("transposed/family_planning_indices.xlsx", index=False)
print("Finished!")

Finished!