In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 70", "Table 71", "Table 72", "Table 73"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

                                      CADRE  PUBLIC FEMALE  PUBLIC MALE
0               Administrative Professional            475          242
1                          Dental Therapist              5            1
2                                   Dentist              5            4
3              Medical Laboratory Assistant              2            0
4  Junior Community Health Extension Worker            102            6

In [6]:
columns = ['year', 'cadre', 'gender', 'hospital_type', 'workforce']

new_df = pd.DataFrame(columns=columns)
ref = {
    'PUBLIC MALE' : {
        'gender': 'Male',
        'hospital_type': 'Public',
        },
    'PUBLIC FEMALE' : {
        'gender': 'Female',
        'hospital_type': 'Public',
        },
    'NAUTH MALE' : {
        'gender': 'Male',
        'hospital_type': 'Nauth',
        },
    'NAUTH FEMALE' : {
        'gender': 'Female',
        'hospital_type': 'Nauth',
        },
    'PRIVATE MALE' : {
        'gender': 'Male',
        'hospital_type': 'Private',
        },
    'PRIVATE FEMALE' : {
        'gender': 'Female',
        'hospital_type': 'Private',
        },
}

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        for col in df.columns[1:]:
            transformed_data = [{
                'year': year,
                'cadre': row['CADRE'],
                'gender': ref[col]['gender'],
                'hospital_type': ref[col]['hospital_type'],
                'workforce': row[col],
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,year,cadre,gender,hospital_type,workforce
0,2019,Administrative Professional,Female,Public,475
1,2019,Administrative Professional,Male,Public,242
2,2019,Dental Therapist,Female,Public,5
3,2019,Dental Therapist,Male,Public,1
4,2019,Dentist,Female,Public,5
5,2019,Dentist,Male,Public,4
6,2019,Medical Laboratory Assistant,Female,Public,2
7,2019,Medical Laboratory Assistant,Male,Public,0
8,2019,Junior Community Health Extension Worker,Female,Public,102
9,2019,Junior Community Health Extension Worker,Male,Public,6
10,2019,Community Health Extension Worker,Female,Public,533
11,2019,Community Health Extension Worker,Male,Public,16
12,2019,Optometrist,Female,Public,11
13,2019,Optometrist,Male,Public,14
14,2019,Physiotherapist,Female,Public,15
15,2019,Physiotherapist,Male,Public,8
16,2019,Medical Laboratory Scientist,Female,Public,79
17,2019,Medical Laboratory Scientist,Male,Public,38
18,2019,Prosthetic & Orthotic,Female,Public,0
19,2019,Prosthetic & Orthotic,Male,Public,1
20,2019,Community Health Officer,Female,Public,111
21,2019,Community Health Officer,Male,Public,29

In [7]:
print("len", len(new_df['cadre'].unique()))
new_df['cadre'].unique()

len 28

array(['Administrative Professional', 'Dental Therapist', 'Dentist',
       'Medical Laboratory Assistant',
       'Junior Community Health Extension Worker',
       'Community Health Extension Worker', 'Optometrist',
       'Physiotherapist', 'Medical Laboratory Scientist',
       'Prosthetic & Orthotic', 'Community Health Officer', 'Nurse',
       'Midwife', 'Medical Laboratory Technician',
       'Medical Specialist - Psychiatry', 'Dental Health Technician',
       'Environment Health Officer', 'Medical Doctor',
       'Financial Professional', 'Health Records Officer',
       'Health Professional Associate', 'Pharmacist',
       'Pharmacy Technician', 'Radiographer', 'Records Technician',
       'Community Health Technician', 'Dietitian', 'Paediatrist'],
      dtype=object)

In [9]:
new_df['workforce']=new_df['workforce'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

   year                        cadre  gender hospital_type  workforce
0  2019  Administrative Professional  Female        Public        475
1  2019  Administrative Professional    Male        Public        242
2  2019             Dental Therapist  Female        Public          5
3  2019             Dental Therapist    Male        Public          1
4  2019                      Dentist  Female        Public          5

In [10]:
new_df.to_excel("transposed/health_workforce_by_cadre.xlsx", index=False)
print("Done!")

Done!