In [1]:
import pandas as pd

In [17]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 66", "Table 67", "Table 68", "Table 69"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [18]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,BCG given,Conjugate A CSM Vaccine given,OPV 3 doses given,OPV 2 doses given,PCV 2 doses given,PCV 3 doses given,Fully Immunized < 1 year,Hep. B 0 birth,Hepatitis B Vaccine 1,...,Rota 2 given,Rota 3 given,Tetanus Toxoid Dose 1,Tetanus Toxoid Dose 3,Tetanus Toxoid Dose 2,Tetanus Toxoid Dose 4,Tetanus Toxoid Dose 5,Vitamin A given,Yellow Fever given,Yellow Fever Vaccine given
0,AGUATA,13113.0,7885.0,13604.0,11205.0,11383.0,13890.0,12633.0,7660.0,0.0,...,56.0,30.0,5996.0,1204.0,4583.0,145.0,56.0,3720.0,5040.0,8407.0
1,ANAMBRA EAST,7644.0,4347.0,6089.0,5206.0,5339.0,6320.0,7322.0,3980.0,0.0,...,69.0,47.0,2517.0,331.0,1911.0,31.0,0.0,2762.0,2748.0,4839.0
2,ANAMBRA WEST,2009.0,845.0,1941.0,1892.0,1886.0,1955.0,1921.0,1048.0,0.0,...,0.0,0.0,755.0,131.0,501.0,36.0,4.0,762.0,866.0,1031.0
3,ANAOCHA,10640.0,5815.0,8349.0,6062.0,6720.0,9294.0,3372.0,8152.0,0.0,...,8.0,52.0,4494.0,510.0,3871.0,110.0,12.0,2359.0,3546.0,6181.0
4,AWKA NORTH,4444.0,1950.0,4369.0,3968.0,4049.0,4417.0,3539.0,2992.0,0.0,...,15.0,0.0,2414.0,416.0,1695.0,111.0,6.0,2808.0,1101.0,2719.0

In [19]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_15912\1883267797.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health

   lga_id  year                     data_point   value
0      13  2019                      BCG given  6986.0
1      13  2019        EPI - OPV 0 doses given  2952.0
2      13  2019  Conjugate A CSM Vaccine given   556.0
3      13  2019              OPV 3 doses given  5597.0
4      13  2019              OPV 2 doses given  4326.0
5      13  2019              PCV 3 doses given  5588.0
6      13  2019              PCV 2 doses given  4399.0
7      13  2019       Fully Immunized < 1 year  6862.0
8      13  2019                 Hep. B 0 birth  3817.0
9      13  2019                  Hepatitis B 2     0.0
10     13  2019    Hepatitis B Vaccine 1 given     0.0
11     13  2019                    IPV 1 given  6216.0
12     13  2019                Measles 1 given  6984.0
13     13  2019                Measles 2 given  2942.0
14     13  2019                    OPV 1 given  6484.0
15     13  2019                    PCV 1 given  6360.0
16     13  2019                  Penta 1 given  6394.0
17     13  2019                  Penta 2 given  4321.0
18     13  2019                  Penta 3 given  5601.0
19     13  2019     Yellow Fever Vaccine given  7017.0
20     13  2019          Tetanus Toxoid Dose 1  3321.0
21     13  2019          Tetanus Toxoid Dose 2  2523.0

In [21]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 39

array(['BCG given', 'EPI - OPV 0 doses given',
       'Conjugate A CSM Vaccine given', 'OPV 3 doses given',
       'OPV 2 doses given', 'PCV 3 doses given', 'PCV 2 doses given',
       'Fully Immunized < 1 year', 'Hep. B 0 birth', 'Hepatitis B 2',
       'Hepatitis B Vaccine 1 given', 'IPV 1 given', 'Measles 1 given',
       'Measles 2 given', 'OPV 1 given', 'PCV 1 given', 'Penta 1 given',
       'Penta 2 given', 'Penta 3 given', 'Yellow Fever Vaccine given',
       'Tetanus Toxoid Dose 1', 'Tetanus Toxoid Dose 2',
       'Tetanus Toxoid Dose 3', 'Tetanus Toxoid Dose 4',
       'Tetanus Toxoid Dose 5', 'Hepatitis B Vaccine 1', 'Men A given',
       'Non-Pregnant women', 'Pregnant women given', 'Rota 1 given',
       'Rota 2 given', 'Rota 3 given', 'Vitamin A given',
       'Yellow Fever given', 'OPV 0 doses given',
       'EPI - PCV 3 doses given', 'IPV 2 given',
       'Pregnant women given TD vaccine',
       'Non-Pregnant women given TD vaccine'], dtype=object)

In [22]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                     data_point  value
0     13  2019                      BCG given   6986
1     13  2019        EPI - OPV 0 doses given   2952
2     13  2019  Conjugate A CSM Vaccine given    556
3     13  2019              OPV 3 doses given   5597
4     13  2019              OPV 2 doses given   4326

In [23]:
new_df.to_excel("transposed/immunization_by_type.xlsx", index=False)
print("Done!")

Done!