In [1]:
import pandas as pd

In [6]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 62", "Table 63", "Table 64", "Table 65"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [7]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,INPATIENT DAYS - TOTAL,GENERAL ATTENDANCE,OUT-PATIENT ATTENDANCE,INPATIENT DISCHARGES,PATIENTS ADMITTED
0,AGUATA,770,115220,20260,1611,1448
1,ANAMBRA EAST,246,50912,14090,474,358
2,ANAMBRA WEST,286,13677,3912,258,124
3,ANAOCHA,141,85022,28544,655,600
4,AWKA NORTH,931,26491,10300,293,163

In [9]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': col.replace("\n", " ").strip(),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year              data_point   value
0      13  2019  INPATIENT DAYS - TOTAL     465
1      13  2019      GENERAL ATTENDANCE  131322
2      13  2019  OUT-PATIENT ATTENDANCE   23321
3      13  2019    INPATIENT DISCHARGES     358
4      18  2019  INPATIENT DAYS - TOTAL     351
5      18  2019      GENERAL ATTENDANCE   39075
6      18  2019  OUT-PATIENT ATTENDANCE   10759
7      18  2019    INPATIENT DISCHARGES     448
8       2  2019  INPATIENT DAYS - TOTAL     208
9       2  2019      GENERAL ATTENDANCE   18399
10      2  2019  OUT-PATIENT ATTENDANCE    5673
11      2  2019    INPATIENT DISCHARGES     208
12      9  2019  INPATIENT DAYS - TOTAL     768
13      9  2019      GENERAL ATTENDANCE   94020
14      9  2019  OUT-PATIENT ATTENDANCE   35085
15      9  2019    INPATIENT DISCHARGES     620
16     15  2019  INPATIENT DAYS - TOTAL     442
17     15  2019      GENERAL ATTENDANCE   34940
18     15  2019  OUT-PATIENT ATTENDANCE   15238
19     15  2019    INPATIENT DISCHARGES     635
20     20  2019  INPATIENT DAYS - TOTAL    1934
21     20  2019      GENERAL ATTENDANCE  188420

In [10]:
new_df['data_point'].unique()

array(['INPATIENT DAYS - TOTAL', 'GENERAL ATTENDANCE',
       'OUT-PATIENT ATTENDANCE', 'INPATIENT DISCHARGES',
       'PATIENTS ADMITTED'], dtype=object)

In [11]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year              data_point   value
0     13  2019  INPATIENT DAYS - TOTAL     465
1     13  2019      GENERAL ATTENDANCE  131322
2     13  2019  OUT-PATIENT ATTENDANCE   23321
3     13  2019    INPATIENT DISCHARGES     358
4     18  2019  INPATIENT DAYS - TOTAL     351

In [12]:
new_df.to_excel("transposed/inpatients_and_outpatients_in_hospitals.xlsx", index=False)
print("Done!")

Done!