In [1]:
import pandas as pd

In [8]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 46", "Table 47", "Table 48", "Table 49"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [9]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,FEDERAL GOVERNMENT OWNED,STATE GOVERNMENT TEACHING HOSPITAL,STATE GOVERNMENT OWNED (GENERAL HOSPITAL),LOCAL GOVERNMENT OWNED (PHC),PRIVATE OWNED HOSPITAL
0,AGUATA,0.0,0.0,4,40,108
1,ANAMBRA EAST,0.0,0.0,1,27,15
2,ANAMBRA WEST,0.0,0.0,1,21,2
3,ANAOCHA,0.0,0.0,4,30,45
4,AWKA NORTH,0.0,0.0,2,25,20

In [10]:
columns = ['lga_id', 'ownership', 'year', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'ownership': "FEDERAL GOVERNMENT OWNED",
                'year': year,
                'population': row["FEDERAL GOVERNMENT OWNED"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'ownership': "STATE GOVERNMENT TEACHING HOSPITAL",
                'year': year,
                'population': row["STATE GOVERNMENT TEACHING HOSPITAL"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'ownership': "STATE GOVERNMENT OWNED (GENERAL HOSPITAL)",
                'year': year,
                'population': row["STATE GOVERNMENT OWNED (GENERAL HOSPITAL)"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'ownership': "LOCAL GOVERNMENT OWNED (PHC)",
                'year': year,
                'population': row["LOCAL GOVERNMENT OWNED (PHC)"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'ownership': "PRIVATE OWNED HOSPITAL",
                'year': year,
                'population': row["PRIVATE OWNED HOSPITAL"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_11296\2073565054.py:39: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id                                  ownership  year  population
0      13                   FEDERAL GOVERNMENT OWNED  2019         0.0
1      13         STATE GOVERNMENT TEACHING HOSPITAL  2019         0.0
2      13  STATE GOVERNMENT OWNED (GENERAL HOSPITAL)  2019         4.0
3      13               LOCAL GOVERNMENT OWNED (PHC)  2019        40.0
4      13                     PRIVATE OWNED HOSPITAL  2019       108.0
5      18                   FEDERAL GOVERNMENT OWNED  2019         0.0
6      18         STATE GOVERNMENT TEACHING HOSPITAL  2019         0.0
7      18  STATE GOVERNMENT OWNED (GENERAL HOSPITAL)  2019         1.0
8      18               LOCAL GOVERNMENT OWNED (PHC)  2019        27.0
9      18                     PRIVATE OWNED HOSPITAL  2019        15.0
10      2                   FEDERAL GOVERNMENT OWNED  2019         0.0
11      2         STATE GOVERNMENT TEACHING HOSPITAL  2019         0.0
12      2  STATE GOVERNMENT OWNED (GENERAL HOSPITAL)  2019         1.0
13      2               LOCAL GOVERNMENT OWNED (PHC)  2019        21.0
14      2                     PRIVATE OWNED HOSPITAL  2019         2.0
15      9                   FEDERAL GOVERNMENT OWNED  2019         0.0
16      9         STATE GOVERNMENT TEACHING HOSPITAL  2019         0.0
17      9  STATE GOVERNMENT OWNED (GENERAL HOSPITAL)  2019         4.0
18      9               LOCAL GOVERNMENT OWNED (PHC)  2019        30.0
19      9                     PRIVATE OWNED HOSPITAL  2019        45.0
20     15                   FEDERAL GOVERNMENT OWNED  2019         0.0
21     15         STATE GOVERNMENT TEACHING HOSPITAL  2019         0.0

In [11]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id                                  ownership  year  population
0     13                   FEDERAL GOVERNMENT OWNED  2019           0
1     13         STATE GOVERNMENT TEACHING HOSPITAL  2019           0
2     13  STATE GOVERNMENT OWNED (GENERAL HOSPITAL)  2019           4
3     13               LOCAL GOVERNMENT OWNED (PHC)  2019          40
4     13                     PRIVATE OWNED HOSPITAL  2019         108

In [12]:
new_df.to_excel("institutions_by_ownership.xlsx", index=False)
print("Done!")

Done!