In [2]:
import pandas as pd

In [3]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 82", "Table 83", "Table 84", "Table 85"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [4]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,Persons with confirmed uncomplicated Malaria,Malaria confirmed pregnant women,Pregnant women with clinical malaria,Children < 5 yrs who received LLIN,Persons presenting with fever & tested by RDT,Persons presenting with fever and tested by Microscopy,Persons tested positive for malaria by RDT,Persons tested positive for malaria by Microscopy,Persons with Confirmed Uncomplicated Malaria treated with ACT,Persons with Confirmed Uncomplicated Malaria treated with other antimalarials,Persons with fever,Persons Clinically diagnosed with Malaria treated with ACT,Persons with Severe Malaria treated with Artesunate injection
0,AGUATA,7334,74,4.0,28.0,7839,1080,6552,838,7388,407,8770,528.0,49.0
1,ANAMBRA EAST,6462,162,7.0,145.0,6898,1337,5540,1188,6553,40,8162,141.0,38.0
2,ANAMBRA WEST,2014,30,0.0,0.0,2318,179,1886,172,2233,117,2523,0.0,0.0
3,ANAOCHA,10757,123,0.0,0.0,10907,1784,9345,1592,10795,44,12712,7.0,27.0
4,AWKA NORTH,5001,82,21.0,46.0,6452,13,5098,4,4812,142,6507,76.0,10.0

In [5]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

TOTAL
TOTAL
TOTAL
TOTAL

   lga_id  year                                         data_point  value
0      13  2019       Persons with confirmed uncomplicated Malaria   8343
1      13  2019                   Malaria confirmed pregnant women     50
2      13  2019                 Children < 5 yrs who received LLIN    411
3      13  2019      Persons presenting with fever & tested by RDT  10127
4      13  2019  Persons presenting with fever and tested by Mi...  193.0
5      13  2019         Persons tested positive for malaria by RDT   8281
6      13  2019  Persons tested positive for malaria by Microscopy  161.0
7      13  2019  Persons with Confirmed Uncomplicated Malaria t...   8199
8      13  2019  Persons with Confirmed Uncomplicated Malaria t...  151.0
9      13  2019                                 Persons with fever  10492
10     13  2019  Persons Clinically diagnosed with Malaria trea...  113.0
11     18  2019       Persons with confirmed uncomplicated Malaria   5524
12     18  2019                   Malaria confirmed pregnant women    176
13     18  2019                 Children < 5 yrs who received LLIN   1169
14     18  2019      Persons presenting with fever & tested by RDT   7274
15     18  2019  Persons presenting with fever and tested by Mi...    0.0
16     18  2019         Persons tested positive for malaria by RDT   5525
17     18  2019  Persons tested positive for malaria by Microscopy    0.0
18     18  2019  Persons with Confirmed Uncomplicated Malaria t...   5401
19     18  2019  Persons with Confirmed Uncomplicated Malaria t...  162.0
20     18  2019                                 Persons with fever   7451
21     18  2019  Persons Clinically diagnosed with Malaria trea...    0.0

In [7]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 13

array(['Persons with confirmed uncomplicated Malaria',
       'Malaria confirmed pregnant women',
       'Children < 5 yrs who received LLIN',
       'Persons presenting with fever & tested by RDT',
       'Persons presenting with fever and tested by Microscopy',
       'Persons tested positive for malaria by RDT',
       'Persons tested positive for malaria by Microscopy',
       'Persons with Confirmed Uncomplicated Malaria treated with ACT',
       'Persons with Confirmed Uncomplicated Malaria treated with other antimalarials',
       'Persons with fever',
       'Persons Clinically diagnosed with Malaria treated with ACT',
       'Pregnant women with clinical malaria',
       'Persons with Severe Malaria treated with Artesunate injection'],
      dtype=object)

In [8]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                                         data_point  value
0     13  2019       Persons with confirmed uncomplicated Malaria   8343
1     13  2019                   Malaria confirmed pregnant women     50
2     13  2019                 Children < 5 yrs who received LLIN    411
3     13  2019      Persons presenting with fever & tested by RDT  10127
4     13  2019  Persons presenting with fever and tested by Mi...    193

In [9]:
new_df.to_excel("transposed/malaria_cases_and_treatment.xlsx", index=False)
print("Finished!")

Finished!