In [1]:
import pandas as pd

In [7]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 94", "Table 95", "Table 96", "Table 97"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [8]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,ANC 1st Visit,ANC 4th visit,ANC 8th Visit,ANC Attendance,ANC Hep. B referred,ANC Hep. B test done,ANC Hep. B test positive,ANC Hep. C Referred,ANC Hep. C test done,...,PW Counselled on FGM,PW who received Haematinics,PW who received LLIN,PW with Proteinuria,PW with Severe Anaemia,Postnatal Visit Total,Postnatal Visit within 3 days,Postnatal visits >= 7 days,Postnatal Clinic Visits,Postnatal visit within 1 day
0,AGUATA,755.0,396.0,153.0,2581.0,11.0,834.0,87.0,41.0,736.0,...,1616.0,5933.0,238.0,85.0,2.0,546.0,21.0,385.0,520.0,99.0
1,ANAMBRA EAST,739.0,263.0,187.0,1509.0,0.0,72.0,13.0,73.0,5.0,...,845.0,4227.0,317.0,11.0,87.0,1404.0,105.0,897.0,1058.0,28.0
2,ANAMBRA WEST,263.0,65.0,22.0,335.0,0.0,52.0,0.0,1.0,29.0,...,197.0,1178.0,29.0,6.0,28.0,84.0,8.0,52.0,41.0,12.0
3,ANAOCHA,728.0,324.0,51.0,2306.0,1.0,389.0,40.0,0.0,382.0,...,1156.0,6379.0,91.0,32.0,9.0,848.0,173.0,576.0,723.0,86.0
4,AWKA NORTH,582.0,79.0,71.0,898.0,0.0,119.0,0.0,5.0,54.0,...,532.0,3053.0,84.0,8.0,14.0,499.0,38.0,447.0,156.0,50.0

In [9]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_2448\1883267797.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
Source: Source: Anambra State Ministry of Health
TOTAL
TOTAL

   lga_id  year                                       data_point   value
0      13  2019                        ANC Syphilis case treated     2.0
1      13  2019                           ANC Syphilis test done   505.0
2      13  2019                       ANC Syphilis test positive     0.0
3      13  2019  Antenatal 1st (booking) visit 20 weeks or later  1470.0
4      13  2019    Antenatal 1st (booking) visit before 20 weeks   710.0
5      13  2019                              Antenatal 4th Visit   811.0
6      13  2019                       Antenatal total attendance  6818.0
7      13  2019                                            IPT1p  1299.0
8      13  2019                                            IPT2p  1069.0
9      13  2019                      PW who received Haematinics  5697.0
10     13  2019                             PW who received LLIN   480.0
11     13  2019                            Postnatal Visit Total   663.0
12     13  2019                    Postnatal Visit within 3 days    21.0
13     13  2019                       Postnatal visits >= 7 days   529.0
14     13  2019                     Postnatal visit within 1 day    54.0
15     18  2019                        ANC Syphilis case treated     0.0
16     18  2019                           ANC Syphilis test done    36.0
17     18  2019                       ANC Syphilis test positive     4.0
18     18  2019  Antenatal 1st (booking) visit 20 weeks or later  1330.0
19     18  2019    Antenatal 1st (booking) visit before 20 weeks  1341.0
20     18  2019                              Antenatal 4th Visit   521.0
21     18  2019                       Antenatal total attendance  7772.0

In [13]:
print("len", len(new_df['data_point'].unique()))
sorted(new_df['data_point'].unique())

len 34

['ANC 1st Visit',
 'ANC 4th visit',
 'ANC 8th Visit',
 'ANC Attendance',
 'ANC Hep. B referred',
 'ANC Hep. B test done',
 'ANC Hep. B test positive',
 'ANC Hep. C Referred',
 'ANC Hep. C test done',
 'ANC Hep. C test positive',
 'ANC Syphilis case treated',
 'ANC Syphilis test done',
 'ANC Syphilis test positive',
 'Antenatal 1st (booking) visit 20 weeks or later',
 'Antenatal 1st (booking) visit before 20 weeks',
 'Antenatal 4th Visit',
 'Antenatal total attendance',
 'IPT1p',
 'IPT2p',
 'IPT3p',
 'IPT>= 4',
 'PW Counselled on FGM',
 'PW Counselled on FP',
 'PW Counselled on Maternal',
 'PW Counselled on Maternal Nutrition',
 'PW who received Haematinics',
 'PW who received LLIN',
 'PW with Proteinuria',
 'PW with Severe Anaemia',
 'Postnatal Clinic Visits',
 'Postnatal Visit Total',
 'Postnatal Visit within 3 days',
 'Postnatal visit within 1 day',
 'Postnatal visits >= 7 days']

In [12]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                                       data_point  value
0     13  2019                        ANC Syphilis case treated      2
1     13  2019                           ANC Syphilis test done    505
2     13  2019                       ANC Syphilis test positive      0
3     13  2019  Antenatal 1st (booking) visit 20 weeks or later   1470
4     13  2019    Antenatal 1st (booking) visit before 20 weeks    710

In [14]:
new_df.to_excel("transposed/maternal_health_indices.xlsx", index=False)
print("Done!")

Done!