In [1]:
import pandas as pd

28007.238494543704

In [10]:
df = pd.read_excel("data/PW and WRA data 2021-2025.xlsx")

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [11]:
df = df.fillna(0)
df.replace(['NA', 'NIL'], 0, inplace=True)

df.head()

,LGA,population of district 2021 (2.8%),Total no of PW 2021 (5% of Pop),Total no of women reproductive age 2021 (22% of Pop),population of district 2022 (2.8%),Total no of PW 2022 (5% of Pop),Total no of women reproductive age 2022 (22% of Pop),population of district 2023 (2.8%),Total no of PW 2023 (5% of Pop),Total no of women reproductive age 2023 (22% of Pop),population of district 2024 (2.8%),Total no of PW 2024 (5% of Pop),Total no of women reproductive age 2024 (22% of Pop),population of district 2025 (2.8%),Total no of PW 2025 (5% of Pop),Total no of women reproductive age 2025 (22% of Pop)
0,Aguata,560144.769891,28007.238495,123231.849376,575828.823448,28791.441172,126682.341159,591952.030504,29597.601525,130229.446711,622378.364872,30426.334368,136923.240272,653656.636603,31278.271730,143804.460053
1,Anambra East,232020.676097,11601.033805,51044.548741,238517.255028,11925.862751,52473.796106,245195.738168,12259.786908,53943.062397,257798.799110,12603.060942,56715.735804,270754.745758,12955.946648,59566.044067
2,Anambra West,253334.117102,12666.705855,55733.505763,260427.472381,13021.373619,57294.043924,267719.441608,13385.972080,58898.277154,281480.220907,13760.779299,61925.648599,295626.302026,14146.081119,65037.786446
3,Anaocha,431265.410967,21563.270548,94878.390413,443340.842474,22167.042124,97534.985344,455754.386063,22787.719303,100265.964934,479180.161507,23425.775444,105419.635532,503261.858663,24081.697156,110717.608906
4,Awka North,170398.577547,8519.928877,37487.687060,175169.737719,8758.486886,38537.342298,180074.490375,9003.724519,39616.387882,189330.319180,9255.828805,41652.670220,198845.311192,9514.992012,43745.968462

In [15]:
columns = ['lga_id', 'timestamp', 'district_population', 'total_num_of_pw', 'total_no_of_women_reproductive_age']

new_df = pd.DataFrame(columns=columns)

for index, row in df.iterrows():
    if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"].upper(), "lga_id"].values) == 0):
        print(row["LGA"])
    else:
        for i in range(1, len(df.columns), 3):
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"].upper(), "lga_id"].values[0],
                'timestamp': "12-31-" + str(int(df.columns[i].split()[-2])),
                'district_population': round(row[df.columns[i]]),
                # these values are meant to be derived from the district population
                'total_num_of_pw': round(row[df.columns[i+1]]), # 5% of pop
                'total_no_of_women_reproductive_age': round(row[df.columns[i+2]]), # 22% of pop
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,lga_id,timestamp,district_population,total_num_of_pw,total_no_of_women_reproductive_age
0,13,12-31-2021,560145,28007,123232
1,13,12-31-2022,575829,28791,126682
2,13,12-31-2023,591952,29598,130229
3,13,12-31-2024,622378,30426,136923
4,13,12-31-2025,653657,31278,143804
5,18,12-31-2021,232021,11601,51045
6,18,12-31-2022,238517,11926,52474
7,18,12-31-2023,245196,12260,53943
8,18,12-31-2024,257799,12603,56716
9,18,12-31-2025,270755,12956,59566
10,2,12-31-2021,253334,12667,55734
11,2,12-31-2022,260427,13021,57294
12,2,12-31-2023,267719,13386,58898
13,2,12-31-2024,281480,13761,61926
14,2,12-31-2025,295626,14146,65038
15,9,12-31-2021,431265,21563,94878
16,9,12-31-2022,443341,22167,97535
17,9,12-31-2023,455754,22788,100266
18,9,12-31-2024,479180,23426,105420
19,9,12-31-2025,503262,24082,110718
20,15,12-31-2021,170399,8520,37488
21,15,12-31-2022,175170,8758,38537

In [16]:
new_df['district_population']=new_df['district_population'].astype(int)
new_df['total_num_of_pw']=new_df['total_num_of_pw'].astype(int)
new_df['total_no_of_women_reproductive_age']=new_df['total_no_of_women_reproductive_age'].astype(int)
new_df.head()

,lga_id,timestamp,district_population,total_num_of_pw,total_no_of_women_reproductive_age
0,13,12-31-2021,560145,28007,123232
1,13,12-31-2022,575829,28791,126682
2,13,12-31-2023,591952,29598,130229
3,13,12-31-2024,622378,30426,136923
4,13,12-31-2025,653657,31278,143804

In [17]:
new_df.to_excel("transposed/pw_and_wra_data.xlsx", index=False)
print("Done!")

Done!