In [1]:
import pandas as pd

In [10]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 74", "Table 75", "Table 76", "Table 77"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [11]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,ART Cervical Cancer new cases,Arthritis new cases (suspected),Asthma new cases (suspected),Breast Cancer new cases (suspected),Depression new cases (suspected),Diabetes Mellitus new cases (suspected),Hypertension New Cases (suspected),New coronary heart disease,Sickle Cell disease new cases (suspected),Snake bites new cases,Women with Gestational Diabetes,Diarrhoea new cases < 5 years,Measles new cases < 5 years,Pneumonia new cases < 5 years
0,AGUATA,0.0,411,39,0.0,4.0,395,1167,1.0,8.0,0.0,2.0,496,11,124
1,ANAMBRA EAST,0.0,191,28,0.0,1.0,130,406,2.0,8.0,3.0,8.0,464,44,153
2,ANAMBRA WEST,0.0,111,17,0.0,1.0,66,146,2.0,20.0,2.0,3.0,104,2,71
3,ANAOCHA,1.0,187,64,2.0,3.0,232,359,4.0,20.0,8.0,14.0,493,13,158
4,AWKA NORTH,0.0,156,45,0.0,0.0,164,569,3.0,13.0,11.0,9.0,545,23,136

In [12]:
columns = ['lga_id', 'year', 'data_point', 'value']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                    'year': year,
                    'data_point': " ".join(col.replace("\n", " ").split(" ")),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year                                 data_point value
0      13  2019            Arthritis new cases (suspected)   410
1      13  2019               Asthma new cases (suspected)    35
2      13  2019    Diabetes Mellitus new cases (suspected)   377
3      13  2019         Hypertension New Cases (suspected)  1482
4      13  2019                 New coronary heart disease   4.0
5      13  2019  Sickle Cell disease new cases (suspected)  21.0
6      13  2019                      Snake bites new cases   7.0
7      13  2019              Diarrhoea new cases < 5 years   419
8      13  2019                Measles new cases < 5 years    35
9      13  2019              Pneumonia new cases < 5 years   240
10     18  2019            Arthritis new cases (suspected)    69
11     18  2019               Asthma new cases (suspected)    19
12     18  2019    Diabetes Mellitus new cases (suspected)   170
13     18  2019         Hypertension New Cases (suspected)   230
14     18  2019                 New coronary heart disease   7.0
15     18  2019  Sickle Cell disease new cases (suspected)   1.0
16     18  2019                      Snake bites new cases   2.0
17     18  2019              Diarrhoea new cases < 5 years   609
18     18  2019                Measles new cases < 5 years    33
19     18  2019              Pneumonia new cases < 5 years   215
20      2  2019            Arthritis new cases (suspected)   119
21      2  2019               Asthma new cases (suspected)    23

In [14]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 16

array(['Arthritis new cases (suspected)', 'Asthma new cases (suspected)',
       'Diabetes Mellitus new cases (suspected)',
       'Hypertension New Cases (suspected)', 'New coronary heart disease',
       'Sickle Cell disease new cases (suspected)',
       'Snake bites new cases', 'Diarrhoea new cases < 5 years',
       'Measles new cases < 5 years', 'Pneumonia new cases < 5 years',
       'ART Cervical Cancer new cases',
       'Breast Cancer new cases (suspected)',
       'Depression new cases (suspected)',
       'Women with Gestational Diabetes',
       'ART Cervical Cancer new cases (suspected)',
       'Women with Gestational Diabetes (suspected)'], dtype=object)

In [15]:
new_df['value']=new_df['value'].astype(int)
new_df['year']=new_df['year'].astype(int)

new_df.head()

  lga_id  year                               data_point  value
0     13  2019          Arthritis new cases (suspected)    410
1     13  2019             Asthma new cases (suspected)     35
2     13  2019  Diabetes Mellitus new cases (suspected)    377
3     13  2019       Hypertension New Cases (suspected)   1482
4     13  2019               New coronary heart disease      4

In [16]:
new_df.to_excel("transposed/reported_cases_of_notifiable_diseases.xlsx", index=False)
print("Finished!")

Finished!