In [14]:
import pandas as pd

In [ ]:
# %pip install xlrd
# years = [2021, 2022, 2023, 2024, 2025]
dfs=[]
file_names = ["data/RH DATA 2021-2025.xls", "data/FP 2021-2025.xls"]
for i, file_name in enumerate(file_names):
    df = pd.read_excel(file_name)
    dfs.append(df)

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [16]:
for i, df in enumerate(dfs):
    dfs[i] = dfs[i].fillna(0)
    dfs[i].replace(['NA', 'NIL'], 0, inplace=True)

dfs[0].head()

,organisationunitname,ANC 1st Visit January 2021,ANC 1st Visit February 2021,ANC 1st Visit March 2021,ANC 1st Visit April 2021,ANC 1st Visit May 2021,ANC 1st Visit June 2021,ANC 1st Visit July 2021,ANC 1st Visit August 2021,ANC 1st Visit September 2021,...,"Postnatal Clinic Visits Mothers, 2 - 3d June 2024","Postnatal Clinic Visits Mothers, 2 - 3d July 2024","Postnatal Clinic Visits Mothers, 2 - 3d August 2024","Postnatal Clinic Visits Mothers, 2 - 3d September 2024","Postnatal Clinic Visits Mothers, 2 - 3d October 2024","Postnatal Clinic Visits Mothers, 2 - 3d November 2024","Postnatal Clinic Visits Mothers, 2 - 3d December 2024","Postnatal Clinic Visits Mothers, 2 - 3d January 2025","Postnatal Clinic Visits Mothers, 2 - 3d February 2025","Postnatal Clinic Visits Mothers, 2 - 3d March 2025"
0,an Aguata Local Government Area,249,236,203,211,156,245,209,157,144,...,38.0,31.0,40.0,13.0,29.0,27.0,35.0,27.0,25.0,52.0
1,an Anambra East Local Government Area,182,250,344,303,279,312,250,186,180,...,14.0,5.0,14.0,23.0,11.0,18.0,6.0,10.0,14.0,6.0
2,an Anambra West Local Government Area,72,101,33,67,79,95,64,57,84,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,an Anaocha Local Government Area,222,200,174,169,129,20,162,133,178,...,8.0,11.0,15.0,23.0,35.0,24.0,8.0,5.0,31.0,11.0
4,an Awka North Local Government Area,114,112,148,96,142,144,133,82,81,...,37.0,36.0,62.0,51.0,50.0,27.0,36.0,15.0,42.0,32.0

In [ ]:
columns = ['lga_id', 'timestamp', 'data_point', 'value']
months = {"JANUARY":"01", "FEBRUARY":"02","MARCH":"03","APRIL":"04","MAY":"05","JUNE":"06","JULY":"07","AUGUST":"08","SEPTEMBER":"09","OCTOBER":"10","NOVEMBER":"11","DECEMBER":"12"}
new_df = pd.DataFrame(columns=columns)
for df in dfs:
    for index, row in df.iterrows():
        lga = " ".join(row["organisationunitname"].upper().split()[1:-3])
        if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"].values) == 0):
            print(lga)

        else:
            for col in df.columns[1:]:
                transformed_data = [{
                    'lga_id': lga_df.loc[lga_df['lga_name'] == lga, "lga_id"].values[0],
                    'timestamp': months[col.upper().split()[-2]] + "-01-" + str(int(col.split()[-1])), #checking if the year is indeed an integer
                    'data_point': " ".join(col.replace("\n", " ").split(" ")[:-2]),
                    'value': row[col]
                }]   

                new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.tail()

      lga_id   timestamp                          data_point  value
10660      5  02-01-2021  Females using modern contraception    467
10661      5  03-01-2021  Females using modern contraception    325
10662      5  04-01-2021  Females using modern contraception    305
10663      5  05-01-2021  Females using modern contraception    266
10664      5  06-01-2021  Females using modern contraception    388
10665      5  07-01-2021  Females using modern contraception    257
10666      5  08-01-2021  Females using modern contraception    216
10667      5  09-01-2021  Females using modern contraception    250
10668      5  10-01-2021  Females using modern contraception    166
10669      5  11-01-2021  Females using modern contraception    180
10670      5  12-01-2021  Females using modern contraception    201
10671      5  01-01-2022  Females using modern contraception    214
10672      5  02-01-2022  Females using modern contraception    217
10673      5  03-01-2022  Females using modern contraception    312
10674      5  04-01-2022  Females using modern contraception    196
10675      5  05-01-2022  Females using modern contraception    261
10676      5  06-01-2022  Females using modern contraception    250
10677      5  07-01-2022  Females using modern contraception    160
10678      5  08-01-2022  Females using modern contraception    187
10679      5  09-01-2022  Females using modern contraception    198
10680      5  10-01-2022  Females using modern contraception    243
10681      5  11-01-2022  Females using modern contraception    227
10682      5  12-01-2022  Females using modern contraception    231
10683      5  01-01-2023  Females using modern contraception    280
10684      5  02-01-2023  Females using modern contraception    286
10685      5  03-01-2023  Females using modern contraception    388
10686      5  04-01-2023  Females using modern contraception    231
10687      5  05-01-2023  Females using modern contraception    221
10688      5  06-01-2023  Females using modern contraception    255
10689      5  07-01-2023  Females using modern contraception    197
10690      5  08-01-2023  Females using modern contraception    231
10691      5  09-01-2023  Females using modern contraception    263
10692      5  10-01-2023  Females using modern contraception    271
10693      5  11-01-2023  Females using modern contraception    246
10694      5  12-01-2023  Females using modern contraception    196
10695      5  01-01-2024  Females using modern contraception    244
10696      5  02-01-2024  Females using modern contraception    202
10697      5  03-01-2024  Females using modern contraception    221
10698      5  04-01-2024  Females using modern contraception  214.0
10699      5  05-01-2024  Females using modern contraception    230
10700      5  06-01-2024  Females using modern contraception    163
10701      5  07-01-2024  Females using modern contraception    178
10702      5  08-01-2024  Females using modern contraception    220
10703      5  09-01-2024  Females using modern contraception    215
10704      5  10-01-2024  Females using modern contraception    175
10705      5  11-01-2024  Females using modern contraception    184
10706      5  12-01-2024  Females using modern contraception    165
10707      5  01-01-2025  Females using modern contraception    190
10708      5  02-01-2025  Females using modern contraception    124
10709      5  03-01-2025  Females using modern contraception    173

In [18]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 10

array(['ANC 1st Visit ', 'ANC 4th visit', 'ANC 8th Visit',
       'Postnatal Clinic Visits Mothers, 1d',
       'Postnatal Clinic Visits Mothers, 2 - 3d',
       'Clients given oral pills', 'Injectables given', 'IUD inserted ',
       'Implants inserted', 'Females using modern contraception'],
      dtype=object)

In [ ]:
rh_df = pd.read_excel("data/REPRODUCTIVE HEALTH DATA 2021-2025.xls")
rh_df = rh_df.fillna(0)
rh_df.replace(['NA', 'NIL'], 0, inplace=True)


for index, row in rh_df.iterrows():
    lga = " ".join(row["organisationunitname"].upper().split()[1:-3])
    if(len(lga_df.loc[lga_df['lga_name'] == lga, "lga_id"].values) == 0):
        print(lga)

    else:
        for col in rh_df.columns[2:]:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == lga, "lga_id"].values[0],
                'timestamp': months[row["periodname"].upper().split()[0]] + "-01-" + str(int(row["periodname"].split()[-1])), #checking if the year is indeed an integer
                'data_point': " ".join(col.replace("\n", " ").split(" ")),
                'value': row[col]
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.tail()

      lga_id   timestamp                                     data_point  value
25654      1  03-01-2025                      ANC Attendance 10 - 14yrs    0.0
25655      1  03-01-2025                     ANC Attendance  15 - 19yrs   10.0
25656      1  03-01-2025                                 ANC Attendance    272
25657      1  03-01-2025            Adolescent Deliveries (10-19 years)    0.0
25658      1  03-01-2025  Females using modern contraception 10 - 14yrs    0.0
25659      1  03-01-2025    Females using modern contraception 15-19yrs    0.0
25660      1  03-01-2025                          FP clients counselled  227.0
25661      1  03-01-2025                               New FP Acceptors   53.0
25662      7  03-01-2025           Postnatal Clinic Visits Newborns, 1d   67.0
25663      7  03-01-2025       Postnatal Clinic Visits Newborns, 2 - 3d    0.0
25664      7  03-01-2025                         Post Natal Visit Total    0.0
25665      7  03-01-2025        Deliveries monitored using a partograph    5.0
25666      7  03-01-2025   Deliveries by Skilled Birth Attendants (SBA)   68.0
25667      7  03-01-2025                                     Deliveries     54
25668      7  03-01-2025                      ANC Attendance 10 - 14yrs    0.0
25669      7  03-01-2025                     ANC Attendance  15 - 19yrs   26.0
25670      7  03-01-2025                                 ANC Attendance    419
25671      7  03-01-2025            Adolescent Deliveries (10-19 years)    0.0
25672      7  03-01-2025  Females using modern contraception 10 - 14yrs    0.0
25673      7  03-01-2025    Females using modern contraception 15-19yrs    0.0
25674      7  03-01-2025                          FP clients counselled  301.0
25675      7  03-01-2025                               New FP Acceptors  122.0
25676     21  03-01-2025           Postnatal Clinic Visits Newborns, 1d   10.0
25677     21  03-01-2025       Postnatal Clinic Visits Newborns, 2 - 3d    0.0
25678     21  03-01-2025                         Post Natal Visit Total    0.0
25679     21  03-01-2025        Deliveries monitored using a partograph   13.0
25680     21  03-01-2025   Deliveries by Skilled Birth Attendants (SBA)   42.0
25681     21  03-01-2025                                     Deliveries     45
25682     21  03-01-2025                      ANC Attendance 10 - 14yrs    0.0
25683     21  03-01-2025                     ANC Attendance  15 - 19yrs   31.0
25684     21  03-01-2025                                 ANC Attendance    251
25685     21  03-01-2025            Adolescent Deliveries (10-19 years)    7.0
25686     21  03-01-2025  Females using modern contraception 10 - 14yrs    0.0
25687     21  03-01-2025    Females using modern contraception 15-19yrs    6.0
25688     21  03-01-2025                          FP clients counselled  112.0
25689     21  03-01-2025                               New FP Acceptors   79.0
25690      5  03-01-2025           Postnatal Clinic Visits Newborns, 1d   65.0
25691      5  03-01-2025       Postnatal Clinic Visits Newborns, 2 - 3d   37.0
25692      5  03-01-2025                         Post Natal Visit Total    0.0
25693      5  03-01-2025        Deliveries monitored using a partograph   93.0
25694      5  03-01-2025   Deliveries by Skilled Birth Attendants (SBA)  131.0
25695      5  03-01-2025                                     Deliveries    131
25696      5  03-01-2025                      ANC Attendance 10 - 14yrs    0.0
25697      5  03-01-2025                     ANC Attendance  15 - 19yrs   70.0
25698      5  03-01-2025                                 ANC Attendance    884
25699      5  03-01-2025            Adolescent Deliveries (10-19 years)    7.0
25700      5  03-01-2025  Females using modern contraception 10 - 14yrs    0.0
25701      5  03-01-2025    Females using modern contraception 15-19yrs    4.0
25702      5  03-01-2025                          FP clients counselled  442.0
25703      5  03-01-2025                               New FP Acceptors  121.0

In [20]:
print("len", len(new_df['data_point'].unique()))
new_df['data_point'].unique()

len 24

array(['ANC 1st Visit ', 'ANC 4th visit', 'ANC 8th Visit',
       'Postnatal Clinic Visits Mothers, 1d',
       'Postnatal Clinic Visits Mothers, 2 - 3d',
       'Clients given oral pills', 'Injectables given', 'IUD inserted ',
       'Implants inserted', 'Females using modern contraception',
       'Postnatal Clinic Visits Newborns, 1d',
       'Postnatal Clinic Visits Newborns, 2 - 3d',
       'Post Natal Visit Total',
       'Deliveries monitored using a partograph',
       'Deliveries by Skilled Birth Attendants (SBA)', 'Deliveries',
       'ANC Attendance 10 - 14yrs', 'ANC Attendance  15 - 19yrs',
       'ANC Attendance', 'Adolescent Deliveries (10-19 years)',
       'Females using modern contraception 10 - 14yrs',
       'Females using modern contraception 15-19yrs',
       'FP clients counselled', 'New FP Acceptors'], dtype=object)

In [21]:
new_df["value"]=new_df["value"].astype(int)

new_df.head()

  lga_id   timestamp      data_point  value
0     13  01-01-2021  ANC 1st Visit     249
1     13  02-01-2021  ANC 1st Visit     236
2     13  03-01-2021  ANC 1st Visit     203
3     13  04-01-2021  ANC 1st Visit     211
4     13  05-01-2021  ANC 1st Visit     156

In [22]:
new_df.to_excel("transposed/reproductive_health_data.xlsx", index=False)
print("Finished!")

Finished!