In [1]:
import pandas as pd

In [2]:
years = [2019, 2020, 2021, 2022]
sheets = ["Table 54", "Table 55", "Table 56", "Table 57"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

            LGA  PUBLIC FACILITIES
0        AGUATA                 44
1  ANAMBRA EAST                 28
2  ANAMBRA WEST                 22
3       ANAOCHA                 34
4    AWKA NORTH                 27

In [4]:
columns = ['lga_id', 'year', 'reproductive_health_facilities']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    year = years[i]
    for index, row in df.iterrows():
        if(row["LGA"] == "IDIMILI NORTH"): row["LGA"] = "IDEMILI NORTH"
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'year': year,
                'reproductive_health_facilities': row["PUBLIC FACILITIES"],
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id  year reproductive_health_facilities
0      13  2019                             44
1      18  2019                             28
2       2  2019                             22
3       9  2019                             34
4      15  2019                             27
5      20  2019                             30
6       6  2019                             21
7      12  2019                             27
8      17  2019                             38
9       8  2019                             40
10      3  2019                             32
11     16  2019                             35
12     11  2019                             31
13     10  2019                             36
14      4  2019                             35
15     19  2019                             33
16     14  2019                             20
17      1  2019                             19
18      7  2019                             43
19     21  2019                             35
20      5  2019                             24
21     13  2020                             44

In [5]:
new_df['reproductive_health_facilities']=new_df['reproductive_health_facilities'].astype(int)
new_df.head()

  lga_id  year  reproductive_health_facilities
0     13  2019                              44
1     18  2019                              28
2      2  2019                              22
3      9  2019                              34
4     15  2019                              27

In [6]:
new_df.to_excel("reproductive_health_facilites.xlsx", index=False)
print("Done!")

Done!