In [1]:
import pandas as pd

In [9]:
# take the last month for both primary and secondary schools
session = "2023/2024"
primary_df = pd.read_csv("combine_schools.csv")
july_school_summaries = pd.read_csv("July_school_summary.csv")
july_school_summaries.head(10)

   school_id class   timestamp  gender  population
0         21  JSS1  07-01-2024    Male           0
1         21  JSS2  07-01-2024    Male           0
2         21  JSS3  07-01-2024    Male           0
3         21  SSS1  07-01-2024    Male           0
4         21  SSS2  07-01-2024    Male           0
5         21  SSS3  07-01-2024    Male           0
6         21  JSS1  07-01-2024  Female         195
7         21  JSS2  07-01-2024  Female         146
8         21  JSS3  07-01-2024  Female         133
9         21  SSS1  07-01-2024  Female         116

In [10]:
primary_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [12]:
columns = ['lga_id', 'session', 'class', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for index, row in july_school_summaries.iterrows():
    if(len(primary_df.loc[primary_df['school_id'] == row["school_id"], "lga_id"].values) == 0):
        print(row["school_id"])
    # print(row)
    else:
        transformed_data = [{
            'lga_id': primary_df.loc[primary_df['school_id'] == row["school_id"], "lga_id"].values[0],
            'session': session,
            'class': row['class'][:-1] + ' ' + row['class'][-1],
            'gender': row['gender'],
            'population': row["population"],
        }]   

        new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(50)

   lga_id    session  class  gender population
0      13  2023/2024  JSS 1    Male          0
1      13  2023/2024  JSS 2    Male          0
2      13  2023/2024  JSS 3    Male          0
3      13  2023/2024  SSS 1    Male          0
4      13  2023/2024  SSS 2    Male          0
5      13  2023/2024  SSS 3    Male          0
6      13  2023/2024  JSS 1  Female        195
7      13  2023/2024  JSS 2  Female        146
8      13  2023/2024  JSS 3  Female        133
9      13  2023/2024  SSS 1  Female        116
10     13  2023/2024  SSS 2  Female         89
11     13  2023/2024  SSS 3  Female         87
12     13  2023/2024  JSS 1    Male          0
13     13  2023/2024  JSS 2    Male          0
14     13  2023/2024  JSS 3    Male          0
15     13  2023/2024  SSS 1    Male          0
16     13  2023/2024  SSS 2    Male          0
17     13  2023/2024  SSS 3    Male          0
18     13  2023/2024  JSS 1  Female        106
19     13  2023/2024  JSS 2  Female         99
20     13  2023/2024  JSS 3  Female        130
21     13  2023/2024  SSS 1  Female        134
22     13  2023/2024  SSS 2  Female        133
23     13  2023/2024  SSS 3  Female        122
24     13  2023/2024  JSS 1    Male        182
25     13  2023/2024  JSS 2    Male        146
26     13  2023/2024  JSS 3    Male        140
27     13  2023/2024  SSS 1    Male        114
28     13  2023/2024  SSS 2    Male        125
29     13  2023/2024  SSS 3    Male        100
30     13  2023/2024  JSS 1  Female        135
31     13  2023/2024  JSS 2  Female        123
32     13  2023/2024  JSS 3  Female         96
33     13  2023/2024  SSS 1  Female        114
34     13  2023/2024  SSS 2  Female        113
35     13  2023/2024  SSS 3  Female         84
36     13  2023/2024  JSS 1    Male         37
37     13  2023/2024  JSS 2    Male         30
38     13  2023/2024  JSS 3    Male         41
39     13  2023/2024  SSS 1    Male         32
40     13  2023/2024  SSS 2    Male         22
41     13  2023/2024  SSS 3    Male         42
42     13  2023/2024  JSS 1  Female          0
43     13  2023/2024  JSS 2  Female          0
44     13  2023/2024  JSS 3  Female          0
45     13  2023/2024  SSS 1  Female          0
46     13  2023/2024  SSS 2  Female          0
47     13  2023/2024  SSS 3  Female          0
48     13  2023/2024  JSS 1    Male          0
49     13  2023/2024  JSS 2    Male          0

In [13]:
new_df['population'] = new_df['population'].astype(int)
new_df.head()

  lga_id    session  class gender  population
0     13  2023/2024  JSS 1   Male           0
1     13  2023/2024  JSS 2   Male           0
2     13  2023/2024  JSS 3   Male           0
3     13  2023/2024  SSS 1   Male           0
4     13  2023/2024  SSS 2   Male           0

In [15]:
new_df.to_excel("2024_Secondary_Schools_Population.xlsx", index=False)
print("!Done")

!Done