In [1]:
import pandas as pd

In [4]:
# take the last month for both primary and secondary schools
session = "2023/2024"
sch_df = pd.read_csv("combine_schools.csv")
july_state_of_origin = pd.read_csv("../july_state_of_origin.csv")
july_state_of_origin.head(10)
july_state_of_origin.dtypes

school_id      int64
state         object
timestamp     object
population     int64
dtype: object

In [3]:
sch_df.head()

,lga_id,school_id,school_name,school_type,category,lat,long
0,13,1,AGUATA HIGH SCH.AGUATA,PUBLIC,Secondary,NaN,NaN
1,13,2,CHRIST THE REDEEMER COLLEGE AMESI,PUBLIC,Secondary,NaN,NaN
2,13,3,COMM SEC. SCH. (BSS) EZINIFITE,PUBLIC,Secondary,NaN,NaN
3,13,4,COMM SEC. SCH. (BSS) IGBOUKWU,PUBLIC,Secondary,NaN,NaN
4,13,5,COMM SEC. SCH. AGULUEZECHUKWU,PUBLIC,Secondary,NaN,NaN

In [18]:

columns = ['lga_id', 'session', 'education_level', 'state', 'population']

new_df = pd.DataFrame(columns=columns)
july_state_of_origin["population"] = july_state_of_origin["population"].astype(int)
new_df["population"] = new_df["population"].astype(int)
for index, row in july_state_of_origin.iterrows():
    if(len(sch_df.loc[sch_df['school_id'] == row["school_id"], "lga_id"].values) == 0):
        print(row["school_id"])
    # print(row)
    else:
        # get the lga_id assoc with school_id;
        # 
        lga_id = sch_df.loc[sch_df['school_id'] == row["school_id"], "lga_id"].values[0]
        filter_df = new_df.loc[(new_df["lga_id"] == lga_id) & (new_df["state"] == row["state"])].values
        if(len(filter_df)>0):
            new_df.loc[(new_df["lga_id"]==lga_id) & (new_df["state"]==row["state"]), "population"].values[0] += int(row["population"])
        else:
                
            transformed_data = [{
                'lga_id': sch_df.loc[sch_df['school_id'] == row["school_id"], "lga_id"].values[0],
                'session': session,
                'education_level': "Secondary",
                'state': row['state'],
                'population': int(row["population"]),
            }]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(50)

   lga_id    session education_level        state  population
0      13  2023/2024       Secondary         ABIA           9
1      13  2023/2024       Secondary      ADAMAWA           0
2      13  2023/2024       Secondary    AKWA IBOM           4
3      13  2023/2024       Secondary       BAUCHI           0
4      13  2023/2024       Secondary      BAYELSA           1
5      13  2023/2024       Secondary        BENUE           4
6      13  2023/2024       Secondary        BORNO           0
7      13  2023/2024       Secondary  CROSS RIVER           2
8      13  2023/2024       Secondary        DELTA           3
9      13  2023/2024       Secondary       EBONYI          54
10     13  2023/2024       Secondary          EDO           0
11     13  2023/2024       Secondary        EKITI           1
12     13  2023/2024       Secondary        ENUGU          76
13     13  2023/2024       Secondary        GOMBE           0
14     13  2023/2024       Secondary          IMO          22
15     13  2023/2024       Secondary       JIGAWA           0
16     13  2023/2024       Secondary       KADUNA           0
17     13  2023/2024       Secondary         KANO           0
18     13  2023/2024       Secondary      KATSINA           0
19     13  2023/2024       Secondary        KEBBI           0
20     13  2023/2024       Secondary         KOGI           0
21     13  2023/2024       Secondary        KWARA           0
22     13  2023/2024       Secondary        LAGOS           0
23     13  2023/2024       Secondary     NASARAWA           1
24     13  2023/2024       Secondary        NIGER           0
25     13  2023/2024       Secondary         OGUN           0
26     13  2023/2024       Secondary         ONDO           1
27     13  2023/2024       Secondary         OSUN           0
28     13  2023/2024       Secondary          OYO           0
29     13  2023/2024       Secondary      PLATEAU           1
30     13  2023/2024       Secondary       RIVERS           0
31     13  2023/2024       Secondary       SOKOTO           0
32     13  2023/2024       Secondary       TARABA           0
33     13  2023/2024       Secondary         YOBE           0
34     13  2023/2024       Secondary      ZAMFARA           0
35     13  2023/2024       Secondary          FCT           0
36     13  2023/2024       Secondary      FOREIGN           0
37      7  2023/2024       Secondary         ABIA           5
38      7  2023/2024       Secondary      ADAMAWA           0
39      7  2023/2024       Secondary    AKWA IBOM           3
40      7  2023/2024       Secondary       BAUCHI           0
41      7  2023/2024       Secondary      BAYELSA           0
42      7  2023/2024       Secondary        BENUE           5
43      7  2023/2024       Secondary        BORNO           0
44      7  2023/2024       Secondary  CROSS RIVER           4
45      7  2023/2024       Secondary        DELTA           0
46      7  2023/2024       Secondary       EBONYI          29
47      7  2023/2024       Secondary          EDO           0
48      7  2023/2024       Secondary        EKITI           0
49      7  2023/2024       Secondary        ENUGU          37

In [20]:
new_df.to_excel("Secondary_State_of_Origin.xlsx", index=False)
print("Done!")

Done!