In [7]:
import pandas as pd

In [8]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 33", "Table 34", "Table 35", "Table 36"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,zone,196,20,48
1,2,ANAMBRA WEST,zone,613,15,21
2,3,IDEMILI SOUTH,zone,145,20,25
3,4,NNEWI SOUTH,zone,176,34,38
4,5,OYI,zone,331,10,40

In [9]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,JSS1_M,JSS1_F,JSS2_M,JSS2_F,JSS3_M,JSS3_F,M,F,TOTAL
0,AGUATA,430,505,350,466,375,462,1155,1433,2588
1,ANAMBRA EAST,209,290,165,169,182,199,556,658,1214
2,ANAMBRA WEST,75,90,63,66,115,155,253,311,564
3,ANAOCHA,520,675,440,554,348,498,1308,1727,3035
4,AWKA NORTH,135,175,119,120,170,203,424,498,922

In [10]:
columns = ['lga_id', 'session', 'class', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'JSS I',
                'gender': "Male",
                'population': row["JSS1_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'JSS I',
                'gender': "Female",
                'population': row["JSS1_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'JSS II',
                'gender': "Male",
                'population': row["JSS2_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'JSS II',
                'gender': "Female",
                'population': row["JSS2_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'JSS III',
                'gender': "Male",
                'population': row["JSS3_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'JSS III',
                'gender': "Female",
                'population': row["JSS3_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    session    class  gender population
0      13  2019/2020    JSS I    Male        444
1      13  2019/2020    JSS I  Female        543
2      13  2019/2020   JSS II    Male        413
3      13  2019/2020   JSS II  Female        439
4      13  2019/2020  JSS III    Male        339
5      13  2019/2020  JSS III  Female        450
6      18  2019/2020    JSS I    Male        242
7      18  2019/2020    JSS I  Female        258
8      18  2019/2020   JSS II    Male        159
9      18  2019/2020   JSS II  Female        170
10     18  2019/2020  JSS III    Male        170
11     18  2019/2020  JSS III  Female        175
12      2  2019/2020    JSS I    Male         84
13      2  2019/2020    JSS I  Female         79
14      2  2019/2020   JSS II    Male         62
15      2  2019/2020   JSS II  Female         80
16      2  2019/2020  JSS III    Male         95
17      2  2019/2020  JSS III  Female        107
18      9  2019/2020    JSS I    Male        498
19      9  2019/2020    JSS I  Female        645
20      9  2019/2020   JSS II    Male        445
21      9  2019/2020   JSS II  Female        579

In [11]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session    class  gender  population
0     13  2019/2020    JSS I    Male         444
1     13  2019/2020    JSS I  Female         543
2     13  2019/2020   JSS II    Male         413
3     13  2019/2020   JSS II  Female         439
4     13  2019/2020  JSS III    Male         339

In [12]:
new_df.to_excel("Junior_Secondary_School_Population.xlsx", index=False)
print("Done!")

Done!