In [7]:
import pandas as pd

In [8]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 26", "Table 27", "Table 28", "Table 29"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [9]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,SCHOOLS,0_3_M,0_3_F,3_5_M,3_5_F,5_M,5_F,M,F,TOTAL,_6_M,_6_F,6_11_M,6_11_F,11_M,11_F,M.1,F.1,TOTAL.1
0,AGUATA,74,1071,1055,683,681,807,712,2561,2448,5009,420,397,5102,4937,480,341,6002,5675,11677
1,ANAMBRA EAST,54,907,812,650,610,679,665,2236,2087,4323,371,328,4498,4075,423,281,5292,4684,9976
2,ANAMBRA WEST,58,671,676,474,450,540,459,1685,1585,3270,238,188,2883,2332,271,161,3392,2681,6073
3,ANAOCHA,51,861,835,548,528,571,489,1980,1852,3832,318,310,3862,3854,364,266,4544,4430,8974
4,AWKA NORTH,38,619,642,503,480,509,446,1631,1568,3199,246,217,2985,2697,281,186,3512,3100,6612

In [10]:
columns = ['lga_id', 'session', 'education_level', 'age_group', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRE-PRIMARY',
                'age_group': 'BELOW 3 Years',
                'gender': "Male",
                'population': row["0_3_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRE-PRIMARY',
                'age_group': 'BELOW 3 Years',
                'gender': "Female",
                'population': row["0_3_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRE-PRIMARY',
                'age_group': '3 - 5 Years',
                'gender': "Male",
                'population': row["3_5_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRE-PRIMARY',
                'age_group': '3 - 5 Years',
                'gender': "Female",
                'population': row["3_5_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRE-PRIMARY',
                'age_group': '5 Years & Above',
                'gender': "Male",
                'population': row["5_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRE-PRIMARY',
                'age_group': '5 Years & Above',
                'gender': "Female",
                'population': row["5_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRIMARY',
                'age_group': 'BELOW 6 Years',
                'gender': "Male",
                'population': row["_6_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRIMARY',
                'age_group': 'BELOW 6 Years',
                'gender': "Female",
                'population': row["_6_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRIMARY',
                'age_group': '6 - 11 Years',
                'gender': "Male",
                'population': row["6_11_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRIMARY',
                'age_group': '6 - 11 Years',
                'gender': "Female",
                'population': row["6_11_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRIMARY',
                'age_group': '11 Years & Above',
                'gender': "Male",
                'population': row["11_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'PRIMARY',
                'age_group': '11 Years & Above',
                'gender': "Female",
                'population': row["11_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    session education_level         age_group  gender population
0      13  2019/2020     PRE-PRIMARY     BELOW 3 Years    Male         36
1      13  2019/2020     PRE-PRIMARY     BELOW 3 Years  Female         32
2      13  2019/2020     PRE-PRIMARY       3 - 5 Years    Male       2173
3      13  2019/2020     PRE-PRIMARY       3 - 5 Years  Female       1925
4      13  2019/2020     PRE-PRIMARY   5 Years & Above    Male       1100
5      13  2019/2020     PRE-PRIMARY   5 Years & Above  Female       1010
6      13  2019/2020         PRIMARY     BELOW 6 Years    Male       1338
7      13  2019/2020         PRIMARY     BELOW 6 Years  Female       1405
8      13  2019/2020         PRIMARY      6 - 11 Years    Male      16248
9      13  2019/2020         PRIMARY      6 - 11 Years  Female      15108
10     13  2019/2020         PRIMARY  11 Years & Above    Male       1529
11     13  2019/2020         PRIMARY  11 Years & Above  Female       1054
12     18  2019/2020     PRE-PRIMARY     BELOW 3 Years    Male        869
13     18  2019/2020     PRE-PRIMARY     BELOW 3 Years  Female        810
14     18  2019/2020     PRE-PRIMARY       3 - 5 Years    Male       1470
15     18  2019/2020     PRE-PRIMARY       3 - 5 Years  Female       1497
16     18  2019/2020     PRE-PRIMARY   5 Years & Above    Male         71
17     18  2019/2020     PRE-PRIMARY   5 Years & Above  Female         99
18     18  2019/2020         PRIMARY     BELOW 6 Years    Male        361
19     18  2019/2020         PRIMARY     BELOW 6 Years  Female        395
20     18  2019/2020         PRIMARY      6 - 11 Years    Male       4388
21     18  2019/2020         PRIMARY      6 - 11 Years  Female       4243

In [11]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session education_level        age_group  gender  population
0     13  2019/2020     PRE-PRIMARY    BELOW 3 Years    Male          36
1     13  2019/2020     PRE-PRIMARY    BELOW 3 Years  Female          32
2     13  2019/2020     PRE-PRIMARY      3 - 5 Years    Male        2173
3     13  2019/2020     PRE-PRIMARY      3 - 5 Years  Female        1925
4     13  2019/2020     PRE-PRIMARY  5 Years & Above    Male        1100

In [12]:
new_df.to_excel("Primary_School_Population_By_Age_Group.xlsx", index=False)
print("Done!")

Done!