In [6]:
import pandas as pd

In [ ]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 22", "Table 23", "Table 24", "Table 25"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,zone,196,20,48
1,2,ANAMBRA WEST,zone,613,15,21
2,3,IDEMILI SOUTH,zone,145,20,25
3,4,NNEWI SOUTH,zone,176,34,38
4,5,OYI,zone,331,10,40

In [8]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,SCHOOLS,PRY1_M,PRY1_F,PRY2_M,PRY2_F,PRY3_M,PRY3_F,PRY4_M,PRY4_F,PRY5_M,PRY5_F,PRY6_M,PRY6_F,M,F,TOTAL
0,AGUATA,74,882,815,1697,909,890,1032,885,1023,837,1006,811,890,6002,5675,11677
1,ANAMBRA EAST,54,743,800,1543,759,763,787,771,799,770,789,702,750,5292,4684,9976
2,ANAMBRA WEST,58,557,527,1084,490,501,470,477,421,389,411,384,362,3392,2681,6073
3,ANAOCHA,51,694,608,1302,725,599,758,689,805,635,782,625,752,4544,4430,8974
4,AWKA NORTH,38,524,500,1024,512,503,527,515,525,450,546,496,490,3512,3100,6612

In [9]:
columns = ['lga_id', 'session', 'class', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 1',
                'gender': "Male",
                'population': row["PRY1_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 1',
                'gender': "Female",
                'population': row["PRY1_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 2',
                'gender': "Male",
                'population': row["PRY2_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 2',
                'gender': "Female",
                'population': row["PRY2_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 3',
                'gender': "Male",
                'population': row["PRY3_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 3',
                'gender': "Female",
                'population': row["PRY3_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 4',
                'gender': "Male",
                'population': row["PRY4_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 4',
                'gender': "Female",
                'population': row["PRY4_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 5',
                'gender': "Male",
                'population': row["PRY5_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 5',
                'gender': "Female",
                'population': row["PRY5_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 6',
                'gender': "Male",
                'population': row["PRY6_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'PRIMARY 6',
                'gender': "Female",
                'population': row["PRY6_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    session      class  gender population
0      13  2019/2020  PRIMARY 1    Male       4679
1      13  2019/2020  PRIMARY 1  Female       4277
2      13  2019/2020  PRIMARY 2    Male       3242
3      13  2019/2020  PRIMARY 2  Female       3089
4      13  2019/2020  PRIMARY 3    Male       3027
5      13  2019/2020  PRIMARY 3  Female       2873
6      13  2019/2020  PRIMARY 4    Male       2968
7      13  2019/2020  PRIMARY 4  Female       2325
8      13  2019/2020  PRIMARY 5    Male       2304
9      13  2019/2020  PRIMARY 5  Female       2237
10     13  2019/2020  PRIMARY 6    Male       2895
11     13  2019/2020  PRIMARY 6  Female       2766
12     18  2019/2020  PRIMARY 1    Male        882
13     18  2019/2020  PRIMARY 1  Female        851
14     18  2019/2020  PRIMARY 2    Male        877
15     18  2019/2020  PRIMARY 2  Female        878
16     18  2019/2020  PRIMARY 3    Male        878
17     18  2019/2020  PRIMARY 3  Female        913
18     18  2019/2020  PRIMARY 4    Male        851
19     18  2019/2020  PRIMARY 4  Female        724
20     18  2019/2020  PRIMARY 5    Male        857
21     18  2019/2020  PRIMARY 5  Female        832

In [10]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session      class  gender  population
0     13  2019/2020  PRIMARY 1    Male        4679
1     13  2019/2020  PRIMARY 1  Female        4277
2     13  2019/2020  PRIMARY 2    Male        3242
3     13  2019/2020  PRIMARY 2  Female        3089
4     13  2019/2020  PRIMARY 3    Male        3027

In [11]:
new_df.to_excel("Primary_School_Population.xlsx", index=False)
print("Done!")

Done!