In [1]:
import pandas as pd

In [2]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 41", "Sheet1", "Sheet2", "Sheet3"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,_12_M,_12_F,12_14_M,12_14_F,15_M,15_F,M,F,TOTAL,_15_M,_15_F,15_17_M,15_17_F,18_M,18_F,M.1,F.1,Unnamed: 18,TOTAL.1
0,ANAMBRA WEST,35,29,157,236,61,46,253,311,564,12,8,166,200,60,77,238,285,523,0.0
1,ANAOCHA,375,520,509,693,424,514,1308,1727,3035,329,533,710,677,259,497,1298,1707,3005,0.0
2,AWKA NORTH,113,138,144,179,167,181,424,498,922,113,140,136,136,159,204,408,480,888,0.0
3,AWKA SOUTH,344,583,1020,1500,719,1016,2083,3099,5182,443,552,1219,1933,407,595,2069,3080,5149,0.0
4,AYAMELUM,149,111,220,274,102,117,471,502,973,83,73,271,283,104,137,458,493,951,0.0

In [4]:
columns = ['lga_id', 'session', 'education_level', 'age_group', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Junior Secondary',
                'age_group': 'BELOW 12 Years',
                'gender': "Male",
                'population': row["_12_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Junior Secondary',
                'age_group': 'BELOW 12 Years',
                'gender': "Female",
                'population': row["_12_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Junior Secondary',
                'age_group': '12 - 14 Years',
                'gender': "Male",
                'population': row["12_14_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Junior Secondary',
                'age_group': '12 - 14 Years',
                'gender': "Female",
                'population': row["12_14_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Junior Secondary',
                'age_group': '15 Years & Above',
                'gender': "Male",
                'population': row["15_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Junior Secondary',
                'age_group': '15 Years & Above',
                'gender': "Female",
                'population': row["15_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Senior Secondary',
                'age_group': 'BELOW 15 Years',
                'gender': "Male",
                'population': row["_15_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Senior Secondary',
                'age_group': 'BELOW 15 Years',
                'gender': "Female",
                'population': row["_15_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Senior Secondary',
                'age_group': '15 - 17 Years',
                'gender': "Male",
                'population': row["15_17_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Senior Secondary',
                'age_group': '15 - 17 Years',
                'gender': "Female",
                'population': row["15_17_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Senior Secondary',
                'age_group': '18 Years & Above',
                'gender': "Male",
                'population': row["18_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Senior Secondary',
                'age_group': '18 Years & Above',
                'gender': "Female",
                'population': row["18_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    session   education_level         age_group  gender population
0      13  2019/2020  Junior Secondary    BELOW 12 Years    Male        266
1      13  2019/2020  Junior Secondary    BELOW 12 Years  Female        302
2      13  2019/2020  Junior Secondary     12 - 14 Years    Male        420
3      13  2019/2020  Junior Secondary     12 - 14 Years  Female        559
4      13  2019/2020  Junior Secondary  15 Years & Above    Male        510
5      13  2019/2020  Junior Secondary  15 Years & Above  Female        571
6      13  2019/2020  Senior Secondary    BELOW 15 Years    Male        412
7      13  2019/2020  Senior Secondary    BELOW 15 Years  Female        508
8      13  2019/2020  Senior Secondary     15 - 17 Years    Male        353
9      13  2019/2020  Senior Secondary     15 - 17 Years  Female        441
10     13  2019/2020  Senior Secondary  18 Years & Above    Male        424
11     13  2019/2020  Senior Secondary  18 Years & Above  Female        456
12     18  2019/2020  Junior Secondary    BELOW 12 Years    Male         21
13     18  2019/2020  Junior Secondary    BELOW 12 Years  Female         22
14     18  2019/2020  Junior Secondary     12 - 14 Years    Male        520
15     18  2019/2020  Junior Secondary     12 - 14 Years  Female        543
16     18  2019/2020  Junior Secondary  15 Years & Above    Male         30
17     18  2019/2020  Junior Secondary  15 Years & Above  Female         38
18     18  2019/2020  Senior Secondary    BELOW 15 Years    Male        100
19     18  2019/2020  Senior Secondary    BELOW 15 Years  Female        202
20     18  2019/2020  Senior Secondary     15 - 17 Years    Male        271
21     18  2019/2020  Senior Secondary     15 - 17 Years  Female        170

In [5]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session   education_level         age_group  gender  population
0     13  2019/2020  Junior Secondary    BELOW 12 Years    Male         266
1     13  2019/2020  Junior Secondary    BELOW 12 Years  Female         302
2     13  2019/2020  Junior Secondary     12 - 14 Years    Male         420
3     13  2019/2020  Junior Secondary     12 - 14 Years  Female         559
4     13  2019/2020  Junior Secondary  15 Years & Above    Male         510

In [6]:
new_df.to_excel("Secondary_School_Population_By_Age_Group.xlsx", index=False)
print("Done!")

Done!