In [1]:
import pandas as pd

In [2]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 37", "Table 38", "Table 39", "Table 40"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,zone,196,20,48
1,2,ANAMBRA WEST,zone,613,15,21
2,3,IDEMILI SOUTH,zone,145,20,25
3,4,NNEWI SOUTH,zone,176,34,38
4,5,OYI,zone,331,10,40

In [3]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,SSS1_M,SSS1_F,SSS2_M,SSS2_F,SSS3_M,SSS3_F,M,F,TOTAL
0,AGUATA,418,498,349,463,360,452,1127,1413,2540
1,ANAMBRA EAST,198,270,165,166,187,186,550,622,1172
2,ANAMBRA WEST,70,80,63,61,105,144,238,285,523
3,ANAOCHA,519,670,440,547,339,490,1298,1707,3005
4,AWKA NORTH,132,161,119,117,157,202,408,480,888

In [4]:
columns = ['lga_id', 'session', 'class', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'SSS I',
                'gender': "Male",
                'population': row["SSS1_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'SSS I',
                'gender': "Female",
                'population': row["SSS1_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'SSS II',
                'gender': "Male",
                'population': row["SSS2_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'SSS II',
                'gender': "Female",
                'population': row["SSS2_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'SSS III',
                'gender': "Male",
                'population': row["SSS3_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'class': 'SSS III',
                'gender': "Female",
                'population': row["SSS3_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    session    class  gender population
0      13  2019/2020    SSS I    Male        439
1      13  2019/2020    SSS I  Female        533
2      13  2019/2020   SSS II    Male        414
3      13  2019/2020   SSS II  Female        432
4      13  2019/2020  SSS III    Male        336
5      13  2019/2020  SSS III  Female        440
6      18  2019/2020    SSS I    Male        237
7      18  2019/2020    SSS I  Female        248
8      18  2019/2020   SSS II    Male        156
9      18  2019/2020   SSS II  Female        155
10     18  2019/2020  SSS III    Male        165
11     18  2019/2020  SSS III  Female        165
12      2  2019/2020    SSS I    Male         79
13      2  2019/2020    SSS I  Female         69
14      2  2019/2020   SSS II    Male         66
15      2  2019/2020   SSS II  Female         69
16      2  2019/2020  SSS III    Male         90
17      2  2019/2020  SSS III  Female        102
18      9  2019/2020    SSS I    Male        493
19      9  2019/2020    SSS I  Female        635
20      9  2019/2020   SSS II    Male        443
21      9  2019/2020   SSS II  Female        573

In [5]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session    class  gender  population
0     13  2019/2020    SSS I    Male         439
1     13  2019/2020    SSS I  Female         533
2     13  2019/2020   SSS II    Male         414
3     13  2019/2020   SSS II  Female         432
4     13  2019/2020  SSS III    Male         336

In [7]:
new_df.to_excel("Senior_Secondary_School_Population.xlsx", index=False)
print("Done!")

Done!