In [7]:
import pandas as pd

In [8]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 30", "Sheet12", "Table 31", "Table 32"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,zone,196,20,48
1,2,ANAMBRA WEST,zone,613,15,21
2,3,IDEMILI SOUTH,zone,145,20,25
3,4,NNEWI SOUTH,zone,176,34,38
4,5,OYI,zone,331,10,40

In [9]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,SCHOOLS,M,F,NCE_M,NCE_F,PDGE_M,PDGE_F,BED_M,BED_F,MED_M,MED_F,GRADEII_M,GRADEII_F,OTHERS_M,OTHERS_F
0,AGUATA,74,10,495,5,313,0,0,3,154,0,4,0,0,2,24
1,ANAMBRA EAST,54,62,471,48,282,0,0,10,178,1,4,0,0,3,7
2,ANAMBRA WEST,58,109,156,90,103,0,0,17,50,0,3,0,0,2,0
3,ANAOCHA,51,1,392,0,197,0,0,1,175,0,2,0,0,0,18
4,AWKA NORTH,38,38,313,32,210,0,0,6,86,0,6,0,0,0,11

In [10]:
columns = ['lga_id', 'session', 'education_level', 'qualification', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'NCE',
                'gender': "Male",
                'population': row["NCE_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'NCE',
                'gender': "Female",
                'population': row["NCE_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'PDGE',
                'gender': "Male",
                'population': row["PDGE_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'PDGE',
                'gender': "Female",
                'population': row["PDGE_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'B.ED',
                'gender': "Male",
                'population': row["BED_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'B.ED',
                'gender': "Female",
                'population': row["BED_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'M.ED',
                'gender': "Male",
                'population': row["MED_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'M.ED',
                'gender': "Female",
                'population': row["MED_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'GRADE II',
                'gender': "Male",
                'population': row["GRADEII_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'GRADE II',
                'gender': "Female",
                'population': row["GRADEII_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'OTHERS(Ph.D, M.SC)',
                'gender': "Male",
                'population': row["OTHERS_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Primary',
                'qualification': 'OTHERS(Ph.D, M.SC)',
                'gender': "Female",
                'population': row["OTHERS_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

   lga_id    session education_level       qualification  gender population
0      13  2019/2020         Primary                 NCE    Male         11
1      13  2019/2020         Primary                 NCE  Female        346
2      13  2019/2020         Primary                PDGE    Male          1
3      13  2019/2020         Primary                PDGE  Female         41
4      13  2019/2020         Primary                B.ED    Male          6
5      13  2019/2020         Primary                B.ED  Female        192
6      13  2019/2020         Primary                M.ED    Male          0
7      13  2019/2020         Primary                M.ED  Female         15
8      13  2019/2020         Primary            GRADE II    Male          0
9      13  2019/2020         Primary            GRADE II  Female          0
10     13  2019/2020         Primary  OTHERS(Ph.D, M.SC)    Male          8
11     13  2019/2020         Primary  OTHERS(Ph.D, M.SC)  Female         13
12     18  2019/2020         Primary                 NCE    Male         35
13     18  2019/2020         Primary                 NCE  Female        265
14     18  2019/2020         Primary                PDGE    Male          1
15     18  2019/2020         Primary                PDGE  Female         11
16     18  2019/2020         Primary                B.ED    Male          9
17     18  2019/2020         Primary                B.ED  Female         98
18     18  2019/2020         Primary                M.ED    Male          3
19     18  2019/2020         Primary                M.ED  Female          3
20     18  2019/2020         Primary            GRADE II    Male          0
21     18  2019/2020         Primary            GRADE II  Female          0

In [11]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session education_level qualification  gender  population
0     13  2019/2020         Primary           NCE    Male          11
1     13  2019/2020         Primary           NCE  Female         346
2     13  2019/2020         Primary          PDGE    Male           1
3     13  2019/2020         Primary          PDGE  Female          41
4     13  2019/2020         Primary          B.ED    Male           6

In [12]:
new_df.to_excel("primary_school_teacher_population.xlsx", index=False)
print("Done!")

Done!