In [11]:
import pandas as pd

In [12]:
sessions = ["2019/2020", "2020/2021", "2021/2022", "2022/2023"]
sheets = ["Table 42", "Table 43", "Table 44", "Table 45"]
dfs = []
for index, sheet in enumerate(sheets):
    dfs.append(pd.read_excel("../AGRICULTURE/anambra_2022_year_book.xlsx", sheet_name=sheets[index]))

lga_df = pd.read_csv("../Geography/Anambra_LGAs.csv")
lga_df.head()

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,zone,196,20,48
1,2,ANAMBRA WEST,zone,613,15,21
2,3,IDEMILI SOUTH,zone,145,20,25
3,4,NNEWI SOUTH,zone,176,34,38
4,5,OYI,zone,331,10,40

In [13]:
for index, df in enumerate(dfs):
    dfs[index] = dfs[index].fillna(0)
    dfs[index].replace(['NA', 'NIL'], 0, inplace=True)

dfs[1].head()

,LGA,TEACHERS,NCE_M,NCE_F,PDGE_M,PDGE_F,BED_M,BED_F,MED_M,MED_F,GRADEII_M,GRADEII_F,TRCN_M,TRCN_F,OTHERS_M,OTHERS_F
0,AGUATA,444,5,64,9,7,12,116,4,4,0,0,23,174,7,19
1,ANAMBRA EAST,329,7,48,2,4,25,96,1,3,1,0,30,72,22,18
2,ANAMBRA WEST,141,30,18,6,2,30,19,0,1,0,0,13,5,9,8
3,ANAOCHA,408,4,42,2,17,10,127,0,13,0,0,10,138,4,41
4,AWKA NORTH,145,1,22,1,5,2,46,1,6,0,0,7,40,8,6

In [14]:
columns = ['lga_id', 'session', 'education_level', 'qualification', 'gender', 'population']

new_df = pd.DataFrame(columns=columns)

for i, df in enumerate(dfs):
    session = sessions[i]
    for index, row in df.iterrows():
        if(len(lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values) == 0):
            print(row["LGA"])
        # print(row)
        else:
            transformed_data = [{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'NCE',
                'gender': "Male",
                'population': row["NCE_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'NCE',
                'gender': "Female",
                'population': row["NCE_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'PDGE',
                'gender': "Male",
                'population': row["PDGE_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'PDGE',
                'gender': "Female",
                'population': row["PDGE_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'B.ED',
                'gender': "Male",
                'population': row["BED_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'B.ED',
                'gender': "Female",
                'population': row["BED_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'M.ED',
                'gender': "Male",
                'population': row["MED_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'M.ED',
                'gender': "Female",
                'population': row["MED_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'GRADE II',
                'gender': "Male",
                'population': row["GRADEII_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'GRADE II',
                'gender': "Female",
                'population': row["GRADEII_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'TRCN',
                'gender': "Male",
                'population': row["TRCN_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'TRCN',
                'gender': "Female",
                'population': row["TRCN_F"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'OTHERS(Ph.D, M.SC)',
                'gender': "Male",
                'population': row["OTHERS_M"],
            },{
                'lga_id': lga_df.loc[lga_df['lga_name'] == row["LGA"], "lga_id"].values[0],
                'session': session,
                'education_level': 'Secondary',
                'qualification': 'OTHERS(Ph.D, M.SC)',
                'gender': "Female",
                'population': row["OTHERS_F"],
            },]   

            new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

C:\Users\USER\AppData\Local\Temp\ipykernel_2764\3697287927.py:112: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)

   lga_id    session education_level       qualification  gender  population
0      13  2019/2020       Secondary                 NCE    Male         5.0
1      13  2019/2020       Secondary                 NCE  Female        66.0
2      13  2019/2020       Secondary                PDGE    Male         9.0
3      13  2019/2020       Secondary                PDGE  Female         8.0
4      13  2019/2020       Secondary                B.ED    Male        14.0
5      13  2019/2020       Secondary                B.ED  Female       119.0
6      13  2019/2020       Secondary                M.ED    Male         3.0
7      13  2019/2020       Secondary                M.ED  Female         3.0
8      13  2019/2020       Secondary            GRADE II    Male         0.0
9      13  2019/2020       Secondary            GRADE II  Female         0.0
10     13  2019/2020       Secondary                TRCN    Male        24.0
11     13  2019/2020       Secondary                TRCN  Female       172.0
12     13  2019/2020       Secondary  OTHERS(Ph.D, M.SC)    Male         7.0
13     13  2019/2020       Secondary  OTHERS(Ph.D, M.SC)  Female        19.0
14     18  2019/2020       Secondary                 NCE    Male         5.0
15     18  2019/2020       Secondary                 NCE  Female        53.0
16     18  2019/2020       Secondary                PDGE    Male         3.0
17     18  2019/2020       Secondary                PDGE  Female         2.0
18     18  2019/2020       Secondary                B.ED    Male        22.0
19     18  2019/2020       Secondary                B.ED  Female        77.0
20     18  2019/2020       Secondary                M.ED    Male         1.0
21     18  2019/2020       Secondary                M.ED  Female         4.0

In [15]:
new_df['population']=new_df['population'].astype(int)
new_df.head()

  lga_id    session education_level qualification  gender  population
0     13  2019/2020       Secondary           NCE    Male           5
1     13  2019/2020       Secondary           NCE  Female          66
2     13  2019/2020       Secondary          PDGE    Male           9
3     13  2019/2020       Secondary          PDGE  Female           8
4     13  2019/2020       Secondary          B.ED    Male          14

In [16]:
new_df.to_excel("Secondary_school_teacher_population.xlsx", index=False)
print("Done!")

Done!