In [1]:
import pandas as pd

In [2]:
lga_df=pd.read_excel("Anambra_LGAs.xlsx")
df=pd.read_excel("Geography & Population.xlsx", sheet_name="T1")
df.head()

            LGA  AREA_SQ_KM  HIGHLANDS_percent  PLAIN_LANDS_percent
0        AGUATA         534                  0                   18
1  ANAMBRA EAST         418                  0                   12
2  ANAMBRA WEST         613                 15                   21
3       ANAOCHA         109                 36                   50
4    AWKA NORTH         356                 20                   48

In [4]:
columns = ['lga_id', 'lga_name', 'zone', 'AREA_SQ_KM', 'HIGHLANDS_percent', 'PLAIN_LANDS_percent']
new_df = pd.DataFrame(columns=columns)


for index, row in lga_df.iterrows():
    transformed_data = [{
        'lga_id': row['lga_id'],
        'lga_name': row['lga_name'],
        'zone': row['zone'],
        'AREA_SQ_KM': df.loc[df['LGA'] == row["lga_name"], 'AREA_SQ_KM'].values[0],
        'HIGHLANDS_percent': df.loc[df['LGA'] == row["lga_name"], 'HIGHLANDS_percent'].values[0],
        'PLAIN_LANDS_percent': df.loc[df['LGA'] == row["lga_name"], 'PLAIN_LANDS_percent'].values[0],
    }]   

    new_df = pd.concat([new_df, pd.DataFrame(transformed_data)], ignore_index=True)


new_df.head(22)

,lga_id,lga_name,zone,AREA_SQ_KM,HIGHLANDS_percent,PLAIN_LANDS_percent
0,1,ONITSHA SOUTH,ONITSHA,196,20,48
1,2,ANAMBRA WEST,OTUOCHA,613,15,21
2,3,IDEMILI SOUTH,OGIDI,145,20,25
3,4,NNEWI SOUTH,NNEWI,176,34,38
4,5,OYI,OGIDI,331,10,40
5,6,AYAMELUM,OTUOCHA,196,40,35
6,7,ORUMBA NORTH,AGUATA,44,15,47
7,8,IDEMILI NORTH,OGIDI,66,34,38
8,9,ANAOCHA,AKWA,109,36,50
9,10,NNEWI NORTH,NNEWI,128,34,42
10,11,NJIKOKA,AKWA,81,18,42
11,12,DUNUKOFIA,AKWA,72,28,40
12,13,AGUATA,AGUATA,534,0,18
13,14,ONITSHA NORTH,ONITSHA,305,11,39
14,15,AWKA NORTH,AKWA,356,20,48
15,16,IHIALA,NNEWI,310,22,40
16,17,EKWUSIGO,NNEWI,104,25,44
17,18,ANAMBRA EAST,OTUOCHA,418,0,12
18,19,OGBARU,ONITSHA,504,5,30
19,20,AWKA SOUTH,AKWA,175,0,61
20,21,ORUMBA SOUTH,AGUATA,24,0,14

In [4]:
new_df.to_csv("Anambra_LGAs.csv", index=False)
print("Done!")

Done!